[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchCreateResourceTags = []
BindGlobalEips = []
CreateConnectGateway = []
CreateGlobalDcGateway = []
CreateHostedDirectConnect = []
CreatePeerLink = []
CreateResourceTag = []
CreateVifPeer = []
CreateVifPeerDetection = []
CreateVirtualGateway = []
CreateVirtualInterface = []
DeleteConnectGateway = []
DeleteDirectConnect = []
DeleteGlobalDcGateway = []
DeleteHostedDirectConnect = []
DeletePeerLink = []
DeleteResourceTag = []
DeleteVifPeer = []
DeleteVifPeerDetection = []
DeleteVirtualGateway = []
DeleteVirtualInterface = []
ListConnectGateways = []
ListDirectConnectLocations = []
ListDirectConnects = []
ListGdgwRouteTables = []
ListGlobalDcGateways = []
ListGlobalEips = []
ListHostedDirectConnects = []
ListPeerLinks = []
ListProjectTags = []
ListSwitchoverTestRecords = []
ListTagResourceInstances = []
ListVifPeerDetections = []
ListVirtualGateways = []
ListVirtualInterfaces = []
ShowConnectGateway = []
ShowDirectConnect = []
ShowDirectConnectLocation = []
ShowGlobalDcGateway = []
ShowHostedDirectConnect = []
ShowPeerLink = []
ShowQuotas = []
ShowResourceTag = []
ShowVifPeerDetection = []
ShowVirtualGateway = []
ShowVirtualInterface = []
SwitchoverTest = []
UnbindGlobalEips = []
UpdateConnectGateway = []
UpdateDirectConnect = []
UpdateExtendAttribute = []
UpdateGdgwRouteTable = []
UpdateGlobalDcGateway = []
UpdateHostedDirectConnect = []
UpdatePeerLink = []
UpdateVifPeer = []
UpdateVirtualGateway = []
UpdateVirtualInterface = []
full = ["BatchCreateResourceTags", "BindGlobalEips", "CreateConnectGateway", "CreateGlobalDcGateway", "CreateHostedDirectConnect", "CreatePeerLink", "CreateResourceTag", "CreateVifPeer", "CreateVifPeerDetection", "CreateVirtualGateway", "CreateVirtualInterface", "DeleteConnectGateway", "DeleteDirectConnect", "DeleteGlobalDcGateway", "DeleteHostedDirectConnect", "DeletePeerLink", "DeleteResourceTag", "DeleteVifPeer", "DeleteVifPeerDetection", "DeleteVirtualGateway", "DeleteVirtualInterface", "ListConnectGateways", "ListDirectConnectLocations", "ListDirectConnects", "ListGdgwRouteTables", "ListGlobalDcGateways", "ListGlobalEips", "ListHostedDirectConnects", "ListPeerLinks", "ListProjectTags", "ListSwitchoverTestRecords", "ListTagResourceInstances", "ListVifPeerDetections", "ListVirtualGateways", "ListVirtualInterfaces", "ShowConnectGateway", "ShowDirectConnect", "ShowDirectConnectLocation", "ShowGlobalDcGateway", "ShowHostedDirectConnect", "ShowPeerLink", "ShowQuotas", "ShowResourceTag", "ShowVifPeerDetection", "ShowVirtualGateway", "ShowVirtualInterface", "SwitchoverTest", "UnbindGlobalEips", "UpdateConnectGateway", "UpdateDirectConnect", "UpdateExtendAttribute", "UpdateGdgwRouteTable", "UpdateGlobalDcGateway", "UpdateHostedDirectConnect", "UpdatePeerLink", "UpdateVifPeer", "UpdateVirtualGateway", "UpdateVirtualInterface"]

[lib]
name = "huawei_cloud_api_definitions_DC"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DC"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
