[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AcceptScheduledEvent = []
ApigAppExists = []
AuthorizeApiToApigApps = []
BatchBindPoolNodes = []
BatchDeletePoolNodes = []
BatchLockPoolNodes = []
BatchResizePoolNodes = []
BatchUnlockPoolNodes = []
BatchUpdatePoolNodes = []
CreateAndAuthAppAuthApi = []
CreateApigApp = []
CreateApigAppCode = []
CreateAppAuthApi = []
CreateNetwork = []
CreateNotebookTags = []
CreatePool = []
CreatePoolPlugin = []
DeleteApiAppAuth = []
DeleteApigApp = []
DeleteApigAppCode = []
DeleteAppAuthApi = []
DeleteNetwork = []
DeleteNotebookTags = []
DeletePool = []
GetAppAuthApiInfo = []
GetAppAuthApisInfo = []
GetServiceAppAuthApiAuthInfo = []
ListApigApps = []
ListEvents = []
ListNetworks = []
ListPluginTemplates = []
ListPoolNodes = []
ListPoolPlugins = []
ListPoolTags = []
ListPools = []
ListResourceFlavors = []
ListScheduledEvents = []
ListWorkloads = []
PatchNetwork = []
PatchPool = []
ResetApigAppCode = []
ResetApigAppSecret = []
ShowApigApp = []
ShowApisBindToApp = []
ShowNetwork = []
ShowNodeConfigTemplate = []
ShowNotebookTags = []
ShowOrder = []
ShowOsConfig = []
ShowOsQuota = []
ShowPluginTemplate = []
ShowPool = []
ShowPoolMonitor = []
ShowPoolNodeConfig = []
ShowPoolRuntimeMetrics = []
ShowPoolStatistics = []
ShowPoolTags = []
ShowWorkloadStatistics = []
full = ["AcceptScheduledEvent", "ApigAppExists", "AuthorizeApiToApigApps", "BatchBindPoolNodes", "BatchDeletePoolNodes", "BatchLockPoolNodes", "BatchResizePoolNodes", "BatchUnlockPoolNodes", "BatchUpdatePoolNodes", "CreateAndAuthAppAuthApi", "CreateApigApp", "CreateApigAppCode", "CreateAppAuthApi", "CreateNetwork", "CreateNotebookTags", "CreatePool", "CreatePoolPlugin", "DeleteApiAppAuth", "DeleteApigApp", "DeleteApigAppCode", "DeleteAppAuthApi", "DeleteNetwork", "DeleteNotebookTags", "DeletePool", "GetAppAuthApiInfo", "GetAppAuthApisInfo", "GetServiceAppAuthApiAuthInfo", "ListApigApps", "ListEvents", "ListNetworks", "ListPluginTemplates", "ListPoolNodes", "ListPoolPlugins", "ListPools", "ListPoolTags", "ListResourceFlavors", "ListScheduledEvents", "ListWorkloads", "PatchNetwork", "PatchPool", "ResetApigAppCode", "ResetApigAppSecret", "ShowApigApp", "ShowApisBindToApp", "ShowNetwork", "ShowNodeConfigTemplate", "ShowNotebookTags", "ShowOrder", "ShowOsConfig", "ShowOsQuota", "ShowPluginTemplate", "ShowPool", "ShowPoolMonitor", "ShowPoolNodeConfig", "ShowPoolRuntimeMetrics", "ShowPoolStatistics", "ShowPoolTags", "ShowWorkloadStatistics"]

[lib]
name = "huawei_cloud_api_definitions_ModelArts"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-ModelArts"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
