[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AcceptScheduledEvent = []
ApigAppExists = []
AttachObs = []
AuthorizeApiToApigApps = []
BatchCreateServiceTags = []
BatchDeletePoolNodes = []
BatchDeleteServiceTags = []
BatchRebootPoolNodes = []
CancelObs = []
ChangeAlgorithm = []
ChangeTrainingExperiment = []
ChangeTrainingJobDescription = []
CreateAlgorithm = []
CreateAndAuthAppAuthApi = []
CreateApigApp = []
CreateApigAppCode = []
CreateAppAuthApi = []
CreateAuthorization = []
CreateDevServer = []
CreateImage = []
CreateInspectionJob = []
CreateLogDiagnosisJob = []
CreateModel = []
CreateModelArtsAgency = []
CreateNetwork = []
CreateNetworkParameterDiagnosisJob = []
CreateNodePool = []
CreateNotebook = []
CreateNotebookTags = []
CreatePool = []
CreateProfilingDiagnosisJob = []
CreateSaveImageJob = []
CreateService = []
CreateTrainJobTags = []
CreateTrainingJob = []
CreateWorkflow = []
CreateWorkflowExecution = []
CreateWorkflowExecutionsActions = []
CreateWorkflowPurchasePool = []
CreateWorkflowSchedule = []
CreateWorkflowServiceAuth = []
CreateWorkflowStepExecutionsActions = []
CreateWorkflowSubscriptions = []
CreateWorkspace = []
DeleteAlgorithm = []
DeleteApiAppAuth = []
DeleteApigApp = []
DeleteApigAppCode = []
DeleteAppAuthApi = []
DeleteAuthorizations = []
DeleteDevServer = []
DeleteImage = []
DeleteInspectionJob = []
DeleteLogDiagnosisJob = []
DeleteModel = []
DeleteNetwork = []
DeleteNetworkDiagnosisJob1 = []
DeleteNodePool = []
DeleteNotebook = []
DeleteNotebookTags = []
DeletePool = []
DeleteProfilingDiagnosisJob = []
DeleteService = []
DeleteTrainJobTags = []
DeleteTrainingJob = []
DeleteWorkflow = []
DeleteWorkflowExecution = []
DeleteWorkflowScheduleId = []
DeleteWorkflowSubscription = []
DeleteWorkspace = []
GetAppAuthApiInfo = []
GetAppAuthApisInfo = []
GetAuthorizations = []
GetServiceAppAuthApiAuthInfo = []
ListAlgorithms = []
ListAllNotebooks = []
ListApigApps = []
ListAttachableObSs = []
ListClusters = []
ListDevServers = []
ListEvents = []
ListFlavors = []
ListImage = []
ListImageGroup = []
ListInspectionItems = []
ListInspectionJobs = []
ListInspectionNodes = []
ListLogDiagnosisJobs = []
ListModels = []
ListNetworkDiagnosisJobAlarm = []
ListNetworkDiagnosisJobProxyResponseDelimit = []
ListNetworkDiagnosisJobs = []
ListNetworks = []
ListNodePoolNodes = []
ListNodePools = []
ListNotebooks = []
ListPoolNodes = []
ListPoolTags = []
ListPools = []
ListProfilingDiagnosisJobs = []
full = ["AcceptScheduledEvent", "ApigAppExists", "AttachObs", "AuthorizeApiToApigApps", "BatchCreateServiceTags", "BatchDeletePoolNodes", "BatchDeleteServiceTags", "BatchRebootPoolNodes", "CancelObs", "ChangeAlgorithm", "ChangeTrainingExperiment", "ChangeTrainingJobDescription", "CreateAlgorithm", "CreateAndAuthAppAuthApi", "CreateApigApp", "CreateApigAppCode", "CreateAppAuthApi", "CreateAuthorization", "CreateDevServer", "CreateImage", "CreateInspectionJob", "CreateLogDiagnosisJob", "CreateModel", "CreateModelArtsAgency", "CreateNetwork", "CreateNetworkParameterDiagnosisJob", "CreateNodePool", "CreateNotebook", "CreateNotebookTags", "CreatePool", "CreateProfilingDiagnosisJob", "CreateSaveImageJob", "CreateService", "CreateTrainingJob", "CreateTrainJobTags", "CreateWorkflow", "CreateWorkflowExecution", "CreateWorkflowExecutionsActions", "CreateWorkflowPurchasePool", "CreateWorkflowSchedule", "CreateWorkflowServiceAuth", "CreateWorkflowStepExecutionsActions", "CreateWorkflowSubscriptions", "CreateWorkspace", "DeleteAlgorithm", "DeleteApiAppAuth", "DeleteApigApp", "DeleteApigAppCode", "DeleteAppAuthApi", "DeleteAuthorizations", "DeleteDevServer", "DeleteImage", "DeleteInspectionJob", "DeleteLogDiagnosisJob", "DeleteModel", "DeleteNetwork", "DeleteNetworkDiagnosisJob1", "DeleteNodePool", "DeleteNotebook", "DeleteNotebookTags", "DeletePool", "DeleteProfilingDiagnosisJob", "DeleteService", "DeleteTrainingJob", "DeleteTrainJobTags", "DeleteWorkflow", "DeleteWorkflowExecution", "DeleteWorkflowScheduleId", "DeleteWorkflowSubscription", "DeleteWorkspace", "GetAppAuthApiInfo", "GetAppAuthApisInfo", "GetAuthorizations", "GetServiceAppAuthApiAuthInfo", "ListAlgorithms", "ListAllNotebooks", "ListApigApps", "ListAttachableObSs", "ListClusters", "ListDevServers", "ListEvents", "ListFlavors", "ListImage", "ListImageGroup", "ListInspectionItems", "ListInspectionJobs", "ListInspectionNodes", "ListLogDiagnosisJobs", "ListModels", "ListNetworkDiagnosisJobAlarm", "ListNetworkDiagnosisJobProxyResponseDelimit", "ListNetworkDiagnosisJobs", "ListNetworks", "ListNodePoolNodes", "ListNodePools", "ListNotebooks", "ListPoolNodes", "ListPools", "ListPoolTags", "ListProfilingDiagnosisJobs"]

[lib]
name = "huawei_cloud_api_definitions_ModelArts"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-ModelArts"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
