[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddAclRule = []
AddAddressItem = []
AddAddressSet = []
AddBlackWhiteList = []
AddCustomDnsServer = []
AddDomainSet = []
AddDomains = []
AddEipAlarmWhitelist = []
AddLogConfig = []
AddServiceItems = []
AddServiceSet = []
BatchAddAccounts = []
BatchCreateBlackWhiteList = []
BatchCreateIpsWhitelist = []
BatchCreatePrivateNetworkSegments = []
BatchDeleteAclRules = []
BatchDeleteAddressItems = []
BatchDeleteAddressSets = []
BatchDeleteBlackWhiteLists = []
BatchDeleteCustomerIps = []
BatchDeleteDomainSet = []
BatchDeleteIpsWhitelist = []
BatchDeletePrivateNetworkSegments = []
BatchDeleteSchedules = []
BatchDeleteServiceItems = []
BatchDeleteServiceSets = []
BatchRemoveAccounts = []
BatchUpdateAclRuleActions = []
BatchUpdateCustomerIpsAction = []
CancelCaptureTask = []
ChangeEastWestFirewallStatus = []
ChangeEipStatus = []
ChangeIpsProtectMode = []
ChangeIpsRuleMode = []
ChangeIpsSwitchStatus = []
CreateCaptureTask = []
CreateCustomerIps = []
CreateEastWestFirewall = []
CreateFirewall = []
CreateReportProfile = []
CreateSchedule = []
CreateTag = []
DeleteAclRule = []
DeleteAclRuleHitCount = []
DeleteAddressItem = []
DeleteAddressSet = []
DeleteBlackWhiteList = []
DeleteCaptureTask = []
DeleteDomainSet = []
DeleteDomains = []
DeleteFirewall = []
DeleteIpBlacklist = []
DeleteReportProfile = []
DeleteSchedule = []
DeleteServiceItem = []
DeleteServiceSet = []
DeleteTag = []
DownloadExportResult = []
DownloadImportResult = []
DownloadImportTemplate = []
EnableIpBlacklist = []
EnableMultiAccount = []
ExportIpBlacklist = []
ExportLogs = []
ExportRuleAcl = []
ImportIpBlacklist = []
ImportRuleAcl = []
ListAccessControlLogs = []
ListAccounts = []
ListAclRuleHitCount = []
ListAclRuleHitStatus = []
ListAclRules = []
ListAddressItems = []
ListAddressSetDetail = []
ListAddressSets = []
ListAdvancedIpsRules = []
ListAlarmWhitelist = []
ListAttackLogs = []
ListAttackStatistic = []
ListBlackWhiteLists = []
ListCaptureResult = []
ListCaptureTask = []
ListCustomerIps = []
ListDnsServers = []
ListDomainParseDetail = []
ListDomainParseIp = []
ListDomainResolveIp = []
ListDomainSets = []
ListDomains = []
ListEastWestFirewall = []
ListEipCount = []
ListEips = []
ListFirewallDetail = []
ListFirewallList = []
ListFlowLogs = []
ListFlowStatistic = []
ListIpBlacklist = []
ListIpBlacklistSwitch = []
ListIpsProtectMode = []
ListIpsRules = []
full = ["AddAclRule", "AddAddressItem", "AddAddressSet", "AddBlackWhiteList", "AddCustomDnsServer", "AddDomains", "AddDomainSet", "AddEipAlarmWhitelist", "AddLogConfig", "AddServiceItems", "AddServiceSet", "BatchAddAccounts", "BatchCreateBlackWhiteList", "BatchCreateIpsWhitelist", "BatchCreatePrivateNetworkSegments", "BatchDeleteAclRules", "BatchDeleteAddressItems", "BatchDeleteAddressSets", "BatchDeleteBlackWhiteLists", "BatchDeleteCustomerIps", "BatchDeleteDomainSet", "BatchDeleteIpsWhitelist", "BatchDeletePrivateNetworkSegments", "BatchDeleteSchedules", "BatchDeleteServiceItems", "BatchDeleteServiceSets", "BatchRemoveAccounts", "BatchUpdateAclRuleActions", "BatchUpdateCustomerIpsAction", "CancelCaptureTask", "ChangeEastWestFirewallStatus", "ChangeEipStatus", "ChangeIpsProtectMode", "ChangeIpsRuleMode", "ChangeIpsSwitchStatus", "CreateCaptureTask", "CreateCustomerIps", "CreateEastWestFirewall", "CreateFirewall", "CreateReportProfile", "CreateSchedule", "CreateTag", "DeleteAclRule", "DeleteAclRuleHitCount", "DeleteAddressItem", "DeleteAddressSet", "DeleteBlackWhiteList", "DeleteCaptureTask", "DeleteDomains", "DeleteDomainSet", "DeleteFirewall", "DeleteIpBlacklist", "DeleteReportProfile", "DeleteSchedule", "DeleteServiceItem", "DeleteServiceSet", "DeleteTag", "DownloadExportResult", "DownloadImportResult", "DownloadImportTemplate", "EnableIpBlacklist", "EnableMultiAccount", "ExportIpBlacklist", "ExportLogs", "ExportRuleAcl", "ImportIpBlacklist", "ImportRuleAcl", "ListAccessControlLogs", "ListAccounts", "ListAclRuleHitCount", "ListAclRuleHitStatus", "ListAclRules", "ListAddressItems", "ListAddressSetDetail", "ListAddressSets", "ListAdvancedIpsRules", "ListAlarmWhitelist", "ListAttackLogs", "ListAttackStatistic", "ListBlackWhiteLists", "ListCaptureResult", "ListCaptureTask", "ListCustomerIps", "ListDnsServers", "ListDomainParseDetail", "ListDomainParseIp", "ListDomainResolveIp", "ListDomains", "ListDomainSets", "ListEastWestFirewall", "ListEipCount", "ListEips", "ListFirewallDetail", "ListFirewallList", "ListFlowLogs", "ListFlowStatistic", "ListIpBlacklist", "ListIpBlacklistSwitch", "ListIpsProtectMode", "ListIpsRules"]

[lib]
name = "huawei_cloud_api_definitions_CFW"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CFW"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
