[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddPostgresqlHbaConf = []
AllowDbPrivilege = []
AllowDbUserPrivilege = []
AllowSqlserverDbUserPrivilege = []
ApplyConfigurationAsync = []
AttachEip = []
BatchAddMsdtcs = []
BatchDeleteInstance = []
BatchDeleteManualBackup = []
BatchExecuteEvents = []
BatchModifyPublication = []
BatchModifySubscription = []
BatchRestoreDatabase = []
BatchRestorePostgreSqlTables = []
BatchStopInstance = []
BatchTagAddAction = []
BatchTagDelAction = []
ChangeFailoverMode = []
ChangeFailoverStrategy = []
ChangeOpsWindow = []
ChangeProxyScale = []
ChangeTheDelayThreshold = []
CheckInstanceForUpgrade = []
CheckWeakpwd = []
CollectPublicationMonitor = []
CollectSubscriptionMonitor = []
CompareConfiguration = []
CopyConfiguration = []
CopyDatabase = []
CreateConfiguration = []
CreateDatabase = []
CreateDbUser = []
CreateDistribution = []
CreateDnsName = []
CreateInstance = []
CreateInstanceIam5 = []
CreateIntelligentKillSession = []
CreateManualBackup = []
CreatePostgresqlDatabase = []
CreatePostgresqlDatabaseSchema = []
CreatePostgresqlDbUser = []
CreatePostgresqlExtension = []
CreatePublication = []
CreateRdSforMySqlProxy = []
CreateRebuildSlave = []
CreateRestoreInstance = []
CreateSqlLimit = []
CreateSqlserverDatabase = []
CreateSqlserverDbUser = []
CreateSubscription = []
CreateXelLogDownload = []
DeleteConfiguration = []
DeleteDatabase = []
DeleteDbUser = []
DeleteDisasterRecovery = []
DeleteDistribution = []
DeleteInstance = []
DeleteJob = []
DeleteLogLtsConfigs = []
DeleteManualBackup = []
DeleteMsdtcLocalHost = []
DeletePostgresqlDatabase = []
DeletePostgresqlDbUser = []
DeletePostgresqlExtension = []
DeletePostgresqlHbaConf = []
DeletePublication = []
DeleteRdSforMySqlProxy = []
DeleteSqlLimit = []
DeleteSqlserverDatabase = []
DeleteSqlserverDatabaseEx = []
DeleteSqlserverDbUser = []
DeleteSubscription = []
DownloadErrorlog = []
DownloadSlowlog = []
EnableConfiguration = []
ExecutePrivilegeDatabaseUserRole = []
ExecuteRevokeDatabaseUserRole = []
GetInstancesNoIndexTables = []
ListApiVersion = []
ListApiVersionNew = []
ListAuditlogs = []
ListAuthorizedDatabases = []
ListAuthorizedDbUsers = []
ListAuthorizedSqlserverDbUsers = []
ListAutoScalingPolicy = []
ListBackupTransfers = []
ListBackups = []
ListBusinessPartners = []
ListCollations = []
ListConfigurationApplyHistories = []
ListConfigurations = []
ListDatabaseUserRole = []
ListDatabases = []
ListDatastores = []
ListDbAgentJobHistorySteps = []
ListDbAgentJobHistorys = []
ListDbAgentJobs = []
ListDbUsers = []
ListDistribution = []
ListDistributorInstances = []
full = ["AddPostgresqlHbaConf", "AllowDbPrivilege", "AllowDbUserPrivilege", "AllowSqlserverDbUserPrivilege", "ApplyConfigurationAsync", "AttachEip", "BatchAddMsdtcs", "BatchDeleteInstance", "BatchDeleteManualBackup", "BatchExecuteEvents", "BatchModifyPublication", "BatchModifySubscription", "BatchRestoreDatabase", "BatchRestorePostgreSqlTables", "BatchStopInstance", "BatchTagAddAction", "BatchTagDelAction", "ChangeFailoverMode", "ChangeFailoverStrategy", "ChangeOpsWindow", "ChangeProxyScale", "ChangeTheDelayThreshold", "CheckInstanceForUpgrade", "CheckWeakpwd", "CollectPublicationMonitor", "CollectSubscriptionMonitor", "CompareConfiguration", "CopyConfiguration", "CopyDatabase", "CreateConfiguration", "CreateDatabase", "CreateDbUser", "CreateDistribution", "CreateDnsName", "CreateInstance", "CreateInstanceIam5", "CreateIntelligentKillSession", "CreateManualBackup", "CreatePostgresqlDatabase", "CreatePostgresqlDatabaseSchema", "CreatePostgresqlDbUser", "CreatePostgresqlExtension", "CreatePublication", "CreateRdSforMySqlProxy", "CreateRebuildSlave", "CreateRestoreInstance", "CreateSqlLimit", "CreateSqlserverDatabase", "CreateSqlserverDbUser", "CreateSubscription", "CreateXelLogDownload", "DeleteConfiguration", "DeleteDatabase", "DeleteDbUser", "DeleteDisasterRecovery", "DeleteDistribution", "DeleteInstance", "DeleteJob", "DeleteLogLtsConfigs", "DeleteManualBackup", "DeleteMsdtcLocalHost", "DeletePostgresqlDatabase", "DeletePostgresqlDbUser", "DeletePostgresqlExtension", "DeletePostgresqlHbaConf", "DeletePublication", "DeleteRdSforMySqlProxy", "DeleteSqlLimit", "DeleteSqlserverDatabase", "DeleteSqlserverDatabaseEx", "DeleteSqlserverDbUser", "DeleteSubscription", "DownloadErrorlog", "DownloadSlowlog", "EnableConfiguration", "ExecutePrivilegeDatabaseUserRole", "ExecuteRevokeDatabaseUserRole", "GetInstancesNoIndexTables", "ListApiVersion", "ListApiVersionNew", "ListAuditlogs", "ListAuthorizedDatabases", "ListAuthorizedDbUsers", "ListAuthorizedSqlserverDbUsers", "ListAutoScalingPolicy", "ListBackups", "ListBackupTransfers", "ListBusinessPartners", "ListCollations", "ListConfigurationApplyHistories", "ListConfigurations", "ListDatabases", "ListDatabaseUserRole", "ListDatastores", "ListDbAgentJobHistorys", "ListDbAgentJobHistorySteps", "ListDbAgentJobs", "ListDbUsers", "ListDistribution", "ListDistributorInstances"]

[lib]
name = "huawei_cloud_api_definitions_RDS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-RDS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
