[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
ApplyCertificateToHost = []
BatchCreateAntiTamperRule = []
BatchCreateAntileakageRule = []
BatchCreateCcRule = []
BatchCreateCustomRule = []
BatchCreateGeoIpRule = []
BatchCreateIgnoreRule = []
BatchCreateIpReputationRule = []
BatchCreatePrivacyRule = []
BatchCreateWhiteblackipRule = []
BatchDeleteAlertNoticeConfig = []
BatchDeleteCompositeHosts = []
BatchDeletePolicies = []
BatchDeleteRules = []
BatchUpdateAntileakageRules = []
BatchUpdateAntitamperRules = []
BatchUpdateCcRules = []
BatchUpdateCustomRules = []
BatchUpdateGeoipRules = []
BatchUpdateIgnoreRules = []
BatchUpdateIpReputationRules = []
BatchUpdatePrivacyRules = []
BatchUpdateWhiteblackipRules = []
ChangePrepaidCloudWaf = []
CheckAgency = []
ConfirmApplicationTypes = []
ConfirmAsyncJob = []
ConfirmDnsDomain = []
ConfirmIpReputationRule = []
ConfirmPolicyAntileakageMap = []
ConfirmPolicyIpReputationMap = []
ConfirmProtectionTypes = []
ConfirmThreatMap = []
ConfirmTmsResourceInstances = []
ConfirmUserBundle = []
CopyPolicyById = []
CreateAgency = []
CreateAlertNoticeConfig = []
CreateAntiTamperRule = []
CreateAnticrawlerRule = []
CreateAntileakageRule = []
CreateCcRule = []
CreateCertificate = []
CreateCustomRule = []
CreateEventExportJob = []
CreateGeoipRule = []
CreateHost = []
CreateIgnoreRule = []
CreateInstance = []
CreateIpGroup = []
CreateIpReputationRule = []
CreatePolicy = []
CreatePremiumHost = []
CreatePrepaidCloudWaf = []
CreatePrivacyRule = []
CreatePunishmentRule = []
CreateQuickAccessDomain = []
CreateSecurityReportSubscription = []
CreateValueList = []
CreateWhiteblackipRule = []
DeleteAgency = []
DeleteAnticrawlerRule = []
DeleteAntileakageRule = []
DeleteAntitamperRule = []
DeleteCcRule = []
DeleteCertificate = []
DeleteCustomRule = []
DeleteGeoipRule = []
DeleteHost = []
DeleteIgnoreRule = []
DeleteInstance = []
DeleteIpGroup = []
DeleteIpReputationRule = []
DeletePolicy = []
DeletePremiumHost = []
DeletePrivacyRule = []
DeletePunishmentRule = []
DeleteSecurityReportSubscription = []
DeleteValueList = []
DeleteWhiteBlackIpRule = []
ListAntiTamperPolicyRules = []
ListAnticrawlerRules = []
ListAntileakagePolicyRules = []
ListAntileakageRules = []
ListAntitamperRule = []
ListAttackActionTypes = []
ListBandwidthTimeline = []
ListCcPolicyRules = []
ListCcRules = []
ListCertificates = []
ListCompositeHosts = []
ListCustomPolicyRules = []
ListCustomRules = []
ListEvent = []
ListEventLog = []
ListGeoIpPolicyRules = []
ListGeoipRule = []
ListHost = []
ListHostRoute = []
ListIgnorePolicyRules = []
full = ["ApplyCertificateToHost", "BatchCreateAntileakageRule", "BatchCreateAntiTamperRule", "BatchCreateCcRule", "BatchCreateCustomRule", "BatchCreateGeoIpRule", "BatchCreateIgnoreRule", "BatchCreateIpReputationRule", "BatchCreatePrivacyRule", "BatchCreateWhiteblackipRule", "BatchDeleteAlertNoticeConfig", "BatchDeleteCompositeHosts", "BatchDeletePolicies", "BatchDeleteRules", "BatchUpdateAntileakageRules", "BatchUpdateAntitamperRules", "BatchUpdateCcRules", "BatchUpdateCustomRules", "BatchUpdateGeoipRules", "BatchUpdateIgnoreRules", "BatchUpdateIpReputationRules", "BatchUpdatePrivacyRules", "BatchUpdateWhiteblackipRules", "ChangePrepaidCloudWaf", "CheckAgency", "ConfirmApplicationTypes", "ConfirmAsyncJob", "ConfirmDnsDomain", "ConfirmIpReputationRule", "ConfirmPolicyAntileakageMap", "ConfirmPolicyIpReputationMap", "ConfirmProtectionTypes", "ConfirmThreatMap", "ConfirmTmsResourceInstances", "ConfirmUserBundle", "CopyPolicyById", "CreateAgency", "CreateAlertNoticeConfig", "CreateAnticrawlerRule", "CreateAntileakageRule", "CreateAntiTamperRule", "CreateCcRule", "CreateCertificate", "CreateCustomRule", "CreateEventExportJob", "CreateGeoipRule", "CreateHost", "CreateIgnoreRule", "CreateInstance", "CreateIpGroup", "CreateIpReputationRule", "CreatePolicy", "CreatePremiumHost", "CreatePrepaidCloudWaf", "CreatePrivacyRule", "CreatePunishmentRule", "CreateQuickAccessDomain", "CreateSecurityReportSubscription", "CreateValueList", "CreateWhiteblackipRule", "DeleteAgency", "DeleteAnticrawlerRule", "DeleteAntileakageRule", "DeleteAntitamperRule", "DeleteCcRule", "DeleteCertificate", "DeleteCustomRule", "DeleteGeoipRule", "DeleteHost", "DeleteIgnoreRule", "DeleteInstance", "DeleteIpGroup", "DeleteIpReputationRule", "DeletePolicy", "DeletePremiumHost", "DeletePrivacyRule", "DeletePunishmentRule", "DeleteSecurityReportSubscription", "DeleteValueList", "DeleteWhiteBlackIpRule", "ListAnticrawlerRules", "ListAntileakagePolicyRules", "ListAntileakageRules", "ListAntiTamperPolicyRules", "ListAntitamperRule", "ListAttackActionTypes", "ListBandwidthTimeline", "ListCcPolicyRules", "ListCcRules", "ListCertificates", "ListCompositeHosts", "ListCustomPolicyRules", "ListCustomRules", "ListEvent", "ListEventLog", "ListGeoIpPolicyRules", "ListGeoipRule", "ListHost", "ListHostRoute", "ListIgnorePolicyRules"]

[lib]
name = "huawei_cloud_api_definitions_WAF"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-WAF"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
