[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
ApplyCertificateToHost = []
BatchDeletePolicies = []
ChangePrepaidCloudWaf = []
CheckAgency = []
ConfirmApplicationTypes = []
ConfirmAsyncJob = []
ConfirmIpReputationRule = []
ConfirmPolicyAntileakageMap = []
ConfirmPolicyIpReputationMap = []
ConfirmProtectionTypes = []
ConfirmThreatMap = []
ConfirmTmsResourceInstances = []
ConfirmUserBundle = []
CreateAntiTamperRule = []
CreateAnticrawlerRule = []
CreateAntileakageRule = []
CreateCcRule = []
CreateCertificate = []
CreateCustomRule = []
CreateGeoipRule = []
CreateHost = []
CreateIgnoreRule = []
CreateInstance = []
CreateIpGroup = []
CreateIpReputationRule = []
CreatePolicy = []
CreatePremiumHost = []
CreatePrepaidCloudWaf = []
CreatePrivacyRule = []
CreatePunishmentRule = []
CreateValueList = []
CreateWhiteblackipRule = []
DeleteAnticrawlerRule = []
DeleteAntileakageRule = []
DeleteAntitamperRule = []
DeleteCcRule = []
DeleteCertificate = []
DeleteCustomRule = []
DeleteGeoipRule = []
DeleteHost = []
DeleteIgnoreRule = []
DeleteInstance = []
DeleteIpGroup = []
DeletePolicy = []
DeletePremiumHost = []
DeletePrivacyRule = []
DeletePunishmentRule = []
DeleteValueList = []
DeleteWhiteBlackIpRule = []
ListAntiTamperPolicyRules = []
ListAnticrawlerRules = []
ListAntileakagePolicyRules = []
ListAntileakageRules = []
ListAntitamperRule = []
ListAttackActionTypes = []
ListBandwidthTimeline = []
ListCcPolicyRules = []
ListCcRules = []
ListCertificates = []
ListCompositeHosts = []
ListCustomPolicyRules = []
ListCustomRules = []
ListEvent = []
ListEventLog = []
ListGeoIpPolicyRules = []
ListGeoipRule = []
ListHost = []
ListHostRoute = []
ListIgnorePolicyRules = []
ListIgnoreRule = []
ListInstance = []
ListInstanceTags = []
ListIpGroup = []
ListIpReputationPolicyRules = []
ListIpReputationRules = []
ListNoticeConfigs = []
ListOverviewsClassification = []
ListPolicy = []
ListPremiumHost = []
ListPrivacyPolicyRules = []
ListPrivacyRule = []
ListProtectableResources = []
ListPunishmentRules = []
ListQpsTimeline = []
ListRequestTimeline = []
ListResponseCodeTimeline = []
ListSecurityReportHistoryPeriods = []
ListSecurityReportSendingRecords = []
ListSecurityReportSubscriptions = []
ListStatistics = []
ListTopAbnormal = []
ListTopDomains = []
ListTopIp = []
ListTopUrl = []
ListValueList = []
ListWebBasicProtectionRules = []
ListWhiteblackipPolicyRules = []
ListWhiteblackipRule = []
MigrateCompositeHosts = []
RenameInstance = []
full = ["ApplyCertificateToHost", "BatchDeletePolicies", "ChangePrepaidCloudWaf", "CheckAgency", "ConfirmApplicationTypes", "ConfirmAsyncJob", "ConfirmIpReputationRule", "ConfirmPolicyAntileakageMap", "ConfirmPolicyIpReputationMap", "ConfirmProtectionTypes", "ConfirmThreatMap", "ConfirmTmsResourceInstances", "ConfirmUserBundle", "CreateAnticrawlerRule", "CreateAntileakageRule", "CreateAntiTamperRule", "CreateCcRule", "CreateCertificate", "CreateCustomRule", "CreateGeoipRule", "CreateHost", "CreateIgnoreRule", "CreateInstance", "CreateIpGroup", "CreateIpReputationRule", "CreatePolicy", "CreatePremiumHost", "CreatePrepaidCloudWaf", "CreatePrivacyRule", "CreatePunishmentRule", "CreateValueList", "CreateWhiteblackipRule", "DeleteAnticrawlerRule", "DeleteAntileakageRule", "DeleteAntitamperRule", "DeleteCcRule", "DeleteCertificate", "DeleteCustomRule", "DeleteGeoipRule", "DeleteHost", "DeleteIgnoreRule", "DeleteInstance", "DeleteIpGroup", "DeletePolicy", "DeletePremiumHost", "DeletePrivacyRule", "DeletePunishmentRule", "DeleteValueList", "DeleteWhiteBlackIpRule", "ListAnticrawlerRules", "ListAntileakagePolicyRules", "ListAntileakageRules", "ListAntiTamperPolicyRules", "ListAntitamperRule", "ListAttackActionTypes", "ListBandwidthTimeline", "ListCcPolicyRules", "ListCcRules", "ListCertificates", "ListCompositeHosts", "ListCustomPolicyRules", "ListCustomRules", "ListEvent", "ListEventLog", "ListGeoIpPolicyRules", "ListGeoipRule", "ListHost", "ListHostRoute", "ListIgnorePolicyRules", "ListIgnoreRule", "ListInstance", "ListInstanceTags", "ListIpGroup", "ListIpReputationPolicyRules", "ListIpReputationRules", "ListNoticeConfigs", "ListOverviewsClassification", "ListPolicy", "ListPremiumHost", "ListPrivacyPolicyRules", "ListPrivacyRule", "ListProtectableResources", "ListPunishmentRules", "ListQpsTimeline", "ListRequestTimeline", "ListResponseCodeTimeline", "ListSecurityReportHistoryPeriods", "ListSecurityReportSendingRecords", "ListSecurityReportSubscriptions", "ListStatistics", "ListTopAbnormal", "ListTopDomains", "ListTopIp", "ListTopUrl", "ListValueList", "ListWebBasicProtectionRules", "ListWhiteblackipPolicyRules", "ListWhiteblackipRule", "MigrateCompositeHosts", "RenameInstance"]

[lib]
name = "huawei_cloud_api_definitions_WAF"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-WAF"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
