[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddFullSqlTask = []
CancelShareConnections = []
ChangeChargeMode = []
ChangeFullDeadLockSwitch = []
ChangeSqlLimitSwitchStatus = []
ChangeSqlSwitch = []
ChangeTransactionSwitchStatus = []
CheckCredential = []
CreateHealthReportTask = []
CreateHistoryTransactionExportTask = []
CreateInstanceConnection = []
CreateShareConnections = []
CreateSnapshots = []
CreateSpaceAnalysisTask = []
CreateSqlLimitRules = []
CreateTuning = []
DeleteDbUser = []
DeleteHistoryTransactionExportTask = []
DeleteProcess = []
DeleteSqlLimitRules = []
ExportFullSqlDetails = []
ExportSlowQueryLogs = []
ExportSlowSqlStatistics = []
ExportSlowSqlTemplatesDetails = []
ExportSlowSqlTrendDetails = []
ExportSqlStatements = []
ExportTopRiskInstances = []
ExportTopSqlTemplatesDetails = []
ExportTopSqlTrendDetails = []
ListApiVersions = []
ListAutoIncrementUsage = []
ListCloudDbaInstances = []
ListConnections = []
ListDbUsers = []
ListFullSqlTasks = []
ListHealthReportTask = []
ListHistoryTransactionExportTask = []
ListInnodbLocks = []
ListInstanceDistribution = []
ListInstanceMultiNodesSingleMetric = []
ListInstanceNodesInfo = []
ListInstanceTopSlowLog = []
ListMetadataLocks = []
ListProcesses = []
ListRiskItems = []
ListRiskTrend = []
ListSnapshots = []
ListSpaceAnalysis = []
ListSqlLimitRules = []
ListTopSlowLog = []
ListTransactions = []
LoginBuiltInAccount = []
LogoffBuiltInAccount = []
ParseSqlLimitRules = []
RegisterDbUser = []
SaveCredential = []
SetThresholdForMetric = []
ShowApiVersion = []
ShowDasRecommendSqlLimitRule = []
ShowDbUser = []
ShowFullDeadLockList = []
ShowFullDeadLockSwitch = []
ShowHealthReportSettings = []
ShowHistoryTransactionExportTaskInfo = []
ShowInstanceHealthReport = []
ShowLatestDeadLockSnapshot = []
ShowMetricNamesSupport = []
ShowQuotas = []
ShowSqlExecutionPlan = []
ShowSqlExplain = []
ShowSqlLimitJobInfo = []
ShowSqlLimitSwitchStatus = []
ShowSqlSwitchStatus = []
ShowTransactionSwitchStatus = []
ShowTuning = []
SynchronizeInstances = []
UpdateDbUser = []
UpdateHealthReportSettings = []
UpdateSqlLimitRules = []
full = ["AddFullSqlTask", "CancelShareConnections", "ChangeChargeMode", "ChangeFullDeadLockSwitch", "ChangeSqlLimitSwitchStatus", "ChangeSqlSwitch", "ChangeTransactionSwitchStatus", "CheckCredential", "CreateHealthReportTask", "CreateHistoryTransactionExportTask", "CreateInstanceConnection", "CreateShareConnections", "CreateSnapshots", "CreateSpaceAnalysisTask", "CreateSqlLimitRules", "CreateTuning", "DeleteDbUser", "DeleteHistoryTransactionExportTask", "DeleteProcess", "DeleteSqlLimitRules", "ExportFullSqlDetails", "ExportSlowQueryLogs", "ExportSlowSqlStatistics", "ExportSlowSqlTemplatesDetails", "ExportSlowSqlTrendDetails", "ExportSqlStatements", "ExportTopRiskInstances", "ExportTopSqlTemplatesDetails", "ExportTopSqlTrendDetails", "ListApiVersions", "ListAutoIncrementUsage", "ListCloudDbaInstances", "ListConnections", "ListDbUsers", "ListFullSqlTasks", "ListHealthReportTask", "ListHistoryTransactionExportTask", "ListInnodbLocks", "ListInstanceDistribution", "ListInstanceMultiNodesSingleMetric", "ListInstanceNodesInfo", "ListInstanceTopSlowLog", "ListMetadataLocks", "ListProcesses", "ListRiskItems", "ListRiskTrend", "ListSnapshots", "ListSpaceAnalysis", "ListSqlLimitRules", "ListTopSlowLog", "ListTransactions", "LoginBuiltInAccount", "LogoffBuiltInAccount", "ParseSqlLimitRules", "RegisterDbUser", "SaveCredential", "SetThresholdForMetric", "ShowApiVersion", "ShowDasRecommendSqlLimitRule", "ShowDbUser", "ShowFullDeadLockList", "ShowFullDeadLockSwitch", "ShowHealthReportSettings", "ShowHistoryTransactionExportTaskInfo", "ShowInstanceHealthReport", "ShowLatestDeadLockSnapshot", "ShowMetricNamesSupport", "ShowQuotas", "ShowSqlExecutionPlan", "ShowSqlExplain", "ShowSqlLimitJobInfo", "ShowSqlLimitSwitchStatus", "ShowSqlSwitchStatus", "ShowTransactionSwitchStatus", "ShowTuning", "SynchronizeInstances", "UpdateDbUser", "UpdateHealthReportSettings", "UpdateSqlLimitRules"]

[lib]
name = "huawei_cloud_api_definitions_DAS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DAS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
