[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddEmailTemplate = []
AddFullSqlTask = []
AddInstanceGroup = []
AddInstanceToGroup = []
BatchSendEmail = []
BatchSubscribeReport = []
CancelShareConnections = []
ChangeChargeMode = []
ChangeFullDeadLockSwitch = []
ChangeSqlLimitSwitchStatus = []
ChangeSqlSwitch = []
ChangeTransactionSwitchStatus = []
CheckCredential = []
CheckCredentialForBatchInspection = []
CreateHealthReportTask = []
CreateHistoryTransactionExportTask = []
CreateInstanceConnection = []
CreateShareConnections = []
CreateSnapshots = []
CreateSpaceAnalysisTask = []
CreateSqlLimitRules = []
CreateTuning = []
DeleteDbUser = []
DeleteEmailTemplate = []
DeleteHistoryTransactionExportTask = []
DeleteInstanceGroup = []
DeleteProcess = []
DeleteSqlLimitRules = []
ExportFullSqlDetails = []
ExportSlowQueryLogs = []
ExportSlowSqlStatistics = []
ExportSlowSqlTemplatesDetails = []
ExportSlowSqlTrendDetails = []
ExportSqlStatements = []
ExportTopRiskInstances = []
ExportTopSqlTemplatesDetails = []
ExportTopSqlTrendDetails = []
ListApiVersions = []
ListAutoIncrementUsage = []
ListCloudDbaInstances = []
ListConnections = []
ListDbUsers = []
ListEmailRecord = []
ListEmailTemplate = []
ListFullSqlTasks = []
ListHealthReportTask = []
ListHistoryTransactionExportTask = []
ListInnodbLocks = []
ListInspectionReport = []
ListInstanceDistribution = []
ListInstanceGroup = []
ListInstanceMultiNodesSingleMetric = []
ListInstanceNodesInfo = []
ListInstanceTopSlowLog = []
ListMetadataLocks = []
ListProcesses = []
ListRiskItems = []
ListRiskTrend = []
ListSnapshots = []
ListSpaceAnalysis = []
ListSqlLimitRules = []
ListTopSlowLog = []
ListTransactions = []
LoginBuiltInAccount = []
LogoffBuiltInAccount = []
ParseSqlLimitRules = []
RegisterDbUser = []
SaveCredential = []
SaveCredentialForBatchInspection = []
SetThresholdForMetric = []
ShowApiVersion = []
ShowCredential = []
ShowDasRecommendSqlLimitRule = []
ShowDbUser = []
ShowFullDeadLockList = []
ShowFullDeadLockSwitch = []
ShowHealthReportSettings = []
ShowHistoryTransactionExportTaskInfo = []
ShowInstanceHealthReport = []
ShowLatestDeadLockSnapshot = []
ShowMetricNamesSupport = []
ShowQuotas = []
ShowSqlExecutionPlan = []
ShowSqlExplain = []
ShowSqlLimitJobInfo = []
ShowSqlLimitSwitchStatus = []
ShowSqlSwitchStatus = []
ShowTransactionSwitchStatus = []
ShowTuning = []
SynchronizeInstances = []
UpdateDbUser = []
UpdateEmailTemplate = []
UpdateHealthReportSettings = []
UpdateInstanceGroup = []
UpdateSqlLimitRules = []
full = ["AddEmailTemplate", "AddFullSqlTask", "AddInstanceGroup", "AddInstanceToGroup", "BatchSendEmail", "BatchSubscribeReport", "CancelShareConnections", "ChangeChargeMode", "ChangeFullDeadLockSwitch", "ChangeSqlLimitSwitchStatus", "ChangeSqlSwitch", "ChangeTransactionSwitchStatus", "CheckCredential", "CheckCredentialForBatchInspection", "CreateHealthReportTask", "CreateHistoryTransactionExportTask", "CreateInstanceConnection", "CreateShareConnections", "CreateSnapshots", "CreateSpaceAnalysisTask", "CreateSqlLimitRules", "CreateTuning", "DeleteDbUser", "DeleteEmailTemplate", "DeleteHistoryTransactionExportTask", "DeleteInstanceGroup", "DeleteProcess", "DeleteSqlLimitRules", "ExportFullSqlDetails", "ExportSlowQueryLogs", "ExportSlowSqlStatistics", "ExportSlowSqlTemplatesDetails", "ExportSlowSqlTrendDetails", "ExportSqlStatements", "ExportTopRiskInstances", "ExportTopSqlTemplatesDetails", "ExportTopSqlTrendDetails", "ListApiVersions", "ListAutoIncrementUsage", "ListCloudDbaInstances", "ListConnections", "ListDbUsers", "ListEmailRecord", "ListEmailTemplate", "ListFullSqlTasks", "ListHealthReportTask", "ListHistoryTransactionExportTask", "ListInnodbLocks", "ListInspectionReport", "ListInstanceDistribution", "ListInstanceGroup", "ListInstanceMultiNodesSingleMetric", "ListInstanceNodesInfo", "ListInstanceTopSlowLog", "ListMetadataLocks", "ListProcesses", "ListRiskItems", "ListRiskTrend", "ListSnapshots", "ListSpaceAnalysis", "ListSqlLimitRules", "ListTopSlowLog", "ListTransactions", "LoginBuiltInAccount", "LogoffBuiltInAccount", "ParseSqlLimitRules", "RegisterDbUser", "SaveCredential", "SaveCredentialForBatchInspection", "SetThresholdForMetric", "ShowApiVersion", "ShowCredential", "ShowDasRecommendSqlLimitRule", "ShowDbUser", "ShowFullDeadLockList", "ShowFullDeadLockSwitch", "ShowHealthReportSettings", "ShowHistoryTransactionExportTaskInfo", "ShowInstanceHealthReport", "ShowLatestDeadLockSnapshot", "ShowMetricNamesSupport", "ShowQuotas", "ShowSqlExecutionPlan", "ShowSqlExplain", "ShowSqlLimitJobInfo", "ShowSqlLimitSwitchStatus", "ShowSqlSwitchStatus", "ShowTransactionSwitchStatus", "ShowTuning", "SynchronizeInstances", "UpdateDbUser", "UpdateEmailTemplate", "UpdateHealthReportSettings", "UpdateInstanceGroup", "UpdateSqlLimitRules"]

[lib]
name = "huawei_cloud_api_definitions_DAS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DAS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
