[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddNode = []
AddNodesToNodePool = []
AwakeCluster = []
BatchCreateAddonPrecheck = []
BatchCreateAutopilotClusterTags = []
BatchCreateClusterTags = []
BatchDeleteAutopilotClusterTags = []
BatchDeleteClusterTags = []
BatchSyncNodes = []
ContinueUpgradeClusterTask = []
CreateAccessPolicy = []
CreateAddonInstance = []
CreateAutopilotAddonInstance = []
CreateAutopilotCluster = []
CreateAutopilotClusterMasterSnapshot = []
CreateAutopilotKubernetesClusterCert = []
CreateAutopilotMaintenanceWindow = []
CreateAutopilotPostCheck = []
CreateAutopilotPreCheck = []
CreateAutopilotRelease = []
CreateAutopilotUpgradeWorkFlow = []
CreateCloudPersistentVolumeClaims = []
CreateCluster = []
CreateClusterMasterSnapshot = []
CreateImageCache = []
CreateKubernetesClusterCert = []
CreateNode = []
CreateNodePool = []
CreatePartition = []
CreatePostCheck = []
CreatePreCheck = []
CreateRelease = []
CreateUpgradeWorkFlow = []
DeleteAccessPolicy = []
DeleteAddonInstance = []
DeleteAutopilotAddonInstance = []
DeleteAutopilotChart = []
DeleteAutopilotCluster = []
DeleteAutopilotJob = []
DeleteAutopilotMaintenanceWindow = []
DeleteAutopilotRelease = []
DeleteChart = []
DeleteCloudPersistentVolumeClaims = []
DeleteCluster = []
DeleteImageCache = []
DeleteNode = []
DeleteNodePool = []
DeleteRelease = []
DownloadAutopilotChart = []
DownloadChart = []
GetAccessPolicy = []
GetAutopilotOneJob = []
GetAvaliableZone = []
GetClusterFlavorSpecs = []
GetClusterLongAkskConfig = []
GetClusterQuota = []
GetCustomizeTags = []
GetLabels = []
GetLongAkskConfig = []
GetResourceTags = []
HibernateCluster = []
ListAccessPolicy = []
ListAddonInstances = []
ListAddonPrecheckTasks = []
ListAddonTemplates = []
ListAutopilotAddonInstances = []
ListAutopilotAddonTemplates = []
ListAutopilotCharts = []
ListAutopilotClusterMasterSnapshotTasks = []
ListAutopilotClusterUpgradeFeatureGates = []
ListAutopilotClusterUpgradePaths = []
ListAutopilotClusters = []
ListAutopilotJobs = []
ListAutopilotPreCheckTasks = []
ListAutopilotReleases = []
ListAutopilotUpgradeClusterTasks = []
ListAutopilotUpgradePlans = []
ListAutopilotUpgradeWorkFlows = []
ListCharts = []
ListClusterMasterSnapshotTasks = []
ListClusterUpgradeFeatureGates = []
ListClusterUpgradePaths = []
ListClusters = []
ListHyperNodes = []
ListImageCaches = []
ListNodePools = []
ListNodes = []
ListPackageProducts = []
ListPartitions = []
ListPreCheckTasks = []
ListReleases = []
ListUpgradeClusterTasks = []
ListUpgradeWorkFlows = []
LockNodepoolNodeScaleDown = []
MigrateNode = []
MigrateToNodePool = []
PauseUpgradeClusterTask = []
RemoveNode = []
ResetNode = []
ResizeCluster = []
full = ["AddNode", "AddNodesToNodePool", "AwakeCluster", "BatchCreateAddonPrecheck", "BatchCreateAutopilotClusterTags", "BatchCreateClusterTags", "BatchDeleteAutopilotClusterTags", "BatchDeleteClusterTags", "BatchSyncNodes", "ContinueUpgradeClusterTask", "CreateAccessPolicy", "CreateAddonInstance", "CreateAutopilotAddonInstance", "CreateAutopilotCluster", "CreateAutopilotClusterMasterSnapshot", "CreateAutopilotKubernetesClusterCert", "CreateAutopilotMaintenanceWindow", "CreateAutopilotPostCheck", "CreateAutopilotPreCheck", "CreateAutopilotRelease", "CreateAutopilotUpgradeWorkFlow", "CreateCloudPersistentVolumeClaims", "CreateCluster", "CreateClusterMasterSnapshot", "CreateImageCache", "CreateKubernetesClusterCert", "CreateNode", "CreateNodePool", "CreatePartition", "CreatePostCheck", "CreatePreCheck", "CreateRelease", "CreateUpgradeWorkFlow", "DeleteAccessPolicy", "DeleteAddonInstance", "DeleteAutopilotAddonInstance", "DeleteAutopilotChart", "DeleteAutopilotCluster", "DeleteAutopilotJob", "DeleteAutopilotMaintenanceWindow", "DeleteAutopilotRelease", "DeleteChart", "DeleteCloudPersistentVolumeClaims", "DeleteCluster", "DeleteImageCache", "DeleteNode", "DeleteNodePool", "DeleteRelease", "DownloadAutopilotChart", "DownloadChart", "GetAccessPolicy", "GetAutopilotOneJob", "GetAvaliableZone", "GetClusterFlavorSpecs", "GetClusterLongAkskConfig", "GetClusterQuota", "GetCustomizeTags", "GetLabels", "GetLongAkskConfig", "GetResourceTags", "HibernateCluster", "ListAccessPolicy", "ListAddonInstances", "ListAddonPrecheckTasks", "ListAddonTemplates", "ListAutopilotAddonInstances", "ListAutopilotAddonTemplates", "ListAutopilotCharts", "ListAutopilotClusterMasterSnapshotTasks", "ListAutopilotClusters", "ListAutopilotClusterUpgradeFeatureGates", "ListAutopilotClusterUpgradePaths", "ListAutopilotJobs", "ListAutopilotPreCheckTasks", "ListAutopilotReleases", "ListAutopilotUpgradeClusterTasks", "ListAutopilotUpgradePlans", "ListAutopilotUpgradeWorkFlows", "ListCharts", "ListClusterMasterSnapshotTasks", "ListClusters", "ListClusterUpgradeFeatureGates", "ListClusterUpgradePaths", "ListHyperNodes", "ListImageCaches", "ListNodePools", "ListNodes", "ListPackageProducts", "ListPartitions", "ListPreCheckTasks", "ListReleases", "ListUpgradeClusterTasks", "ListUpgradeWorkFlows", "LockNodepoolNodeScaleDown", "MigrateNode", "MigrateToNodePool", "PauseUpgradeClusterTask", "RemoveNode", "ResetNode", "ResizeCluster"]

[lib]
name = "huawei_cloud_api_definitions_CCE"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CCE"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
