[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchAddAvailableZones = []
BatchCreateListenerTags = []
BatchCreateLoadBalancers = []
BatchCreateLoadbalancerTags = []
BatchCreateMembers = []
BatchDeleteCertificates = []
BatchDeleteIpList = []
BatchDeleteListenerTags = []
BatchDeleteListeners = []
BatchDeleteLoadbalancerTags = []
BatchDeleteLoadbalancers = []
BatchDeleteMembers = []
BatchDeletePools = []
BatchDisableDomainIPs = []
BatchEnableDomainIPs = []
BatchRemoveAvailableZones = []
BatchUpdateMembers = []
BatchUpdatePoliciesPriority = []
ChangeListenerTags = []
ChangeLoadbalancerChargeMode = []
ChangeLoadbalancerTags = []
CloneListener = []
CloneLoadbalancer = []
CountPreoccupyIpNum = []
CreateCertificate = []
CreateCertificatePrivateKeyEcho = []
CreateHealthMonitor = []
CreateIpGroup = []
CreateL7policy = []
CreateL7rule = []
CreateListener = []
CreateListenerTags = []
CreateLoadbalancer = []
CreateLoadbalancerTags = []
CreateLogtank = []
CreateMasterSlavePool = []
CreateMember = []
CreateMemberHealthCheckJob = []
CreatePool = []
CreateSecurityPolicy = []
CreateWhitelist = []
DeleteCertificate = []
DeleteHealthMonitor = []
DeleteIpGroup = []
DeleteL7Policy = []
DeleteL7Rule = []
DeleteListener = []
DeleteListenerForce = []
DeleteListenerTags = []
DeleteLoadBalancer = []
DeleteLoadBalancerCascade = []
DeleteLoadBalancerForce = []
DeleteLoadbalancerTags = []
DeleteLogtank = []
DeleteMasterSlavePool = []
DeleteMember = []
DeletePool = []
DeletePoolCascade = []
DeleteRecycleLoadBalancer = []
DeleteSecurityPolicy = []
DeleteWhitelist = []
ListAllL7Rules = []
ListAllMembers = []
ListApiVersions = []
ListAvailabilityZones = []
ListCertificates = []
ListDomainIPs = []
ListFeatureConfigs = []
ListFlavors = []
ListHealthmonitors = []
ListIpGroups = []
ListJobs = []
ListL7Policies = []
ListL7Rules = []
ListListenerTags = []
ListListeners = []
ListListenersByTags = []
ListLoadBalancers = []
ListLoadbalancerFeature = []
ListLoadbalancerTags = []
ListLoadbalancersByTags = []
ListLogtanks = []
ListMasterSlavePools = []
ListMembers = []
ListPools = []
ListQuotaDetails = []
ListRecycleBinLoadBalancers = []
ListSecurityPolicies = []
ListSystemSecurityPolicies = []
ListWhitelists = []
RestoreLoadbalancer = []
ShowCertificate = []
ShowCertificatePrivateKeyEcho = []
ShowFlavor = []
ShowHealthMonitor = []
ShowHealthmonitors = []
ShowIpGroup = []
ShowIpGroupRelatedListeners = []
ShowJob = []
ShowL7policy = []
full = ["BatchAddAvailableZones", "BatchCreateListenerTags", "BatchCreateLoadBalancers", "BatchCreateLoadbalancerTags", "BatchCreateMembers", "BatchDeleteCertificates", "BatchDeleteIpList", "BatchDeleteListeners", "BatchDeleteListenerTags", "BatchDeleteLoadbalancers", "BatchDeleteLoadbalancerTags", "BatchDeleteMembers", "BatchDeletePools", "BatchDisableDomainIPs", "BatchEnableDomainIPs", "BatchRemoveAvailableZones", "BatchUpdateMembers", "BatchUpdatePoliciesPriority", "ChangeListenerTags", "ChangeLoadbalancerChargeMode", "ChangeLoadbalancerTags", "CloneListener", "CloneLoadbalancer", "CountPreoccupyIpNum", "CreateCertificate", "CreateCertificatePrivateKeyEcho", "CreateHealthMonitor", "CreateIpGroup", "CreateL7policy", "CreateL7rule", "CreateListener", "CreateListenerTags", "CreateLoadbalancer", "CreateLoadbalancerTags", "CreateLogtank", "CreateMasterSlavePool", "CreateMember", "CreateMemberHealthCheckJob", "CreatePool", "CreateSecurityPolicy", "CreateWhitelist", "DeleteCertificate", "DeleteHealthMonitor", "DeleteIpGroup", "DeleteL7Policy", "DeleteL7Rule", "DeleteListener", "DeleteListenerForce", "DeleteListenerTags", "DeleteLoadBalancer", "DeleteLoadBalancerCascade", "DeleteLoadBalancerForce", "DeleteLoadbalancerTags", "DeleteLogtank", "DeleteMasterSlavePool", "DeleteMember", "DeletePool", "DeletePoolCascade", "DeleteRecycleLoadBalancer", "DeleteSecurityPolicy", "DeleteWhitelist", "ListAllL7Rules", "ListAllMembers", "ListApiVersions", "ListAvailabilityZones", "ListCertificates", "ListDomainIPs", "ListFeatureConfigs", "ListFlavors", "ListHealthmonitors", "ListIpGroups", "ListJobs", "ListL7Policies", "ListL7Rules", "ListListeners", "ListListenersByTags", "ListListenerTags", "ListLoadbalancerFeature", "ListLoadBalancers", "ListLoadbalancersByTags", "ListLoadbalancerTags", "ListLogtanks", "ListMasterSlavePools", "ListMembers", "ListPools", "ListQuotaDetails", "ListRecycleBinLoadBalancers", "ListSecurityPolicies", "ListSystemSecurityPolicies", "ListWhitelists", "RestoreLoadbalancer", "ShowCertificate", "ShowCertificatePrivateKeyEcho", "ShowFlavor", "ShowHealthMonitor", "ShowHealthmonitors", "ShowIpGroup", "ShowIpGroupRelatedListeners", "ShowJob", "ShowL7policy"]

[lib]
name = "huawei_cloud_api_definitions_ELB"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-ELB"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
