[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddAppGroupAuthorization = []
AttachImageServerApp = []
AuthorizeObs = []
BatchChangeServerImage = []
BatchChangeServerMaintainMode = []
BatchCreateServerGroupTags = []
BatchDeleteAppGroup = []
BatchDeleteAppGroupAuthorization = []
BatchDeleteAppSubJobs = []
BatchDeleteCloudStorage = []
BatchDeleteImageServer = []
BatchDeleteImageSubJobs = []
BatchDeletePersistentStorage = []
BatchDeleteScheduleTask = []
BatchDeleteServer = []
BatchDeleteServerGroupTags = []
BatchDeleteWarehouseApp = []
BatchDisableApp = []
BatchEnableApp = []
BatchMigrateHostsServer = []
BatchRebootServer = []
BatchReinstallServer = []
BatchRejoinDomain = []
BatchStartServer = []
BatchStopServer = []
BatchUpdateTsvi = []
BatchUpgradeHdaVersion = []
BindAppWarehouseBucket = []
ChangeCluster = []
ChangeServerImage = []
CheckAppGroup = []
CheckPublishApp = []
CheckQuota = []
CountImageSubJobs = []
CountSubJobs = []
CreateAppGroup = []
CreateAppServers = []
CreateBucketOrAcl = []
CreateCloudStorage = []
CreateHotspotSessionConfig = []
CreateImageServer = []
CreateOrUpdateScalingPolicy = []
CreateOrUpdateStoragePolicyStatement = []
CreateOrder = []
CreatePersistentStorage = []
CreatePolicyGroup = []
CreatePolicyTemplate = []
CreateScheduleTask = []
CreateServerGroup = []
CreateServerGroupTags = []
CreateShareFolder = []
CreateUserFolderAssignment = []
CreateWarehouseApp = []
DeleteAppGroup = []
DeleteAppIcon = []
DeleteCloudStorage = []
DeleteCloudStorageAttachment = []
DeletePersistentStorage = []
DeletePolicyGroup = []
DeletePolicyTemplate = []
DeleteScalingPolicy = []
DeleteScheduleTask = []
DeleteServer = []
DeleteServerGroupTags = []
DeleteServerGroups = []
DeleteStorageClaim = []
DeleteUserStorageAttachment = []
DeleteWarehouseApp = []
DisassociateAppGroup = []
ExportAppConnection = []
ExportSessions = []
ExportUserConnection = []
InitializeTenant = []
ListAccessAgentLatestVersion = []
ListAppConnection = []
ListAppGroup = []
ListAppGroupAuthorization = []
ListAuthorizationMailRecord = []
ListAvailabilityZone = []
ListAz = []
ListCloudStorage = []
ListCloudStorageAssignment = []
ListCorpConfigInfo = []
ListFoldersAndFiles = []
ListFutureExecutions = []
ListHotspotSessionConfig = []
ListImageJobs = []
ListImageServers = []
ListImageSubJobs = []
ListLatestAttachedServerApp = []
ListNonMigrationUsers = []
ListPersistentStorage = []
ListPolicyGroup = []
ListPolicyGroupDetailInfo = []
ListPolicyOfPolicyGroup = []
ListPolicyTemplate = []
ListProduct = []
ListProjectConfigs = []
ListPublishedApp = []
ListScheduleTasks = []
full = ["AddAppGroupAuthorization", "AttachImageServerApp", "AuthorizeObs", "BatchChangeServerImage", "BatchChangeServerMaintainMode", "BatchCreateServerGroupTags", "BatchDeleteAppGroup", "BatchDeleteAppGroupAuthorization", "BatchDeleteAppSubJobs", "BatchDeleteCloudStorage", "BatchDeleteImageServer", "BatchDeleteImageSubJobs", "BatchDeletePersistentStorage", "BatchDeleteScheduleTask", "BatchDeleteServer", "BatchDeleteServerGroupTags", "BatchDeleteWarehouseApp", "BatchDisableApp", "BatchEnableApp", "BatchMigrateHostsServer", "BatchRebootServer", "BatchReinstallServer", "BatchRejoinDomain", "BatchStartServer", "BatchStopServer", "BatchUpdateTsvi", "BatchUpgradeHdaVersion", "BindAppWarehouseBucket", "ChangeCluster", "ChangeServerImage", "CheckAppGroup", "CheckPublishApp", "CheckQuota", "CountImageSubJobs", "CountSubJobs", "CreateAppGroup", "CreateAppServers", "CreateBucketOrAcl", "CreateCloudStorage", "CreateHotspotSessionConfig", "CreateImageServer", "CreateOrder", "CreateOrUpdateScalingPolicy", "CreateOrUpdateStoragePolicyStatement", "CreatePersistentStorage", "CreatePolicyGroup", "CreatePolicyTemplate", "CreateScheduleTask", "CreateServerGroup", "CreateServerGroupTags", "CreateShareFolder", "CreateUserFolderAssignment", "CreateWarehouseApp", "DeleteAppGroup", "DeleteAppIcon", "DeleteCloudStorage", "DeleteCloudStorageAttachment", "DeletePersistentStorage", "DeletePolicyGroup", "DeletePolicyTemplate", "DeleteScalingPolicy", "DeleteScheduleTask", "DeleteServer", "DeleteServerGroups", "DeleteServerGroupTags", "DeleteStorageClaim", "DeleteUserStorageAttachment", "DeleteWarehouseApp", "DisassociateAppGroup", "ExportAppConnection", "ExportSessions", "ExportUserConnection", "InitializeTenant", "ListAccessAgentLatestVersion", "ListAppConnection", "ListAppGroup", "ListAppGroupAuthorization", "ListAuthorizationMailRecord", "ListAvailabilityZone", "ListAz", "ListCloudStorage", "ListCloudStorageAssignment", "ListCorpConfigInfo", "ListFoldersAndFiles", "ListFutureExecutions", "ListHotspotSessionConfig", "ListImageJobs", "ListImageServers", "ListImageSubJobs", "ListLatestAttachedServerApp", "ListNonMigrationUsers", "ListPersistentStorage", "ListPolicyGroup", "ListPolicyGroupDetailInfo", "ListPolicyOfPolicyGroup", "ListPolicyTemplate", "ListProduct", "ListProjectConfigs", "ListPublishedApp", "ListScheduleTasks"]

[lib]
name = "huawei_cloud_api_definitions_WorkspaceApp"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-WorkspaceApp"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
