[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchCreateOrDeleteRocketmqTag = []
BatchDeleteDiagnosisReport = []
BatchDeleteInstances = []
BatchDeleteRocketMqMigrationTask = []
BatchUpdateConsumerGroup = []
CreateConsumerGroupOrBatchDeleteConsumerGroup = []
CreateDiagnosisTask = []
CreateInstanceByEngine = []
CreateRocketMqMigrationTask = []
CreateTopicOrBatchDeleteTopic = []
CreateUser = []
DeleteBackgroundTask = []
DeleteConsumerGroup = []
DeleteInstance = []
DeleteTopic = []
DeleteUser = []
ExportDlqMessage = []
ListAvailableZones = []
ListBackgroundTasks = []
ListBrokers = []
ListConsumeGroupAccessPolicy = []
ListConsumerGroupOfTopic = []
ListDiagnosisReports = []
ListEngineProducts = []
ListInstanceConsumerGroups = []
ListInstances = []
ListMessageTrace = []
ListMessages = []
ListRocketInstanceTopics = []
ListRocketMqMigrationTask = []
ListTopicAccessPolicy = []
ListUser = []
ModifyInstanceSslConfig = []
ResetConsumeOffset = []
ResizeInstance = []
RestartInstance = []
SendDlqMessage = []
SendMessage = []
ShowBackgroundTask = []
ShowConsumerConnections = []
ShowConsumerListOrDetails = []
ShowDiagnosisReport = []
ShowDiagnosisStack = []
ShowEngineInstanceExtendProductInfo = []
ShowGroup = []
ShowInstance = []
ShowInstanceNodes = []
ShowOneTopic = []
ShowRocketMQProductCores = []
ShowRocketMqConfigs = []
ShowRocketmqProjectTags = []
ShowRocketmqTags = []
ShowTopicStatus = []
ShowUser = []
UpdateConsumerGroup = []
UpdateInstance = []
UpdateRocketMqConfigs = []
UpdateTopic = []
UpdateUser = []
ValidateConsumedMessage = []
full = ["BatchCreateOrDeleteRocketmqTag", "BatchDeleteDiagnosisReport", "BatchDeleteInstances", "BatchDeleteRocketMqMigrationTask", "BatchUpdateConsumerGroup", "CreateConsumerGroupOrBatchDeleteConsumerGroup", "CreateDiagnosisTask", "CreateInstanceByEngine", "CreateRocketMqMigrationTask", "CreateTopicOrBatchDeleteTopic", "CreateUser", "DeleteBackgroundTask", "DeleteConsumerGroup", "DeleteInstance", "DeleteTopic", "DeleteUser", "ExportDlqMessage", "ListAvailableZones", "ListBackgroundTasks", "ListBrokers", "ListConsumeGroupAccessPolicy", "ListConsumerGroupOfTopic", "ListDiagnosisReports", "ListEngineProducts", "ListInstanceConsumerGroups", "ListInstances", "ListMessages", "ListMessageTrace", "ListRocketInstanceTopics", "ListRocketMqMigrationTask", "ListTopicAccessPolicy", "ListUser", "ModifyInstanceSslConfig", "ResetConsumeOffset", "ResizeInstance", "RestartInstance", "SendDlqMessage", "SendMessage", "ShowBackgroundTask", "ShowConsumerConnections", "ShowConsumerListOrDetails", "ShowDiagnosisReport", "ShowDiagnosisStack", "ShowEngineInstanceExtendProductInfo", "ShowGroup", "ShowInstance", "ShowInstanceNodes", "ShowOneTopic", "ShowRocketMqConfigs", "ShowRocketMQProductCores", "ShowRocketmqProjectTags", "ShowRocketmqTags", "ShowTopicStatus", "ShowUser", "UpdateConsumerGroup", "UpdateInstance", "UpdateRocketMqConfigs", "UpdateTopic", "UpdateUser", "ValidateConsumedMessage"]

[lib]
name = "huawei_cloud_api_definitions_RocketMQ"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-RocketMQ"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
