[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CreateAccessConfig = []
CreateAgencyAccess = []
CreateAomMappingRules = []
CreateDashBoard = []
CreateDashboardGroup = []
CreateHostGroup = []
CreateKeywordsAlarmRule = []
CreateLogGroup = []
CreateLogStream = []
CreateNotificationTemplate = []
CreateSearchCriterias = []
CreateSqlAlarmRule = []
CreateStructConfig = []
CreateStructTemplate = []
CreateTags = []
CreateTransfer = []
Createfavorite = []
DeleteAccessConfig = []
DeleteActiveAlarms = []
DeleteAomMappingRules = []
DeleteHostGroup = []
DeleteKeywordsAlarmRule = []
DeleteLogGroup = []
DeleteLogStream = []
DeleteNotificationTemplate = []
DeleteSearchCriterias = []
DeleteSqlAlarmRule = []
DeleteStructTemplate = []
DeleteTransfer = []
Deletefavorite = []
DisableLogCollection = []
EnableLogCollection = []
ListAccessConfig = []
ListActiveOrHistoryAlarms = []
ListBreifStructTemplate = []
ListCharts = []
ListCriterias = []
ListHistorySql = []
ListHost = []
ListHostGroup = []
ListKeywordsAlarmRules = []
ListLogContext = []
ListLogGroups = []
ListLogHistogram = []
ListLogStream = []
ListLogStreamIndex = []
ListLogStreams = []
ListLogs = []
ListNotificationTemplate = []
ListNotificationTemplates = []
ListNotificationTopics = []
ListQueryAllSearchCriterias = []
ListQueryStructuredLogs = []
ListSqlAlarmRules = []
ListStructTemplate = []
ListStructuredLogsWithTimeRange = []
ListTimeLineTrafficStatistics = []
ListTopnTrafficStatistics = []
ListTransfers = []
RegisterDmsKafkaInstance = []
ShowAdminConfig = []
ShowAomMappingRule = []
ShowAomMappingRules = []
ShowLogConvergeConfig = []
ShowMemberGroupAndStream = []
ShowNotificationTemplate = []
ShowStructTemplate = []
UpdateAccessConfig = []
UpdateAlarmRuleStatus = []
UpdateAomMappingRules = []
UpdateHostGroup = []
UpdateKeywordsAlarmRule = []
UpdateLogConvergeConfig = []
UpdateLogGroup = []
UpdateLogStream = []
UpdateNotificationTemplate = []
UpdateSqlAlarmRule = []
UpdateStructConfig = []
UpdateStructTemplate = []
UpdateSwitch = []
UpdateTransfer = []
full = ["CreateAccessConfig", "CreateAgencyAccess", "CreateAomMappingRules", "CreateDashBoard", "CreateDashboardGroup", "Createfavorite", "CreateHostGroup", "CreateKeywordsAlarmRule", "CreateLogGroup", "CreateLogStream", "CreateNotificationTemplate", "CreateSearchCriterias", "CreateSqlAlarmRule", "CreateStructConfig", "CreateStructTemplate", "CreateTags", "CreateTransfer", "DeleteAccessConfig", "DeleteActiveAlarms", "DeleteAomMappingRules", "Deletefavorite", "DeleteHostGroup", "DeleteKeywordsAlarmRule", "DeleteLogGroup", "DeleteLogStream", "DeleteNotificationTemplate", "DeleteSearchCriterias", "DeleteSqlAlarmRule", "DeleteStructTemplate", "DeleteTransfer", "DisableLogCollection", "EnableLogCollection", "ListAccessConfig", "ListActiveOrHistoryAlarms", "ListBreifStructTemplate", "ListCharts", "ListCriterias", "ListHistorySql", "ListHost", "ListHostGroup", "ListKeywordsAlarmRules", "ListLogContext", "ListLogGroups", "ListLogHistogram", "ListLogs", "ListLogStream", "ListLogStreamIndex", "ListLogStreams", "ListNotificationTemplate", "ListNotificationTemplates", "ListNotificationTopics", "ListQueryAllSearchCriterias", "ListQueryStructuredLogs", "ListSqlAlarmRules", "ListStructTemplate", "ListStructuredLogsWithTimeRange", "ListTimeLineTrafficStatistics", "ListTopnTrafficStatistics", "ListTransfers", "RegisterDmsKafkaInstance", "ShowAdminConfig", "ShowAomMappingRule", "ShowAomMappingRules", "ShowLogConvergeConfig", "ShowMemberGroupAndStream", "ShowNotificationTemplate", "ShowStructTemplate", "UpdateAccessConfig", "UpdateAlarmRuleStatus", "UpdateAomMappingRules", "UpdateHostGroup", "UpdateKeywordsAlarmRule", "UpdateLogConvergeConfig", "UpdateLogGroup", "UpdateLogStream", "UpdateNotificationTemplate", "UpdateSqlAlarmRule", "UpdateStructConfig", "UpdateStructTemplate", "UpdateSwitch", "UpdateTransfer"]

[lib]
name = "huawei_cloud_api_definitions_LTS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-LTS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
