[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddActiveDirectoryDomain = []
BatchAddSharedTags = []
ChangeSecurityGroup = []
ChangeShareChargeModeV2 = []
ChangeShareName = []
CreateBackendTarget = []
CreateFsDir = []
CreateFsDirQuota = []
CreateFsTask = []
CreateHpcCacheTask = []
CreateLdapConfig = []
CreatePermRule = []
CreateShare = []
CreateSharedTag = []
DeleteActiveDirectoryDomain = []
DeleteBackendTarget = []
DeleteFsDir = []
DeleteFsDirQuota = []
DeleteFsTask = []
DeleteHpcCacheTask = []
DeleteLdapConfig = []
DeletePermRule = []
DeleteShare = []
DeleteSharedTag = []
ExpandShare = []
ListBackendTargets = []
ListFsTasks = []
ListHpcCacheTasks = []
ListPermRules = []
ListShareTypes = []
ListSharedTags = []
ListShares = []
ListSharesByTag = []
SetHpcCacheBackend = []
ShowActiveDirectoryDomain = []
ShowBackendTargetInfo = []
ShowClientIpInfo = []
ShowFsDir = []
ShowFsDirQuota = []
ShowFsDirUsage = []
ShowFsTask = []
ShowHpcCacheTask = []
ShowJobDetail = []
ShowLdapConfig = []
ShowPermRule = []
ShowQuota = []
ShowShare = []
ShowSharedTags = []
UpdateActiveDirectoryDomain = []
UpdateFsDirQuota = []
UpdateHpcShare = []
UpdateLdapConfig = []
UpdateObsTargetAttributes = []
UpdateObsTargetPolicy = []
UpdatePermRule = []
full = ["AddActiveDirectoryDomain", "BatchAddSharedTags", "ChangeSecurityGroup", "ChangeShareChargeModeV2", "ChangeShareName", "CreateBackendTarget", "CreateFsDir", "CreateFsDirQuota", "CreateFsTask", "CreateHpcCacheTask", "CreateLdapConfig", "CreatePermRule", "CreateShare", "CreateSharedTag", "DeleteActiveDirectoryDomain", "DeleteBackendTarget", "DeleteFsDir", "DeleteFsDirQuota", "DeleteFsTask", "DeleteHpcCacheTask", "DeleteLdapConfig", "DeletePermRule", "DeleteShare", "DeleteSharedTag", "ExpandShare", "ListBackendTargets", "ListFsTasks", "ListHpcCacheTasks", "ListPermRules", "ListSharedTags", "ListShares", "ListSharesByTag", "ListShareTypes", "SetHpcCacheBackend", "ShowActiveDirectoryDomain", "ShowBackendTargetInfo", "ShowClientIpInfo", "ShowFsDir", "ShowFsDirQuota", "ShowFsDirUsage", "ShowFsTask", "ShowHpcCacheTask", "ShowJobDetail", "ShowLdapConfig", "ShowPermRule", "ShowQuota", "ShowShare", "ShowSharedTags", "UpdateActiveDirectoryDomain", "UpdateFsDirQuota", "UpdateHpcShare", "UpdateLdapConfig", "UpdateObsTargetAttributes", "UpdateObsTargetPolicy", "UpdatePermRule"]

[lib]
name = "huawei_cloud_api_definitions_SFSTurbo"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-SFSTurbo"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
