[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddDesktopPoolVolumes = []
AddDesktopSubResources = []
AddDesktopVolumes = []
AddMetricNotifyRule = []
AddOu = []
AddRestrictedRule = []
AddSite = []
AddVolumes = []
ApplyDesktopsInternet = []
ApplyInternet = []
ApplySubnetBandwidth = []
ApplyWorkspace = []
AssociateDesktopsEip = []
AttachInstances = []
BatchAddDesktopsTags = []
BatchAssociateInstances = []
BatchAttachInstances = []
BatchChangeDesktopNetwork = []
BatchChangeTags = []
BatchCreateDesktopSnapshot = []
BatchCreateUsers = []
BatchDeleteAccessPolicies = []
BatchDeleteAppRules = []
BatchDeleteApps = []
BatchDeleteDesktopNamePolicy = []
BatchDeleteDesktopSnapshot = []
BatchDeleteDesktops = []
BatchDeleteDesktopsTags = []
BatchDeleteJobs = []
BatchDeleteOtpDevices = []
BatchDeleteScheduledTasks = []
BatchDeleteScreenRecords = []
BatchDeleteSubJobs = []
BatchDeleteUser = []
BatchDeleteUserGroups = []
BatchDetachInstances = []
BatchDisableApps = []
BatchDisassociateDesktopsEip = []
BatchEnableApps = []
BatchInstallAgent = []
BatchInstallApps = []
BatchLogoffDesktops = []
BatchModifyQosVolumes = []
BatchRebuildDesktopsSystemDisk = []
BatchRestoreDesktopSnapshot = []
BatchRunDesktops = []
BatchUpdateAppAuthorizations = []
BatchUpdateTargetOfPolicyGroup = []
CancelRemoteAssistance = []
CancelWorkspace = []
ChangeDesktopNetwork = []
ChangeDesktopToImage = []
ChangeUserPrivilegeGroup = []
ChangeUserStatus = []
CheckCidr = []
CheckDesktopImages = []
CheckEdgeSiteResources = []
CheckEnterpriseId = []
CheckSysprepInfo = []
CreateAccessPolicy = []
CreateAgencies = []
CreateAndAuthorizeBucket = []
CreateAppRule = []
CreateBucketCredential = []
CreateCert = []
CreateChangeOrder = []
CreateDesktop = []
CreateDesktopBatchOrder = []
CreateDesktopNamePolicy = []
CreateDesktopOrder = []
CreateDesktopPool = []
CreateDesktopPoolAuthorizedObjects = []
CreateDesktopPoolChangeOrder = []
CreateDesktopUser = []
CreateOrder = []
CreatePolicyGroup = []
CreatePolicyTemplate = []
CreateRemoteAssistance = []
CreateResourcePackagesOrder = []
CreateScheduledTasks = []
CreateScript = []
CreateSubnetBandwidthChangeOrder = []
CreateTag = []
CreateTerminalsBindingDesktops = []
CreateUserGroup = []
DeleteApp = []
DeleteAppRule = []
DeleteCert = []
DeleteDesktop = []
DeleteDesktopPool = []
DeleteDesktopPoolVolumes = []
DeleteDesktopSubResources = []
DeleteDesktopVolumes = []
DeleteExportTasks = []
DeleteMetricNotifyRule = []
DeleteOu = []
DeletePolicyGroup = []
DeleteRestrictedRule = []
DeleteScheduledTasks = []
DeleteScript = []
full = ["AddDesktopPoolVolumes", "AddDesktopSubResources", "AddDesktopVolumes", "AddMetricNotifyRule", "AddOu", "AddRestrictedRule", "AddSite", "AddVolumes", "ApplyDesktopsInternet", "ApplyInternet", "ApplySubnetBandwidth", "ApplyWorkspace", "AssociateDesktopsEip", "AttachInstances", "BatchAddDesktopsTags", "BatchAssociateInstances", "BatchAttachInstances", "BatchChangeDesktopNetwork", "BatchChangeTags", "BatchCreateDesktopSnapshot", "BatchCreateUsers", "BatchDeleteAccessPolicies", "BatchDeleteAppRules", "BatchDeleteApps", "BatchDeleteDesktopNamePolicy", "BatchDeleteDesktops", "BatchDeleteDesktopSnapshot", "BatchDeleteDesktopsTags", "BatchDeleteJobs", "BatchDeleteOtpDevices", "BatchDeleteScheduledTasks", "BatchDeleteScreenRecords", "BatchDeleteSubJobs", "BatchDeleteUser", "BatchDeleteUserGroups", "BatchDetachInstances", "BatchDisableApps", "BatchDisassociateDesktopsEip", "BatchEnableApps", "BatchInstallAgent", "BatchInstallApps", "BatchLogoffDesktops", "BatchModifyQosVolumes", "BatchRebuildDesktopsSystemDisk", "BatchRestoreDesktopSnapshot", "BatchRunDesktops", "BatchUpdateAppAuthorizations", "BatchUpdateTargetOfPolicyGroup", "CancelRemoteAssistance", "CancelWorkspace", "ChangeDesktopNetwork", "ChangeDesktopToImage", "ChangeUserPrivilegeGroup", "ChangeUserStatus", "CheckCidr", "CheckDesktopImages", "CheckEdgeSiteResources", "CheckEnterpriseId", "CheckSysprepInfo", "CreateAccessPolicy", "CreateAgencies", "CreateAndAuthorizeBucket", "CreateAppRule", "CreateBucketCredential", "CreateCert", "CreateChangeOrder", "CreateDesktop", "CreateDesktopBatchOrder", "CreateDesktopNamePolicy", "CreateDesktopOrder", "CreateDesktopPool", "CreateDesktopPoolAuthorizedObjects", "CreateDesktopPoolChangeOrder", "CreateDesktopUser", "CreateOrder", "CreatePolicyGroup", "CreatePolicyTemplate", "CreateRemoteAssistance", "CreateResourcePackagesOrder", "CreateScheduledTasks", "CreateScript", "CreateSubnetBandwidthChangeOrder", "CreateTag", "CreateTerminalsBindingDesktops", "CreateUserGroup", "DeleteApp", "DeleteAppRule", "DeleteCert", "DeleteDesktop", "DeleteDesktopPool", "DeleteDesktopPoolVolumes", "DeleteDesktopSubResources", "DeleteDesktopVolumes", "DeleteExportTasks", "DeleteMetricNotifyRule", "DeleteOu", "DeletePolicyGroup", "DeleteRestrictedRule", "DeleteScheduledTasks", "DeleteScript"]

[lib]
name = "huawei_cloud_api_definitions_Workspace"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-Workspace"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
