[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddBlackWhiteIpList = []
AddPolicyBlackAndWhiteIpList = []
AddWafWhiteIpRule = []
AssociateIpToPolicy = []
AssociateIpToPolicyAndPackage = []
BatchCreateInstanceIpRule = []
BatchDeleteInstanceIpRule = []
CreateAadDomain = []
CreateDomain = []
CreatePolicy = []
DeleteAlarmConfig = []
DeleteBlackWhiteIpList = []
DeleteDomain = []
DeletePolicy = []
DeletePolicyBlackAndWhiteIpList = []
DeleteWafWhiteIpRule = []
DisassociateIpFromPolicy = []
DisassociateIpFromPolicyAndPackage = []
ExecuteUnblockIp = []
ListBlockIps = []
ListDDoSAttackEvent = []
ListDDoSConnectionNumber = []
ListDDoSFlow = []
ListDomain = []
ListFrequencyControlRule = []
ListInstance = []
ListInstanceDomains = []
ListInstanceId = []
ListInstanceIpRule = []
ListPackage = []
ListPeak = []
ListPolicy = []
ListProtectedIp = []
ListSourceIps = []
ListUnblockQuotaStatistics = []
ListUnboundProtectedIp = []
ListWafAttackEvent = []
ListWafBandwidth = []
ListWafCustomRule = []
ListWafGeoIpRule = []
ListWafQps = []
ListWafWhiteIpRule = []
ListWhiteBlackIpRule = []
ModifyDomainWebSwitch = []
SetCertForDomain = []
ShowAlarmConfig = []
ShowBlockStatistics = []
ShowDomainCertificate = []
ShowFlowBlock = []
ShowLtsConfig = []
ShowPolicy = []
ShowUnblockRecord = []
ShowWafPolicy = []
ShowWafQps = []
UpdateAlarmConfig = []
UpdateDomain = []
UpdateInstanceIpRule = []
UpdateLtsConfig = []
UpdatePackageIp = []
UpdatePackageName = []
UpdatePolicy = []
UpdateTagForProtectedIp = []
UpgradeInstanceSpec = []
full = ["AddBlackWhiteIpList", "AddPolicyBlackAndWhiteIpList", "AddWafWhiteIpRule", "AssociateIpToPolicy", "AssociateIpToPolicyAndPackage", "BatchCreateInstanceIpRule", "BatchDeleteInstanceIpRule", "CreateAadDomain", "CreateDomain", "CreatePolicy", "DeleteAlarmConfig", "DeleteBlackWhiteIpList", "DeleteDomain", "DeletePolicy", "DeletePolicyBlackAndWhiteIpList", "DeleteWafWhiteIpRule", "DisassociateIpFromPolicy", "DisassociateIpFromPolicyAndPackage", "ExecuteUnblockIp", "ListBlockIps", "ListDDoSAttackEvent", "ListDDoSConnectionNumber", "ListDDoSFlow", "ListDomain", "ListFrequencyControlRule", "ListInstance", "ListInstanceDomains", "ListInstanceId", "ListInstanceIpRule", "ListPackage", "ListPeak", "ListPolicy", "ListProtectedIp", "ListSourceIps", "ListUnblockQuotaStatistics", "ListUnboundProtectedIp", "ListWafAttackEvent", "ListWafBandwidth", "ListWafCustomRule", "ListWafGeoIpRule", "ListWafQps", "ListWafWhiteIpRule", "ListWhiteBlackIpRule", "ModifyDomainWebSwitch", "SetCertForDomain", "ShowAlarmConfig", "ShowBlockStatistics", "ShowDomainCertificate", "ShowFlowBlock", "ShowLtsConfig", "ShowPolicy", "ShowUnblockRecord", "ShowWafPolicy", "ShowWafQps", "UpdateAlarmConfig", "UpdateDomain", "UpdateInstanceIpRule", "UpdateLtsConfig", "UpdatePackageIp", "UpdatePackageName", "UpdatePolicy", "UpdateTagForProtectedIp", "UpgradeInstanceSpec"]

[lib]
name = "huawei_cloud_api_definitions_AAD"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-AAD"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
