[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchShowIpBelongs = []
CheckDomainVerification = []
CreateDomain = []
CreateDomainMapping = []
CreateFlowOutput = []
CreateFlows = []
CreateOttChannelInfo = []
CreatePullTask = []
CreateRecordCallbackConfig = []
CreateRecordIndex = []
CreateRecordRule = []
CreateSnapshotConfig = []
CreateStreamForbidden = []
CreateStreamForbiddenOnce = []
CreateTranscodingsTemplate = []
CreateUrlAuthchain = []
CreateWatermarkRule = []
CreateWatermarkTemplate = []
DeleteDomain = []
DeleteDomainHttpsCert = []
DeleteDomainKeyChain = []
DeleteDomainMapping = []
DeleteFlow = []
DeleteFlowOutput = []
DeleteOttChannelInfo = []
DeletePublishTemplate = []
DeletePullTask = []
DeleteRecordCallbackConfig = []
DeleteRecordRule = []
DeleteRefererChain = []
DeleteSnapshotConfig = []
DeleteStreamForbidden = []
DeleteTranscodingsTemplate = []
DeleteWatermarkRule = []
DeleteWatermarkTemplate = []
ListAreaDetail = []
ListBandwidthDetail = []
ListCarouselTaskDetail = []
ListCesDimsInfo = []
ListCesInstance = []
ListDelayConfig = []
ListDomainBandwidthPeak = []
ListDomainTrafficDetail = []
ListDomainTrafficSummary = []
ListFlows = []
ListGeoBlockingConfig = []
ListHistoryStreams = []
ListHlsConfig = []
ListIpAuthList = []
ListLiveSampleLogs = []
ListLiveStreamsOnline = []
ListOttChannelInfo = []
ListPlayDomainStreamInfo = []
ListPublishTemplate = []
ListPullTasks = []
ListQueryHttpCode = []
ListRecordCallbackConfigs = []
ListRecordData = []
ListRecordRules = []
ListSingleStreamBitrate = []
ListSingleStreamDetail = []
ListSingleStreamFramerate = []
ListSnapshotConfigs = []
ListSnapshotData = []
ListStreamForbidden = []
ListTranscodeConcurrencyNum = []
ListTranscodeData = []
ListTranscodeTaskDetail = []
ListUpStreamDetail = []
ListUsersOfStream = []
ListWatermarkRule = []
ListWatermarkTemplate = []
ModifyFlowOutput = []
ModifyFlowSources = []
ModifyFlowStart = []
ModifyFlowStop = []
ModifyOttChannelInfoEncoderSettings = []
ModifyOttChannelInfoEndPoints = []
ModifyOttChannelInfoGeneral = []
ModifyOttChannelInfoInput = []
ModifyOttChannelInfoRecordSettings = []
ModifyOttChannelInfoStats = []
ModifyPullTask = []
RunRecord = []
SetRefererChain = []
ShowCertificateInfo = []
ShowChannelStatistic = []
ShowDomain = []
ShowDomainHttpsCert = []
ShowDomainKeyChain = []
ShowDomainVerification = []
ShowFlowDetail = []
ShowOutputInfo = []
ShowPullSourcesConfig = []
ShowRecordCallbackConfig = []
ShowRecordRule = []
ShowRefererChain = []
ShowStreamCount = []
ShowStreamPortrait = []
ShowTranscodingsTemplate = []
full = ["BatchShowIpBelongs", "CheckDomainVerification", "CreateDomain", "CreateDomainMapping", "CreateFlowOutput", "CreateFlows", "CreateOttChannelInfo", "CreatePullTask", "CreateRecordCallbackConfig", "CreateRecordIndex", "CreateRecordRule", "CreateSnapshotConfig", "CreateStreamForbidden", "CreateStreamForbiddenOnce", "CreateTranscodingsTemplate", "CreateUrlAuthchain", "CreateWatermarkRule", "CreateWatermarkTemplate", "DeleteDomain", "DeleteDomainHttpsCert", "DeleteDomainKeyChain", "DeleteDomainMapping", "DeleteFlow", "DeleteFlowOutput", "DeleteOttChannelInfo", "DeletePublishTemplate", "DeletePullTask", "DeleteRecordCallbackConfig", "DeleteRecordRule", "DeleteRefererChain", "DeleteSnapshotConfig", "DeleteStreamForbidden", "DeleteTranscodingsTemplate", "DeleteWatermarkRule", "DeleteWatermarkTemplate", "ListAreaDetail", "ListBandwidthDetail", "ListCarouselTaskDetail", "ListCesDimsInfo", "ListCesInstance", "ListDelayConfig", "ListDomainBandwidthPeak", "ListDomainTrafficDetail", "ListDomainTrafficSummary", "ListFlows", "ListGeoBlockingConfig", "ListHistoryStreams", "ListHlsConfig", "ListIpAuthList", "ListLiveSampleLogs", "ListLiveStreamsOnline", "ListOttChannelInfo", "ListPlayDomainStreamInfo", "ListPublishTemplate", "ListPullTasks", "ListQueryHttpCode", "ListRecordCallbackConfigs", "ListRecordData", "ListRecordRules", "ListSingleStreamBitrate", "ListSingleStreamDetail", "ListSingleStreamFramerate", "ListSnapshotConfigs", "ListSnapshotData", "ListStreamForbidden", "ListTranscodeConcurrencyNum", "ListTranscodeData", "ListTranscodeTaskDetail", "ListUpStreamDetail", "ListUsersOfStream", "ListWatermarkRule", "ListWatermarkTemplate", "ModifyFlowOutput", "ModifyFlowSources", "ModifyFlowStart", "ModifyFlowStop", "ModifyOttChannelInfoEncoderSettings", "ModifyOttChannelInfoEndPoints", "ModifyOttChannelInfoGeneral", "ModifyOttChannelInfoInput", "ModifyOttChannelInfoRecordSettings", "ModifyOttChannelInfoStats", "ModifyPullTask", "RunRecord", "SetRefererChain", "ShowCertificateInfo", "ShowChannelStatistic", "ShowDomain", "ShowDomainHttpsCert", "ShowDomainKeyChain", "ShowDomainVerification", "ShowFlowDetail", "ShowOutputInfo", "ShowPullSourcesConfig", "ShowRecordCallbackConfig", "ShowRecordRule", "ShowRefererChain", "ShowStreamCount", "ShowStreamPortrait", "ShowTranscodingsTemplate"]

[lib]
name = "huawei_cloud_api_definitions_Live"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-Live"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
