[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
ApplyArchiveRule = []
CheckNoNewAccess = []
CreateAccessPreview = []
CreateAnalyzer = []
CreateArchiveRule = []
CreateNotificationSetting = []
CreateResourceConfigurations = []
DeleteAnalyzer = []
DeleteArchiveRule = []
DeleteNotificationSetting = []
DeleteResourceConfigurations = []
ListAccessPreviewFindings = []
ListAccessPreviews = []
ListAnalyzers = []
ListArchiveRules = []
ListFindings = []
ListNotificationSettings = []
ListResourceConfigurations = []
ShowAccessPreview = []
ShowAnalyzer = []
ShowArchiveRule = []
ShowFinding = []
ShowNotificationSetting = []
StartResourceScan = []
TagResource = []
UntagResource = []
UpdateAnalyzer = []
UpdateArchiveRule = []
UpdateFindings = []
UpdateNotificationSetting = []
ValidatePolicy = []
full = ["ApplyArchiveRule", "CheckNoNewAccess", "CreateAccessPreview", "CreateAnalyzer", "CreateArchiveRule", "CreateNotificationSetting", "CreateResourceConfigurations", "DeleteAnalyzer", "DeleteArchiveRule", "DeleteNotificationSetting", "DeleteResourceConfigurations", "ListAccessPreviewFindings", "ListAccessPreviews", "ListAnalyzers", "ListArchiveRules", "ListFindings", "ListNotificationSettings", "ListResourceConfigurations", "ShowAccessPreview", "ShowAnalyzer", "ShowArchiveRule", "ShowFinding", "ShowNotificationSetting", "StartResourceScan", "TagResource", "UntagResource", "UpdateAnalyzer", "UpdateArchiveRule", "UpdateFindings", "UpdateNotificationSetting", "ValidatePolicy"]

[lib]
name = "huawei_cloud_api_definitions_IAMAccessAnalyzer"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-IAMAccessAnalyzer"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
