[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CreateAddonInstance = []
CreateClusterConf = []
CreateClusterGroupPolicyInstance = []
CreateClusterKubeconfig = []
CreateClusterPolicyInstance = []
CreateConfigSet = []
CreateFederationCert = []
CreateFederationConnection = []
CreateProxyUnitedWorkload = []
CreateRecordSet = []
CreateRepo = []
CreateRule = []
DeleteAddonInstance = []
DeleteCluster = []
DeleteClusterGroup = []
DeleteConfigSet = []
DeletePolicyInstance = []
DeleteProxyUnitedWorkload = []
DeleteRepo = []
DeleteRule = []
DisableClusterPolicy = []
DisableClustergroupPolicy = []
DisableFederation = []
DisableGitOps = []
DownloadFederationKubeconfig = []
EnableClusterPolicy = []
EnableClustergroupPolicy = []
EnableFederation = []
EnableGitOps = []
JoinGroup = []
LeaveGroup = []
ListAddonInstances = []
ListAddonTemplates = []
ListClusterGroup = []
ListConfigSets = []
ListManagedClusters = []
ListPolicyDefinitions = []
ListPolicyInstances = []
ListPolicyJobs = []
ListRecordSets = []
ListRegisteredClusterVersions = []
ListRepos = []
ListRule = []
ListServerConfigs = []
RegisterCluster = []
RegisterClusterGroup = []
RetryClusterActivation = []
ShowAddonInstance = []
ShowCluster = []
ShowClusterAccessInfo = []
ShowClusterGroup = []
ShowClusterList = []
ShowConfigSet = []
ShowFederationProgress = []
ShowGitOpsStatus = []
ShowGitopsStatistics = []
ShowPolicyDefinition = []
ShowPolicyInstance = []
ShowPolicyJob = []
ShowProxyUnitedWorkload = []
ShowQuota = []
UpdateAddonInstance = []
UpdateCluster = []
UpdateClusterGroup = []
UpdateClusterGroupAssociatedClusters = []
UpdateClusterGroupAssociatedRules = []
UpdateClusterGroupAssociatedZones = []
UpdateClusterRules = []
UpdateConfigSet = []
UpdatePolicyDefination = []
UpdatePolicyInstance = []
UpdateProxyUnitedWorkload = []
UpdateRepo = []
UpdateRule = []
UpgradeFederation = []
full = ["CreateAddonInstance", "CreateClusterConf", "CreateClusterGroupPolicyInstance", "CreateClusterKubeconfig", "CreateClusterPolicyInstance", "CreateConfigSet", "CreateFederationCert", "CreateFederationConnection", "CreateProxyUnitedWorkload", "CreateRecordSet", "CreateRepo", "CreateRule", "DeleteAddonInstance", "DeleteCluster", "DeleteClusterGroup", "DeleteConfigSet", "DeletePolicyInstance", "DeleteProxyUnitedWorkload", "DeleteRepo", "DeleteRule", "DisableClustergroupPolicy", "DisableClusterPolicy", "DisableFederation", "DisableGitOps", "DownloadFederationKubeconfig", "EnableClustergroupPolicy", "EnableClusterPolicy", "EnableFederation", "EnableGitOps", "JoinGroup", "LeaveGroup", "ListAddonInstances", "ListAddonTemplates", "ListClusterGroup", "ListConfigSets", "ListManagedClusters", "ListPolicyDefinitions", "ListPolicyInstances", "ListPolicyJobs", "ListRecordSets", "ListRegisteredClusterVersions", "ListRepos", "ListRule", "ListServerConfigs", "RegisterCluster", "RegisterClusterGroup", "RetryClusterActivation", "ShowAddonInstance", "ShowCluster", "ShowClusterAccessInfo", "ShowClusterGroup", "ShowClusterList", "ShowConfigSet", "ShowFederationProgress", "ShowGitopsStatistics", "ShowGitOpsStatus", "ShowPolicyDefinition", "ShowPolicyInstance", "ShowPolicyJob", "ShowProxyUnitedWorkload", "ShowQuota", "UpdateAddonInstance", "UpdateCluster", "UpdateClusterGroup", "UpdateClusterGroupAssociatedClusters", "UpdateClusterGroupAssociatedRules", "UpdateClusterGroupAssociatedZones", "UpdateClusterRules", "UpdateConfigSet", "UpdatePolicyDefination", "UpdatePolicyInstance", "UpdateProxyUnitedWorkload", "UpdateRepo", "UpdateRule", "UpgradeFederation"]

[lib]
name = "huawei_cloud_api_definitions_UCS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-UCS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
