[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CreateFederationCert = []
CreateFederationConnection = []
CreateRule = []
DeleteCluster = []
DeleteClusterGroup = []
DeleteRule = []
DisableFederation = []
DownloadFederationKubeconfig = []
EnableFederation = []
JoinGroup = []
LeaveGroup = []
ListClusterGroup = []
ListManagedClusters = []
ListRegisteredClusterVersions = []
ListRule = []
RegisterCluster = []
RegisterClusterGroup = []
RetryClusterActivation = []
ShowCluster = []
ShowClusterAccessInfo = []
ShowClusterGroup = []
ShowClusterList = []
ShowFederationProgress = []
UpdateCluster = []
UpdateClusterGroup = []
UpdateClusterGroupAssociatedClusters = []
UpdateClusterGroupAssociatedRules = []
UpdateClusterGroupAssociatedZones = []
UpdateClusterRules = []
UpdateRule = []
full = ["CreateFederationCert", "CreateFederationConnection", "CreateRule", "DeleteCluster", "DeleteClusterGroup", "DeleteRule", "DisableFederation", "DownloadFederationKubeconfig", "EnableFederation", "JoinGroup", "LeaveGroup", "ListClusterGroup", "ListManagedClusters", "ListRegisteredClusterVersions", "ListRule", "RegisterCluster", "RegisterClusterGroup", "RetryClusterActivation", "ShowCluster", "ShowClusterAccessInfo", "ShowClusterGroup", "ShowClusterList", "ShowFederationProgress", "UpdateCluster", "UpdateClusterGroup", "UpdateClusterGroupAssociatedClusters", "UpdateClusterGroupAssociatedRules", "UpdateClusterGroupAssociatedZones", "UpdateClusterRules", "UpdateRule"]

[lib]
name = "huawei_cloud_api_definitions_UCS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-UCS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
