[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
ApplyDomainTemplate = []
BatchCopyDomain = []
BatchDeleteTags = []
BatchUpdateRuleStatus = []
CreateAccessControlTask = []
CreateDomain = []
CreateDomainByDuplicate = []
CreateDomainTemplate = []
CreateExportTask = []
CreatePreheatingTasks = []
CreateRefreshTasks = []
CreateRuleNew = []
CreateShareCacheGroups = []
CreateSubscriptionTask = []
CreateTags = []
DeleteDomain = []
DeleteDomainTemplate = []
DeleteRuleNew = []
DeleteShareCacheGroups = []
DeleteSubscriptionTask = []
DisableDomain = []
DownloadRegionCarrierExcel = []
DownloadStatisticsExcel = []
EnableDomain = []
ExportStatsOpen = []
ListAccessControlTask = []
ListBanUrl = []
ListCdnDomainTopIps = []
ListCdnDomainTopOriginUrl = []
ListCdnDomainTopPath = []
ListCdnDomainTopRefers = []
ListCdnDomainTopUas = []
ListDomainClientStats = []
ListDomainConfigs = []
ListDomains = []
ListExportTasks = []
ListRuleDetails = []
ListShareCacheGroups = []
ListSpecialConfiguration = []
ListSubscriptionTasks = []
ModifyAccountInfo = []
SetChargeModes = []
SetStatsConfig = []
ShowAppliedTemplateRecord = []
ShowBandwidthCalc = []
ShowBlackWhiteList = []
ShowCacheRules = []
ShowCertificatesHttpsInfo = []
ShowChargeModes = []
ShowDomainCountryStat = []
ShowDomainDetail = []
ShowDomainDetailByName = []
ShowDomainFullConfig = []
ShowDomainLocationStats = []
ShowDomainStats = []
ShowDomainTemplate = []
ShowHistoryTaskDetails = []
ShowHistoryTasks = []
ShowHttpInfo = []
ShowIpInfo = []
ShowLogs = []
ShowOriginHost = []
ShowQuota = []
ShowRefer = []
ShowResponseHeader = []
ShowSpecialUser = []
ShowStatsConfigs = []
ShowTags = []
ShowTopDomainNames = []
ShowTopUrl = []
ShowUrlTaskInfo = []
ShowVerifyDomainOwnerInfo = []
UpdateBlackWhiteList = []
UpdateCacheRules = []
UpdateDomainFullConfig = []
UpdateDomainMultiCertificates = []
UpdateDomainOrigin = []
UpdateDomainTemplate = []
UpdateFollow302Switch = []
UpdateFullRule = []
UpdateHttpsInfo = []
UpdateOriginHost = []
UpdatePrivateBucketAccess = []
UpdateRangeSwitch = []
UpdateRefer = []
UpdateResponseHeader = []
UpdateRuleNew = []
UpdateShareCacheGroups = []
UpdateSubscriptionTask = []
VerifyDomainOwner = []
full = ["ApplyDomainTemplate", "BatchCopyDomain", "BatchDeleteTags", "BatchUpdateRuleStatus", "CreateAccessControlTask", "CreateDomain", "CreateDomainByDuplicate", "CreateDomainTemplate", "CreateExportTask", "CreatePreheatingTasks", "CreateRefreshTasks", "CreateRuleNew", "CreateShareCacheGroups", "CreateSubscriptionTask", "CreateTags", "DeleteDomain", "DeleteDomainTemplate", "DeleteRuleNew", "DeleteShareCacheGroups", "DeleteSubscriptionTask", "DisableDomain", "DownloadRegionCarrierExcel", "DownloadStatisticsExcel", "EnableDomain", "ExportStatsOpen", "ListAccessControlTask", "ListBanUrl", "ListCdnDomainTopIps", "ListCdnDomainTopOriginUrl", "ListCdnDomainTopPath", "ListCdnDomainTopRefers", "ListCdnDomainTopUas", "ListDomainClientStats", "ListDomainConfigs", "ListDomains", "ListExportTasks", "ListRuleDetails", "ListShareCacheGroups", "ListSpecialConfiguration", "ListSubscriptionTasks", "ModifyAccountInfo", "SetChargeModes", "SetStatsConfig", "ShowAppliedTemplateRecord", "ShowBandwidthCalc", "ShowBlackWhiteList", "ShowCacheRules", "ShowCertificatesHttpsInfo", "ShowChargeModes", "ShowDomainCountryStat", "ShowDomainDetail", "ShowDomainDetailByName", "ShowDomainFullConfig", "ShowDomainLocationStats", "ShowDomainStats", "ShowDomainTemplate", "ShowHistoryTaskDetails", "ShowHistoryTasks", "ShowHttpInfo", "ShowIpInfo", "ShowLogs", "ShowOriginHost", "ShowQuota", "ShowRefer", "ShowResponseHeader", "ShowSpecialUser", "ShowStatsConfigs", "ShowTags", "ShowTopDomainNames", "ShowTopUrl", "ShowUrlTaskInfo", "ShowVerifyDomainOwnerInfo", "UpdateBlackWhiteList", "UpdateCacheRules", "UpdateDomainFullConfig", "UpdateDomainMultiCertificates", "UpdateDomainOrigin", "UpdateDomainTemplate", "UpdateFollow302Switch", "UpdateFullRule", "UpdateHttpsInfo", "UpdateOriginHost", "UpdatePrivateBucketAccess", "UpdateRangeSwitch", "UpdateRefer", "UpdateResponseHeader", "UpdateRuleNew", "UpdateShareCacheGroups", "UpdateSubscriptionTask", "VerifyDomainOwner"]

[lib]
name = "huawei_cloud_api_definitions_CDN"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CDN"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
