[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AssociateEndpointIpaddress = []
AssociateResolverQueryLogConfig = []
AssociateResolverRuleRouter = []
AssociateRouter = []
BatchCreateCombinedPublicRecordsetsTask = []
BatchCreatePublicRecordsetsTask = []
BatchCreatePublicZonesTask = []
BatchCreateRecordSetsTask = []
BatchCreateTag = []
BatchDeletePtrRecords = []
BatchDeletePublicRecordsetsTask = []
BatchDeleteRecordSetWithLine = []
BatchDeleteRecordSets = []
BatchDeleteZones = []
BatchSetRecordSetsStatus = []
BatchSetZonesStatus = []
BatchTransferPublicZonesTask = []
BatchUpdatePublicRecordsetsTask = []
BatchUpdateRecordSetWithLine = []
CreateAuthorizeTxtRecord = []
CreateAuthorizeTxtRecordVerification = []
CreateCustomLine = []
CreateEipRecordSet = []
CreateEndpoint = []
CreateLineGroup = []
CreatePrivateZone = []
CreatePtr = []
CreatePublicZone = []
CreateRecordSet = []
CreateRecordSetWithBatchLines = []
CreateRecordSetWithLine = []
CreateResolverQueryLogConfig = []
CreateResolverRule = []
CreateRetrieval = []
CreateRetrievalVerification = []
CreateTag = []
DeleteBatchCreateRecordSetsTask = []
DeleteCustomLine = []
DeleteEndpoint = []
DeleteLineGroup = []
DeletePrivateZone = []
DeletePtr = []
DeletePublicZone = []
DeleteRecordSet = []
DeleteRecordSets = []
DeleteResolverQueryLogConfig = []
DeleteResolverRule = []
DeleteTag = []
DisableDnssecConfig = []
DisassociateEndpointIpaddress = []
DisassociateResolverQueryLogConfig = []
DisassociateResolverRuleRouter = []
DisassociateRouter = []
EnableDnssecConfig = []
ListApiVersions = []
ListBatchOperationTasks = []
ListCustomLine = []
ListEndpointIpaddresses = []
ListEndpointVpcs = []
ListEndpoints = []
ListInstances = []
ListLineGroups = []
ListNameServers = []
ListPrivateZones = []
ListPtrRecords = []
ListPtrs = []
ListPublicZoneLines = []
ListPublicZones = []
ListRecordSets = []
ListRecordSetsByZone = []
ListRecordSetsWithLine = []
ListResolverQueryLogConfigs = []
ListResolverRules = []
ListSystemLines = []
ListTag = []
ListTags = []
RestorePtrRecord = []
SetPrivateZoneProxyPattern = []
SetRecordSetsStatus = []
ShowApiInfo = []
ShowAuthorizeTxtRecord = []
ShowBatchCreateRecordSetsTask = []
ShowBatchOperationTask = []
ShowDnssecConfig = []
ShowDomainDetection = []
ShowDomainQuota = []
ShowEmailRecordSet = []
ShowEndpoint = []
ShowLineGroup = []
ShowPrivateZone = []
ShowPrivateZoneNameServer = []
ShowPtr = []
ShowPtrRecordSet = []
ShowPublicZone = []
ShowPublicZoneNameServer = []
ShowRecordSet = []
ShowRecordSetByZone = []
ShowRecordSetWithLine = []
ShowResolverQueryLogConfig = []
ShowResolverRule = []
full = ["AssociateEndpointIpaddress", "AssociateResolverQueryLogConfig", "AssociateResolverRuleRouter", "AssociateRouter", "BatchCreateCombinedPublicRecordsetsTask", "BatchCreatePublicRecordsetsTask", "BatchCreatePublicZonesTask", "BatchCreateRecordSetsTask", "BatchCreateTag", "BatchDeletePtrRecords", "BatchDeletePublicRecordsetsTask", "BatchDeleteRecordSets", "BatchDeleteRecordSetWithLine", "BatchDeleteZones", "BatchSetRecordSetsStatus", "BatchSetZonesStatus", "BatchTransferPublicZonesTask", "BatchUpdatePublicRecordsetsTask", "BatchUpdateRecordSetWithLine", "CreateAuthorizeTxtRecord", "CreateAuthorizeTxtRecordVerification", "CreateCustomLine", "CreateEipRecordSet", "CreateEndpoint", "CreateLineGroup", "CreatePrivateZone", "CreatePtr", "CreatePublicZone", "CreateRecordSet", "CreateRecordSetWithBatchLines", "CreateRecordSetWithLine", "CreateResolverQueryLogConfig", "CreateResolverRule", "CreateRetrieval", "CreateRetrievalVerification", "CreateTag", "DeleteBatchCreateRecordSetsTask", "DeleteCustomLine", "DeleteEndpoint", "DeleteLineGroup", "DeletePrivateZone", "DeletePtr", "DeletePublicZone", "DeleteRecordSet", "DeleteRecordSets", "DeleteResolverQueryLogConfig", "DeleteResolverRule", "DeleteTag", "DisableDnssecConfig", "DisassociateEndpointIpaddress", "DisassociateResolverQueryLogConfig", "DisassociateResolverRuleRouter", "DisassociateRouter", "EnableDnssecConfig", "ListApiVersions", "ListBatchOperationTasks", "ListCustomLine", "ListEndpointIpaddresses", "ListEndpoints", "ListEndpointVpcs", "ListInstances", "ListLineGroups", "ListNameServers", "ListPrivateZones", "ListPtrRecords", "ListPtrs", "ListPublicZoneLines", "ListPublicZones", "ListRecordSets", "ListRecordSetsByZone", "ListRecordSetsWithLine", "ListResolverQueryLogConfigs", "ListResolverRules", "ListSystemLines", "ListTag", "ListTags", "RestorePtrRecord", "SetPrivateZoneProxyPattern", "SetRecordSetsStatus", "ShowApiInfo", "ShowAuthorizeTxtRecord", "ShowBatchCreateRecordSetsTask", "ShowBatchOperationTask", "ShowDnssecConfig", "ShowDomainDetection", "ShowDomainQuota", "ShowEmailRecordSet", "ShowEndpoint", "ShowLineGroup", "ShowPrivateZone", "ShowPrivateZoneNameServer", "ShowPtr", "ShowPtrRecordSet", "ShowPublicZone", "ShowPublicZoneNameServer", "ShowRecordSet", "ShowRecordSetByZone", "ShowRecordSetWithLine", "ShowResolverQueryLogConfig", "ShowResolverRule"]

[lib]
name = "huawei_cloud_api_definitions_DNS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DNS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
