[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AcceptVpcPeering = []
AddFirewallRules = []
AddSecurityGroups = []
AddSourcesToTrafficMirrorSession = []
AddVpcExtendCidr = []
AssociateRouteTable = []
AssociateSubnetFirewall = []
BatchCreateFirewallTags = []
BatchCreatePortTags = []
BatchCreateSecurityGroupRules = []
BatchCreateSecurityGroupTags = []
BatchCreateSubNetworkInterface = []
BatchCreateSubnetTags = []
BatchCreateVpcTags = []
BatchDeleteFirewallTags = []
BatchDeletePortTags = []
BatchDeleteSecurityGroupTags = []
BatchDeleteSubnetTags = []
BatchDeleteVpcTags = []
CountFirewallsByTags = []
CountPortsByTags = []
CreateAddressGroup = []
CreateFirewall = []
CreateFirewallTag = []
CreateFlowLog = []
CreatePort = []
CreatePortTag = []
CreatePrivateip = []
CreateRouteTable = []
CreateSecurityGroup = []
CreateSecurityGroupRule = []
CreateSecurityGroupTag = []
CreateSubNetworkInterface = []
CreateSubnet = []
CreateSubnetTag = []
CreateTrafficMirrorFilter = []
CreateTrafficMirrorFilterRule = []
CreateTrafficMirrorSession = []
CreateVirsubnetCidrReservation = []
CreateVpc = []
CreateVpcPeering = []
CreateVpcResourceTag = []
CreateVpcRoute = []
DeleteAddressGroup = []
DeleteFirewall = []
DeleteFirewallTag = []
DeleteFlowLog = []
DeleteIpAddressGroupForce = []
DeletePort = []
DeletePortTag = []
DeletePrivateip = []
DeleteRouteTable = []
DeleteSecurityGroup = []
DeleteSecurityGroupRule = []
DeleteSecurityGroupTag = []
DeleteSubNetworkInterface = []
DeleteSubnet = []
DeleteSubnetTag = []
DeleteTrafficMirrorFilter = []
DeleteTrafficMirrorFilterRule = []
DeleteTrafficMirrorSession = []
DeleteVirsubnetCidrReservation = []
DeleteVpc = []
DeleteVpcPeering = []
DeleteVpcRoute = []
DeleteVpcTag = []
DisassociateRouteTable = []
DisassociateSubnetFirewall = []
ListAddressGroup = []
ListAddressGroupsDependency = []
ListApiVersion = []
ListFirewall = []
ListFirewallTags = []
ListFirewallsByTags = []
ListFlowLogs = []
ListPortTags = []
ListPorts = []
ListPortsByTags = []
ListPrivateips = []
ListRouteTables = []
ListSecurityGroupRules = []
ListSecurityGroupTags = []
ListSecurityGroups = []
ListSecurityGroupsByTags = []
ListSubNetworkInterfaces = []
ListSubnetTags = []
ListSubnets = []
ListSubnetsByTags = []
ListTrafficMirrorFilterRules = []
ListTrafficMirrorFilters = []
ListTrafficMirrorSessions = []
ListVirsubnetCidrReservations = []
ListVirsubnets = []
ListVpcPeerings = []
ListVpcRoutes = []
ListVpcTags = []
ListVpcs = []
ListVpcsByTags = []
NeutronAddFirewallRule = []
NeutronAddRouterInterface = []
full = ["AcceptVpcPeering", "AddFirewallRules", "AddSecurityGroups", "AddSourcesToTrafficMirrorSession", "AddVpcExtendCidr", "AssociateRouteTable", "AssociateSubnetFirewall", "BatchCreateFirewallTags", "BatchCreatePortTags", "BatchCreateSecurityGroupRules", "BatchCreateSecurityGroupTags", "BatchCreateSubnetTags", "BatchCreateSubNetworkInterface", "BatchCreateVpcTags", "BatchDeleteFirewallTags", "BatchDeletePortTags", "BatchDeleteSecurityGroupTags", "BatchDeleteSubnetTags", "BatchDeleteVpcTags", "CountFirewallsByTags", "CountPortsByTags", "CreateAddressGroup", "CreateFirewall", "CreateFirewallTag", "CreateFlowLog", "CreatePort", "CreatePortTag", "CreatePrivateip", "CreateRouteTable", "CreateSecurityGroup", "CreateSecurityGroupRule", "CreateSecurityGroupTag", "CreateSubnet", "CreateSubnetTag", "CreateSubNetworkInterface", "CreateTrafficMirrorFilter", "CreateTrafficMirrorFilterRule", "CreateTrafficMirrorSession", "CreateVirsubnetCidrReservation", "CreateVpc", "CreateVpcPeering", "CreateVpcResourceTag", "CreateVpcRoute", "DeleteAddressGroup", "DeleteFirewall", "DeleteFirewallTag", "DeleteFlowLog", "DeleteIpAddressGroupForce", "DeletePort", "DeletePortTag", "DeletePrivateip", "DeleteRouteTable", "DeleteSecurityGroup", "DeleteSecurityGroupRule", "DeleteSecurityGroupTag", "DeleteSubnet", "DeleteSubnetTag", "DeleteSubNetworkInterface", "DeleteTrafficMirrorFilter", "DeleteTrafficMirrorFilterRule", "DeleteTrafficMirrorSession", "DeleteVirsubnetCidrReservation", "DeleteVpc", "DeleteVpcPeering", "DeleteVpcRoute", "DeleteVpcTag", "DisassociateRouteTable", "DisassociateSubnetFirewall", "ListAddressGroup", "ListAddressGroupsDependency", "ListApiVersion", "ListFirewall", "ListFirewallsByTags", "ListFirewallTags", "ListFlowLogs", "ListPorts", "ListPortsByTags", "ListPortTags", "ListPrivateips", "ListRouteTables", "ListSecurityGroupRules", "ListSecurityGroups", "ListSecurityGroupsByTags", "ListSecurityGroupTags", "ListSubnets", "ListSubnetsByTags", "ListSubnetTags", "ListSubNetworkInterfaces", "ListTrafficMirrorFilterRules", "ListTrafficMirrorFilters", "ListTrafficMirrorSessions", "ListVirsubnetCidrReservations", "ListVirsubnets", "ListVpcPeerings", "ListVpcRoutes", "ListVpcs", "ListVpcsByTags", "ListVpcTags", "NeutronAddFirewallRule", "NeutronAddRouterInterface"]

[lib]
name = "huawei_cloud_api_definitions_VPC"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-VPC"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
