[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddApplication = []
AddBridge = []
AddCertificate = []
AddDevice = []
AddDeviceGroup = []
AddFunctions = []
AddHarmonySoftBus = []
AddQueue = []
AddTunnel = []
BatchShowQueue = []
BindDevicePolicy = []
BroadcastMessage = []
ChangeGateway = []
ChangeRuleStatus = []
CheckCertificate = []
CloseDeviceTunnel = []
CountAsyncHistoryCommands = []
CreateAccessCode = []
CreateAsyncCommand = []
CreateBatchTask = []
CreateCommand = []
CreateDeviceAuthenticationTemplate = []
CreateDeviceAuthorizer = []
CreateDevicePolicy = []
CreateDeviceProxy = []
CreateDomainConfiguration = []
CreateMessage = []
CreateOrDeleteDeviceInGroup = []
CreateOtaModule = []
CreateOtaPackage = []
CreateProduct = []
CreateProvisioningTemplate = []
CreateRoutingBacklogPolicy = []
CreateRoutingFlowControlPolicy = []
CreateRoutingRule = []
CreateRule = []
CreateRuleAction = []
CreateSecurityProfile = []
CreateServerCertificate = []
CreateSyncHarmonySoftBus = []
DeleteApplication = []
DeleteBatchTask = []
DeleteBatchTaskFile = []
DeleteBridge = []
DeleteCertificate = []
DeleteDevice = []
DeleteDeviceAuthenticationTemplate = []
DeleteDeviceAuthorizer = []
DeleteDeviceCertificate = []
DeleteDeviceGroup = []
DeleteDeviceMessage = []
DeleteDevicePolicy = []
DeleteDeviceProxy = []
DeleteDeviceShadow = []
DeleteDeviceTunnel = []
DeleteDomainConfiguration = []
DeleteFunctions = []
DeleteHarmonySoftBus = []
DeleteOtaModule = []
DeleteOtaPackage = []
DeleteProduct = []
DeleteProvisioningTemplate = []
DeleteQueue = []
DeleteRoutingBacklogPolicy = []
DeleteRoutingFlowControlPolicy = []
DeleteRoutingRule = []
DeleteRule = []
DeleteRuleAction = []
DeleteSecurityProfile = []
DeleteServerCertificate = []
FreezeDevice = []
ListAsyncCommands = []
ListAsyncHistoryCommands = []
ListBatchTaskFiles = []
ListBatchTasks = []
ListBridges = []
ListCertificates = []
ListDeviceAuthenticationTemplates = []
ListDeviceAuthorizers = []
ListDeviceByDeviceCertificate = []
ListDeviceCertificate = []
ListDeviceGroups = []
ListDeviceGroupsByDevice = []
ListDeviceMessages = []
ListDevicePolicies = []
ListDeviceProxies = []
ListDeviceTunnels = []
ListDevices = []
ListDomainConfigurations = []
ListFunctions = []
ListHarmonySoftBus = []
ListOtaModules = []
ListOtaPackageInfo = []
ListProducts = []
ListProperties = []
ListProvisioningTemplates = []
ListResourcesByTags = []
ListRoutingBacklogPolicy = []
ListRoutingFlowControlPolicy = []
ListRoutingRules = []
full = ["AddApplication", "AddBridge", "AddCertificate", "AddDevice", "AddDeviceGroup", "AddFunctions", "AddHarmonySoftBus", "AddQueue", "AddTunnel", "BatchShowQueue", "BindDevicePolicy", "BroadcastMessage", "ChangeGateway", "ChangeRuleStatus", "CheckCertificate", "CloseDeviceTunnel", "CountAsyncHistoryCommands", "CreateAccessCode", "CreateAsyncCommand", "CreateBatchTask", "CreateCommand", "CreateDeviceAuthenticationTemplate", "CreateDeviceAuthorizer", "CreateDevicePolicy", "CreateDeviceProxy", "CreateDomainConfiguration", "CreateMessage", "CreateOrDeleteDeviceInGroup", "CreateOtaModule", "CreateOtaPackage", "CreateProduct", "CreateProvisioningTemplate", "CreateRoutingBacklogPolicy", "CreateRoutingFlowControlPolicy", "CreateRoutingRule", "CreateRule", "CreateRuleAction", "CreateSecurityProfile", "CreateServerCertificate", "CreateSyncHarmonySoftBus", "DeleteApplication", "DeleteBatchTask", "DeleteBatchTaskFile", "DeleteBridge", "DeleteCertificate", "DeleteDevice", "DeleteDeviceAuthenticationTemplate", "DeleteDeviceAuthorizer", "DeleteDeviceCertificate", "DeleteDeviceGroup", "DeleteDeviceMessage", "DeleteDevicePolicy", "DeleteDeviceProxy", "DeleteDeviceShadow", "DeleteDeviceTunnel", "DeleteDomainConfiguration", "DeleteFunctions", "DeleteHarmonySoftBus", "DeleteOtaModule", "DeleteOtaPackage", "DeleteProduct", "DeleteProvisioningTemplate", "DeleteQueue", "DeleteRoutingBacklogPolicy", "DeleteRoutingFlowControlPolicy", "DeleteRoutingRule", "DeleteRule", "DeleteRuleAction", "DeleteSecurityProfile", "DeleteServerCertificate", "FreezeDevice", "ListAsyncCommands", "ListAsyncHistoryCommands", "ListBatchTaskFiles", "ListBatchTasks", "ListBridges", "ListCertificates", "ListDeviceAuthenticationTemplates", "ListDeviceAuthorizers", "ListDeviceByDeviceCertificate", "ListDeviceCertificate", "ListDeviceGroups", "ListDeviceGroupsByDevice", "ListDeviceMessages", "ListDevicePolicies", "ListDeviceProxies", "ListDevices", "ListDeviceTunnels", "ListDomainConfigurations", "ListFunctions", "ListHarmonySoftBus", "ListOtaModules", "ListOtaPackageInfo", "ListProducts", "ListProperties", "ListProvisioningTemplates", "ListResourcesByTags", "ListRoutingBacklogPolicy", "ListRoutingFlowControlPolicy", "ListRoutingRules"]

[lib]
name = "huawei_cloud_api_definitions_IoTDA"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-IoTDA"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
