[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddQueueUserList = []
AddWorkloadPlanStage = []
AddWorkloadQueue = []
AddWorkloadRule = []
AssociateEip = []
AssociateElb = []
BatchCreateClusterCn = []
BatchCreateResourceTag = []
BatchDeleteClusterCn = []
BatchDeleteResourceTag = []
CancelReadonlyCluster = []
ChangeSecurityGroup = []
CheckCluster = []
CheckClusterShrink = []
CheckDisasterName = []
CheckGrowCluster = []
CheckTableRestore = []
ConvertToLogicalCluster = []
CopySnapshot = []
CreateAlarmSub = []
CreateCluster = []
CreateClusterDns = []
CreateClusterV2 = []
CreateClusterWorkload = []
CreateDataSource = []
CreateDatabaseUser = []
CreateDisasterRecovery = []
CreateEventSub = []
CreateLogicalCluster = []
CreateLogicalClusterPlan = []
CreateSnapshot = []
CreateSnapshotPolicy = []
CreateWorkloadPlan = []
DeleteAlarmSub = []
DeleteCluster = []
DeleteClusterDns = []
DeleteClusterNodes = []
DeleteDataSource = []
DeleteDatabaseUser = []
DeleteDisasterRecovery = []
DeleteDwsCluster = []
DeleteEventSub = []
DeleteLogicalCluster = []
DeleteLogicalClusterPlan = []
DeleteQueueUserList = []
DeleteSnapshot = []
DeleteSnapshotPolicy = []
DeleteWorkloadPlan = []
DeleteWorkloadPlanStage = []
DeleteWorkloadQueue = []
DeleteWorkloadRule = []
DisableLogicalClusterPlan = []
DisableLtsLogs = []
DisassociateEip = []
DisassociateElb = []
EnableLogicalCluster = []
EnableLogicalClusterPlan = []
EnableLtsLogs = []
EncryptCluster = []
ExecuteClusterUpgradeAction = []
ExecuteDatabaseOmUserAction = []
ExecuteFlavorChange = []
ExecuteRedistributionCluster = []
ExpandInstanceStorage = []
ExportDatabaseUsers = []
ExportUserAuthority = []
ListAlarmConfigs = []
ListAlarmDetail = []
ListAlarmStatistic = []
ListAlarmSubs = []
ListAuditLog = []
ListAvailabilityZones = []
ListAvailableDisasterClusters = []
ListClusterActions = []
ListClusterCn = []
ListClusterConfigurations = []
ListClusterConfigurationsParameter = []
ListClusterDetails = []
ListClusterEndpoints = []
ListClusterNodes = []
ListClusterScaleInNumbers = []
ListClusterSnapshots = []
ListClusterTags = []
ListClusterWorkload = []
ListClusters = []
ListConfigurationsAuditRecords = []
ListDataSource = []
ListDatabaseObjects = []
ListDatabaseUserAuthorities = []
ListDatabaseUsers = []
ListDisasterRecover = []
ListDssPools = []
ListElbs = []
ListEventSpecs = []
ListEventSubs = []
ListEvents = []
ListHostDisk = []
ListHostNet = []
ListHostOverview = []
ListJobDetails = []
full = ["AddQueueUserList", "AddWorkloadPlanStage", "AddWorkloadQueue", "AddWorkloadRule", "AssociateEip", "AssociateElb", "BatchCreateClusterCn", "BatchCreateResourceTag", "BatchDeleteClusterCn", "BatchDeleteResourceTag", "CancelReadonlyCluster", "ChangeSecurityGroup", "CheckCluster", "CheckClusterShrink", "CheckDisasterName", "CheckGrowCluster", "CheckTableRestore", "ConvertToLogicalCluster", "CopySnapshot", "CreateAlarmSub", "CreateCluster", "CreateClusterDns", "CreateClusterV2", "CreateClusterWorkload", "CreateDatabaseUser", "CreateDataSource", "CreateDisasterRecovery", "CreateEventSub", "CreateLogicalCluster", "CreateLogicalClusterPlan", "CreateSnapshot", "CreateSnapshotPolicy", "CreateWorkloadPlan", "DeleteAlarmSub", "DeleteCluster", "DeleteClusterDns", "DeleteClusterNodes", "DeleteDatabaseUser", "DeleteDataSource", "DeleteDisasterRecovery", "DeleteDwsCluster", "DeleteEventSub", "DeleteLogicalCluster", "DeleteLogicalClusterPlan", "DeleteQueueUserList", "DeleteSnapshot", "DeleteSnapshotPolicy", "DeleteWorkloadPlan", "DeleteWorkloadPlanStage", "DeleteWorkloadQueue", "DeleteWorkloadRule", "DisableLogicalClusterPlan", "DisableLtsLogs", "DisassociateEip", "DisassociateElb", "EnableLogicalCluster", "EnableLogicalClusterPlan", "EnableLtsLogs", "EncryptCluster", "ExecuteClusterUpgradeAction", "ExecuteDatabaseOmUserAction", "ExecuteFlavorChange", "ExecuteRedistributionCluster", "ExpandInstanceStorage", "ExportDatabaseUsers", "ExportUserAuthority", "ListAlarmConfigs", "ListAlarmDetail", "ListAlarmStatistic", "ListAlarmSubs", "ListAuditLog", "ListAvailabilityZones", "ListAvailableDisasterClusters", "ListClusterActions", "ListClusterCn", "ListClusterConfigurations", "ListClusterConfigurationsParameter", "ListClusterDetails", "ListClusterEndpoints", "ListClusterNodes", "ListClusters", "ListClusterScaleInNumbers", "ListClusterSnapshots", "ListClusterTags", "ListClusterWorkload", "ListConfigurationsAuditRecords", "ListDatabaseObjects", "ListDatabaseUserAuthorities", "ListDatabaseUsers", "ListDataSource", "ListDisasterRecover", "ListDssPools", "ListElbs", "ListEvents", "ListEventSpecs", "ListEventSubs", "ListHostDisk", "ListHostNet", "ListHostOverview", "ListJobDetails"]

[lib]
name = "huawei_cloud_api_definitions_DWS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DWS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
