[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddDeployKey = []
AddDeployKeyV2 = []
AddGroupWebhook = []
AddHooks = []
AddProjectWebhook = []
AddProtectBranchV2 = []
AddRepoMembers = []
AddRepositoryMembers = []
AddRepositoryWebhook = []
AddSshKey = []
AddSubmodule = []
AddTagV2 = []
AddTenantTrustedIpAddress = []
AddTrustedIpAddress = []
ApprovalMergeRequest = []
AssociateGroupUserGroup = []
AssociateIssues = []
AssociateRemoteMirror = []
AssociateRepositoryUserGroup = []
BatchCreateProtectedBranch = []
BatchCreateProtectedTags = []
BatchDeleteBranch = []
BatchDeleteProtectedBranches = []
BatchDeleteProtectedTags = []
BatchDeleteRepositoryFilePushPermissions = []
BatchUpdateProtectedBranches = []
BatchUpdateProtectedTags = []
BatchUpdateRepositoryFilePushPermissions = []
BatchValidateRepoNames = []
BatchValidateUserGroupPermissions = []
CheckDeployKey = []
CheckGroupDeployKey = []
CreateBranch = []
CreateCherryPickMergeRequest = []
CreateCommit = []
CreateCommitRevert = []
CreateDir = []
CreateFile = []
CreateFilePushPermission = []
CreateGroup = []
CreateGroupMergeRequestApproverSetting = []
CreateGroupMergeRequestTemplate = []
CreateMergeRequest = []
CreateMergeRequestApproverSetting = []
CreateMergeRequestDiscussion = []
CreateMergeRequestDiscussionNote = []
CreateMergeRequestDiscussionResponse = []
CreateMergeRequestTemplate = []
CreateNewBranch = []
CreateProjectAndRepositories = []
CreateProjectAndforkRepositories = []
CreateProjectMergeRequestApproverSetting = []
CreateProjectMergeRequestTemplate = []
CreateProjectProtectedBranches = []
CreateProjectProtectedTags = []
CreateRepository = []
CreateRepositoryCommitRule = []
CreateRepositoryLabel = []
CreateRepositorySystemLabels = []
CreateReviewSetting = []
CreateTag = []
DeleteBranch = []
DeleteDeployKey = []
DeleteDeployKeyV2 = []
DeleteFile = []
DeleteGroup = []
DeleteGroupMergeRequestApproverSetting = []
DeleteGroupMergeRequestTemplate = []
DeleteHooks = []
DeleteMergeRequestApproverSetting = []
DeleteMergeRequestDiscussion = []
DeleteMergeRequestTemplate = []
DeleteMergeRequestVote = []
DeleteProjectMergeRequestApproverSetting = []
DeleteProjectMergeRequestTemplate = []
DeleteProtectedBranch = []
DeleteProtectedTag = []
DeleteRepoMember = []
DeleteRepository = []
DeleteRepositoryLabel = []
DeleteSshKey = []
DeleteTag = []
DeleteTenantTrustedIpAddress = []
DeleteTrustedIpAddress = []
DownloadArchive = []
DownloadBlobsRaw = []
ExecuteRepositoryStatistics = []
ExportTenantRepositories = []
GetAllRepositoryByProjectId = []
GetProductTemplates = []
GetRepositoryByProjectId = []
GetTemplates = []
ImportMergeRequest = []
ListBranchRelatedWorkItems = []
ListBranches = []
ListBranchesByRepositoryId = []
ListCommitAssociatedMergeRequests = []
ListCommitAssociatedRefs = []
ListCommitDiscussions = []
ListCommits = []
full = ["AddDeployKey", "AddDeployKeyV2", "AddGroupWebhook", "AddHooks", "AddProjectWebhook", "AddProtectBranchV2", "AddRepoMembers", "AddRepositoryMembers", "AddRepositoryWebhook", "AddSshKey", "AddSubmodule", "AddTagV2", "AddTenantTrustedIpAddress", "AddTrustedIpAddress", "ApprovalMergeRequest", "AssociateGroupUserGroup", "AssociateIssues", "AssociateRemoteMirror", "AssociateRepositoryUserGroup", "BatchCreateProtectedBranch", "BatchCreateProtectedTags", "BatchDeleteBranch", "BatchDeleteProtectedBranches", "BatchDeleteProtectedTags", "BatchDeleteRepositoryFilePushPermissions", "BatchUpdateProtectedBranches", "BatchUpdateProtectedTags", "BatchUpdateRepositoryFilePushPermissions", "BatchValidateRepoNames", "BatchValidateUserGroupPermissions", "CheckDeployKey", "CheckGroupDeployKey", "CreateBranch", "CreateCherryPickMergeRequest", "CreateCommit", "CreateCommitRevert", "CreateDir", "CreateFile", "CreateFilePushPermission", "CreateGroup", "CreateGroupMergeRequestApproverSetting", "CreateGroupMergeRequestTemplate", "CreateMergeRequest", "CreateMergeRequestApproverSetting", "CreateMergeRequestDiscussion", "CreateMergeRequestDiscussionNote", "CreateMergeRequestDiscussionResponse", "CreateMergeRequestTemplate", "CreateNewBranch", "CreateProjectAndforkRepositories", "CreateProjectAndRepositories", "CreateProjectMergeRequestApproverSetting", "CreateProjectMergeRequestTemplate", "CreateProjectProtectedBranches", "CreateProjectProtectedTags", "CreateRepository", "CreateRepositoryCommitRule", "CreateRepositoryLabel", "CreateRepositorySystemLabels", "CreateReviewSetting", "CreateTag", "DeleteBranch", "DeleteDeployKey", "DeleteDeployKeyV2", "DeleteFile", "DeleteGroup", "DeleteGroupMergeRequestApproverSetting", "DeleteGroupMergeRequestTemplate", "DeleteHooks", "DeleteMergeRequestApproverSetting", "DeleteMergeRequestDiscussion", "DeleteMergeRequestTemplate", "DeleteMergeRequestVote", "DeleteProjectMergeRequestApproverSetting", "DeleteProjectMergeRequestTemplate", "DeleteProtectedBranch", "DeleteProtectedTag", "DeleteRepoMember", "DeleteRepository", "DeleteRepositoryLabel", "DeleteSshKey", "DeleteTag", "DeleteTenantTrustedIpAddress", "DeleteTrustedIpAddress", "DownloadArchive", "DownloadBlobsRaw", "ExecuteRepositoryStatistics", "ExportTenantRepositories", "GetAllRepositoryByProjectId", "GetProductTemplates", "GetRepositoryByProjectId", "GetTemplates", "ImportMergeRequest", "ListBranches", "ListBranchesByRepositoryId", "ListBranchRelatedWorkItems", "ListCommitAssociatedMergeRequests", "ListCommitAssociatedRefs", "ListCommitDiscussions", "ListCommits"]

[lib]
name = "huawei_cloud_api_definitions_CodeArtsRepo"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CodeArtsRepo"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
