[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddFavorite = []
AddIndependentNode = []
ChangeClusterSubnet = []
ChangeMode = []
ChangeSecurityGroup = []
CloseAiOpsSetting = []
CreateAgency = []
CreateAiOps = []
CreateAutoCreatePolicy = []
CreateBindPublic = []
CreateCluster = []
CreateClustersTags = []
CreateCnf = []
CreateElbListener = []
CreateLoadIkThesaurus = []
CreateLogBackup = []
CreateSnapshot = []
DeleteAiOps = []
DeleteCerts = []
DeleteCluster = []
DeleteClustersTags = []
DeleteConf = []
DeleteIkThesaurus = []
DeleteLogstashConf = []
DeleteLogstashTemplate = []
DeleteSnapshot = []
DeleteTemplate = []
DownloadCert = []
EnableOrDisableElb = []
ListActions = []
ListAiOps = []
ListCerts = []
ListClustersDetails = []
ListClustersTags = []
ListConfs = []
ListElbCerts = []
ListElbs = []
ListFlavors = []
ListImages = []
ListLogsJob = []
ListPipelines = []
ListRoutes = []
ListSmnTopics = []
ListSnapshots = []
ListTemplates = []
ListYmls = []
ListYmlsJob = []
RebootCluster = []
ResetPassword = []
RestartCluster = []
RestoreSnapshot = []
RetryUpgradeTask = []
RollingRestart = []
ShowAiOpsDetector = []
ShowAiOpsSetting = []
ShowAutoCreatePolicy = []
ShowCertsDetail = []
ShowClusterDetail = []
ShowClusterTag = []
ShowClusterVolumeUsage = []
ShowDataStoreFlavorDetail = []
ShowElbDetail = []
ShowFlavorDetail = []
ShowGetConfDetail = []
ShowGetLogSetting = []
ShowIkThesaurus = []
ShowLogBackup = []
ShowResizeFlavors = []
ShowVpcepConnection = []
StartAutoCreateSnapshots = []
StartAutoSetting = []
StartConnectivityTest = []
StartHotPipeline = []
StartKibanaPublic = []
StartLogAutoBackupPolicy = []
StartLogs = []
StartPipeline = []
StartPublicWhitelist = []
StartTargetClusterConnectivityTest = []
StartVpecp = []
StopAutoCreateSnapshots = []
StopHotPipeline = []
StopLogAutoBackupPolicy = []
StopLogs = []
StopPipeline = []
StopPublicKibanaWhitelist = []
StopPublicWhitelist = []
StopSnapshot = []
StopVpecp = []
UpdateAiOpsSetting = []
UpdateAlterKibana = []
UpdateAzByInstanceType = []
UpdateBatchClustersTags = []
UpdateCloseKibana = []
UpdateClusterName = []
UpdateCnf = []
UpdateEsListener = []
UpdateExtendCluster = []
UpdateExtendInstanceStorage = []
UpdateFlavor = []
full = ["AddFavorite", "AddIndependentNode", "ChangeClusterSubnet", "ChangeMode", "ChangeSecurityGroup", "CloseAiOpsSetting", "CreateAgency", "CreateAiOps", "CreateAutoCreatePolicy", "CreateBindPublic", "CreateCluster", "CreateClustersTags", "CreateCnf", "CreateElbListener", "CreateLoadIkThesaurus", "CreateLogBackup", "CreateSnapshot", "DeleteAiOps", "DeleteCerts", "DeleteCluster", "DeleteClustersTags", "DeleteConf", "DeleteIkThesaurus", "DeleteLogstashConf", "DeleteLogstashTemplate", "DeleteSnapshot", "DeleteTemplate", "DownloadCert", "EnableOrDisableElb", "ListActions", "ListAiOps", "ListCerts", "ListClustersDetails", "ListClustersTags", "ListConfs", "ListElbCerts", "ListElbs", "ListFlavors", "ListImages", "ListLogsJob", "ListPipelines", "ListRoutes", "ListSmnTopics", "ListSnapshots", "ListTemplates", "ListYmls", "ListYmlsJob", "RebootCluster", "ResetPassword", "RestartCluster", "RestoreSnapshot", "RetryUpgradeTask", "RollingRestart", "ShowAiOpsDetector", "ShowAiOpsSetting", "ShowAutoCreatePolicy", "ShowCertsDetail", "ShowClusterDetail", "ShowClusterTag", "ShowClusterVolumeUsage", "ShowDataStoreFlavorDetail", "ShowElbDetail", "ShowFlavorDetail", "ShowGetConfDetail", "ShowGetLogSetting", "ShowIkThesaurus", "ShowLogBackup", "ShowResizeFlavors", "ShowVpcepConnection", "StartAutoCreateSnapshots", "StartAutoSetting", "StartConnectivityTest", "StartHotPipeline", "StartKibanaPublic", "StartLogAutoBackupPolicy", "StartLogs", "StartPipeline", "StartPublicWhitelist", "StartTargetClusterConnectivityTest", "StartVpecp", "StopAutoCreateSnapshots", "StopHotPipeline", "StopLogAutoBackupPolicy", "StopLogs", "StopPipeline", "StopPublicKibanaWhitelist", "StopPublicWhitelist", "StopSnapshot", "StopVpecp", "UpdateAiOpsSetting", "UpdateAlterKibana", "UpdateAzByInstanceType", "UpdateBatchClustersTags", "UpdateCloseKibana", "UpdateClusterName", "UpdateCnf", "UpdateEsListener", "UpdateExtendCluster", "UpdateExtendInstanceStorage", "UpdateFlavor"]

[lib]
name = "huawei_cloud_api_definitions_CSS"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CSS"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
