[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddPublicipsIntoSharedBandwidth = []
AssociatePublicips = []
AttachBatchPublicIp = []
AttachShareBandwidth = []
BatchCreatePublicipTags = []
BatchCreatePublicips = []
BatchCreateSharedBandwidths = []
BatchDeletePublicIp = []
BatchDeletePublicipTags = []
BatchDisassociatePublicips = []
BatchModifyBandwidth = []
ChangeBandwidthToPeriod = []
ChangePublicipToPeriod = []
CountEipAvailableResources = []
CountPublicIp = []
CountPublicIpInstance = []
CreateBandwidthRuleV3 = []
CreatePrePaidPublicip = []
CreatePublicip = []
CreatePublicipTag = []
CreateSharedBandwidth = []
CreateTenantVpcIgw = []
DeleteBandwidthRuleV3 = []
DeletePublicip = []
DeletePublicipTag = []
DeleteSharedBandwidth = []
DeleteTenantVpcIgw = []
DetachBatchPublicIp = []
DetachShareBandwidth = []
DisableNat64 = []
DisassociatePublicips = []
EnableNat64 = []
ListBandwidth = []
ListBandwidthPkg = []
ListBandwidthRuleV3 = []
ListBandwidths = []
ListBandwidthsLimit = []
ListCommonPools = []
ListEipBandwidths = []
ListProjectGeipBindings = []
ListPublicipPool = []
ListPublicipTags = []
ListPublicips = []
ListPublicipsByTags = []
ListQuotas = []
ListShareBandwidthTypes = []
ListTenantVpcIgws = []
NeutronCreateFloatingIp = []
NeutronDeleteFloatingIp = []
NeutronListFloatingIps = []
NeutronShowFloatingIp = []
NeutronUpdateFloatingIp = []
RemovePublicipsFromSharedBandwidth = []
ShowBandwidth = []
ShowBandwidthRuleV3 = []
ShowInternalVpcIgw = []
ShowPublicIpType = []
ShowPublicip = []
ShowPublicipPool = []
ShowPublicipPoolTypes = []
ShowPublicipTags = []
ShowResourcesJobDetail = []
UpdateBandwidth = []
UpdateBandwidthRuleV3 = []
UpdatePrePaidBandwidth = []
UpdatePublicip = []
UpdatePublicipPool = []
UpdateTenantVpcIgw = []
full = ["AddPublicipsIntoSharedBandwidth", "AssociatePublicips", "AttachBatchPublicIp", "AttachShareBandwidth", "BatchCreatePublicips", "BatchCreatePublicipTags", "BatchCreateSharedBandwidths", "BatchDeletePublicIp", "BatchDeletePublicipTags", "BatchDisassociatePublicips", "BatchModifyBandwidth", "ChangeBandwidthToPeriod", "ChangePublicipToPeriod", "CountEipAvailableResources", "CountPublicIp", "CountPublicIpInstance", "CreateBandwidthRuleV3", "CreatePrePaidPublicip", "CreatePublicip", "CreatePublicipTag", "CreateSharedBandwidth", "CreateTenantVpcIgw", "DeleteBandwidthRuleV3", "DeletePublicip", "DeletePublicipTag", "DeleteSharedBandwidth", "DeleteTenantVpcIgw", "DetachBatchPublicIp", "DetachShareBandwidth", "DisableNat64", "DisassociatePublicips", "EnableNat64", "ListBandwidth", "ListBandwidthPkg", "ListBandwidthRuleV3", "ListBandwidths", "ListBandwidthsLimit", "ListCommonPools", "ListEipBandwidths", "ListProjectGeipBindings", "ListPublicipPool", "ListPublicips", "ListPublicipsByTags", "ListPublicipTags", "ListQuotas", "ListShareBandwidthTypes", "ListTenantVpcIgws", "NeutronCreateFloatingIp", "NeutronDeleteFloatingIp", "NeutronListFloatingIps", "NeutronShowFloatingIp", "NeutronUpdateFloatingIp", "RemovePublicipsFromSharedBandwidth", "ShowBandwidth", "ShowBandwidthRuleV3", "ShowInternalVpcIgw", "ShowPublicip", "ShowPublicipPool", "ShowPublicipPoolTypes", "ShowPublicipTags", "ShowPublicIpType", "ShowResourcesJobDetail", "UpdateBandwidth", "UpdateBandwidthRuleV3", "UpdatePrePaidBandwidth", "UpdatePublicip", "UpdatePublicipPool", "UpdateTenantVpcIgw"]

[lib]
name = "huawei_cloud_api_definitions_EIP"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-EIP"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
