[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchCreateDataobjectRelations = []
BatchCreateDatapanelObjects = []
BatchSearchMetricHits = []
BatchTagResources = []
BatchUntagResources = []
BatchUpdateCatalogue = []
ChangeAlert = []
ChangeAlerts = []
ChangeIncident = []
ChangeIncidents = []
ChangePlaybookInstance = []
ChangeResource = []
CopyMapping = []
CopyPlaybookVersion = []
CountResourceInstance = []
CreateAdhocQuery = []
CreateAlert = []
CreateAlertRule = []
CreateAlertRuleSimulation = []
CreateAnalysisScript = []
CreateAopWorkflow = []
CreateAopWorkflowVersion = []
CreateAopWorkflowVersionApprovel = []
CreateBatchOrderAlerts = []
CreateCatalogue = []
CreateClassifier = []
CreateCodeSegment = []
CreateCollectConfig = []
CreateCollectConfigV2 = []
CreateCollectorChannel = []
CreateCollectorChannelGroup = []
CreateCollectorChannelOperation = []
CreateCollectorConnection = []
CreateCollectorFiles = []
CreateCollectorParser = []
CreateComponentTemplate = []
CreateConfigurationApplication = []
CreateConfigurationDictionaries = []
CreateConnection = []
CreateCustomizedCheckitem = []
CreateCustomizedCompliancePackage = []
CreateDataTransformation = []
CreateDataclassType = []
CreateDataobject = []
CreateDataobjectRelation = []
CreateDataspace = []
CreateIncident = []
CreateIndicator = []
CreateLayout = []
CreateLayoutField = []
CreateLayoutWizard = []
CreateMapper = []
CreateMetric = []
CreateModule = []
CreateNote = []
CreatePipe = []
CreatePipeConsumption = []
CreatePlaybook = []
CreatePlaybookAction = []
CreatePlaybookApprove = []
CreatePlaybookRule = []
CreatePlaybookVersion = []
CreatePreProcessRules = []
CreateReport = []
CreateResourceConfig = []
CreateRetrieveScript = []
CreateRetryPolicy = []
CreateSearchAnalysis = []
CreateSearchCondition = []
CreateServiceAgency = []
CreateShipper = []
CreateShipperDelegateAuth = []
CreateSqlRender = []
CreateSqlValidation = []
CreateTable = []
CreateTableAnalysis = []
CreateWorkflowInstance = []
CreateWorkspace = []
DeleteAdhocQuery = []
DeleteAlert = []
DeleteAlertRule = []
DeleteAlerts = []
DeleteAnalysisScript = []
DeleteAopWorkflow = []
DeleteAopWorkflowVersion = []
DeleteCatalogue = []
DeleteCodeSegment = []
DeleteCollectorChannel = []
DeleteCollectorChannelGroup = []
DeleteCollectorConnection = []
DeleteCollectorParser = []
DeleteComponentTemplate = []
DeleteConfigurationDictionaries = []
DeleteConnection = []
DeleteCustomizedCheckitems = []
DeleteCustomizedCompliancePackages = []
DeleteDataclassType = []
DeleteDataobjectRelation = []
DeleteDataobjects = []
DeleteDataspace = []
full = ["BatchCreateDataobjectRelations", "BatchCreateDatapanelObjects", "BatchSearchMetricHits", "BatchTagResources", "BatchUntagResources", "BatchUpdateCatalogue", "ChangeAlert", "ChangeAlerts", "ChangeIncident", "ChangeIncidents", "ChangePlaybookInstance", "ChangeResource", "CopyMapping", "CopyPlaybookVersion", "CountResourceInstance", "CreateAdhocQuery", "CreateAlert", "CreateAlertRule", "CreateAlertRuleSimulation", "CreateAnalysisScript", "CreateAopWorkflow", "CreateAopWorkflowVersion", "CreateAopWorkflowVersionApprovel", "CreateBatchOrderAlerts", "CreateCatalogue", "CreateClassifier", "CreateCodeSegment", "CreateCollectConfig", "CreateCollectConfigV2", "CreateCollectorChannel", "CreateCollectorChannelGroup", "CreateCollectorChannelOperation", "CreateCollectorConnection", "CreateCollectorFiles", "CreateCollectorParser", "CreateComponentTemplate", "CreateConfigurationApplication", "CreateConfigurationDictionaries", "CreateConnection", "CreateCustomizedCheckitem", "CreateCustomizedCompliancePackage", "CreateDataclassType", "CreateDataobject", "CreateDataobjectRelation", "CreateDataspace", "CreateDataTransformation", "CreateIncident", "CreateIndicator", "CreateLayout", "CreateLayoutField", "CreateLayoutWizard", "CreateMapper", "CreateMetric", "CreateModule", "CreateNote", "CreatePipe", "CreatePipeConsumption", "CreatePlaybook", "CreatePlaybookAction", "CreatePlaybookApprove", "CreatePlaybookRule", "CreatePlaybookVersion", "CreatePreProcessRules", "CreateReport", "CreateResourceConfig", "CreateRetrieveScript", "CreateRetryPolicy", "CreateSearchAnalysis", "CreateSearchCondition", "CreateServiceAgency", "CreateShipper", "CreateShipperDelegateAuth", "CreateSqlRender", "CreateSqlValidation", "CreateTable", "CreateTableAnalysis", "CreateWorkflowInstance", "CreateWorkspace", "DeleteAdhocQuery", "DeleteAlert", "DeleteAlertRule", "DeleteAlerts", "DeleteAnalysisScript", "DeleteAopWorkflow", "DeleteAopWorkflowVersion", "DeleteCatalogue", "DeleteCodeSegment", "DeleteCollectorChannel", "DeleteCollectorChannelGroup", "DeleteCollectorConnection", "DeleteCollectorParser", "DeleteComponentTemplate", "DeleteConfigurationDictionaries", "DeleteConnection", "DeleteCustomizedCheckitems", "DeleteCustomizedCompliancePackages", "DeleteDataclassType", "DeleteDataobjectRelation", "DeleteDataobjects", "DeleteDataspace"]

[lib]
name = "huawei_cloud_api_definitions_SecMaster"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-SecMaster"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
