[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
ApplyHttpPolicy = []
CreateDomain = []
CreateHttpAccessControlRule = []
CreateHttpBlockTrustIpRule = []
CreateHttpCcRule = []
CreateHttpGeoIpRule = []
CreateHttpIgnoreRule = []
CreateHttpIpGroup = []
CreateHttpPolicy = []
CreateHttpPunishmentRule = []
CreateHttpReferenceTable = []
DeleteDomain = []
DeleteHttpAccessControlRule = []
DeleteHttpBlockTrustIpRule = []
DeleteHttpCcRule = []
DeleteHttpGeoIpRule = []
DeleteHttpIgnoreRule = []
DeleteHttpIpGroup = []
DeleteHttpPolicy = []
DeleteHttpPunishmentRule = []
DeleteHttpReferenceTable = []
DownloadDdosAttackLogs = []
ResetHttpIgnoreRule = []
ShowDdosAttackLogs = []
ShowDdosAttackTimelineStats = []
ShowDomainDetail = []
ShowDomains = []
ShowHttpAccessControlRule = []
ShowHttpAccessControlRules = []
ShowHttpAttackDistributionStats = []
ShowHttpAttackTimelineStats = []
ShowHttpAttackTopStats = []
ShowHttpBlockTrustIpRule = []
ShowHttpBlockTrustIpRules = []
ShowHttpCcRule = []
ShowHttpCcRules = []
ShowHttpGeoIpRule = []
ShowHttpGeoIpRules = []
ShowHttpIgnoreRule = []
ShowHttpIgnoreRules = []
ShowHttpIpGroup = []
ShowHttpIpGroups = []
ShowHttpOverviews = []
ShowHttpPolicies = []
ShowHttpPolicy = []
ShowHttpPunishmentRule = []
ShowHttpPunishmentRules = []
ShowHttpReferenceTables = []
ShowHttpStatistics = []
UpdateDomain = []
UpdateHttpAccessControlRule = []
UpdateHttpBlockTrustIpRule = []
UpdateHttpCcRule = []
UpdateHttpGeoIpRule = []
UpdateHttpIgnoreRule = []
UpdateHttpIpGroup = []
UpdateHttpPolicy = []
UpdateHttpPolicyRuleStatus = []
UpdateHttpPunishmentRule = []
UpdateHttpReferenceTable = []
full = ["ApplyHttpPolicy", "CreateDomain", "CreateHttpAccessControlRule", "CreateHttpBlockTrustIpRule", "CreateHttpCcRule", "CreateHttpGeoIpRule", "CreateHttpIgnoreRule", "CreateHttpIpGroup", "CreateHttpPolicy", "CreateHttpPunishmentRule", "CreateHttpReferenceTable", "DeleteDomain", "DeleteHttpAccessControlRule", "DeleteHttpBlockTrustIpRule", "DeleteHttpCcRule", "DeleteHttpGeoIpRule", "DeleteHttpIgnoreRule", "DeleteHttpIpGroup", "DeleteHttpPolicy", "DeleteHttpPunishmentRule", "DeleteHttpReferenceTable", "DownloadDdosAttackLogs", "ResetHttpIgnoreRule", "ShowDdosAttackLogs", "ShowDdosAttackTimelineStats", "ShowDomainDetail", "ShowDomains", "ShowHttpAccessControlRule", "ShowHttpAccessControlRules", "ShowHttpAttackDistributionStats", "ShowHttpAttackTimelineStats", "ShowHttpAttackTopStats", "ShowHttpBlockTrustIpRule", "ShowHttpBlockTrustIpRules", "ShowHttpCcRule", "ShowHttpCcRules", "ShowHttpGeoIpRule", "ShowHttpGeoIpRules", "ShowHttpIgnoreRule", "ShowHttpIgnoreRules", "ShowHttpIpGroup", "ShowHttpIpGroups", "ShowHttpOverviews", "ShowHttpPolicies", "ShowHttpPolicy", "ShowHttpPunishmentRule", "ShowHttpPunishmentRules", "ShowHttpReferenceTables", "ShowHttpStatistics", "UpdateDomain", "UpdateHttpAccessControlRule", "UpdateHttpBlockTrustIpRule", "UpdateHttpCcRule", "UpdateHttpGeoIpRule", "UpdateHttpIgnoreRule", "UpdateHttpIpGroup", "UpdateHttpPolicy", "UpdateHttpPolicyRuleStatus", "UpdateHttpPunishmentRule", "UpdateHttpReferenceTable"]

[lib]
name = "huawei_cloud_api_definitions_EdgeSec"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-EdgeSec"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
