[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchCreateOrDeleteKafkaTag = []
BatchDeleteGroup = []
BatchDeleteInstanceTopic = []
BatchDeleteInstanceUsers = []
BatchDeleteMessageDiagnosisReports = []
BatchRestartOrDeleteInstances = []
CloseKafkaManager = []
CreateConnector = []
CreateConnectorTask = []
CreateInstanceTopic = []
CreateInstanceUser = []
CreateKafkaConsumerGroup = []
CreateKafkaReassignmentTask = []
CreateKafkaRebalanceLogTask = []
CreateKafkaTopicQuota = []
CreateKafkaUserClientQuotaTask = []
CreateMessageDiagnosisTask = []
CreatePostPaidKafkaInstance = []
CreateReassignmentTask = []
DeleteBackgroundTask = []
DeleteConnector = []
DeleteConnectorTask = []
DeleteConsumerGroupOffsets = []
DeleteInstance = []
DeleteInstanceConsumerGroup = []
DeleteKafkaMessage = []
DeleteKafkaTopicMessages = []
DeleteKafkaTopicQuota = []
DeleteKafkaUserClientQuotaTask = []
DeleteScheduledTask = []
ListAvailableZones = []
ListBackgroundTasks = []
ListConfigFeatures = []
ListConnectorTasks = []
ListEngineProducts = []
ListInstanceConsumerGroup = []
ListInstanceConsumerGroupMembers = []
ListInstanceConsumerGroupMessageOffset = []
ListInstanceConsumerGroupTopics = []
ListInstanceConsumerGroups = []
ListInstanceTopics = []
ListInstances = []
ListMessageDiagnosisReports = []
ListObsBuckets = []
ListScheduledTasks = []
ListTopicPartitions = []
ListTopicProducers = []
ModifyConnectorTask = []
ModifyInstanceConfigs = []
ModifyKafkaPublicIpAccessSwitch = []
ModifyKafkaTopicQuota = []
ModifyRecyclePolicy = []
PauseConnectorTask = []
ResetManagerPassword = []
ResetMessageOffsetWithEngine = []
ResetPassword = []
ResetUserPasswrod = []
ResizeEngineInstance = []
RestartConnectorTask = []
RestartManager = []
RestoreRecycleInstance = []
ResumeConnectorTask = []
SendKafkaMessage = []
ShowBackgroundTask = []
ShowBackgroundTaskProgress = []
ShowCesHierarchy = []
ShowCluster = []
ShowConnectorResourceInfo = []
ShowConnectorTask = []
ShowCoordinators = []
ShowDiagnosisPreCheck = []
ShowEngineInstanceExtendProductInfo = []
ShowGroups = []
ShowInstance = []
ShowInstanceConfigs = []
ShowInstanceMessages = []
ShowInstanceUsers = []
ShowKafkaCluster = []
ShowKafkaProductCores = []
ShowKafkaProjectTags = []
ShowKafkaRebalanceLog = []
ShowKafkaScalePreCheckInfo = []
ShowKafkaTags = []
ShowKafkaTopicDetail = []
ShowKafkaTopicPartitionDiskusage = []
ShowKafkaTopicQuota = []
ShowKafkaUserClientQuota = []
ShowMaintainWindows = []
ShowMessageDiagnosisReport = []
ShowMessages = []
ShowPartitionBeginningMessage = []
ShowPartitionEndMessage = []
ShowPartitionMessage = []
ShowRecycleInstances = []
ShowSpecConvertProduct = []
ShowTopicAccessPolicy = []
ShowUpgradeInstanceVersion = []
ShowVolumeExpandConfig = []
StopKafkaRebalanceLogTask = []
UpdateInstance = []
full = ["BatchCreateOrDeleteKafkaTag", "BatchDeleteGroup", "BatchDeleteInstanceTopic", "BatchDeleteInstanceUsers", "BatchDeleteMessageDiagnosisReports", "BatchRestartOrDeleteInstances", "CloseKafkaManager", "CreateConnector", "CreateConnectorTask", "CreateInstanceTopic", "CreateInstanceUser", "CreateKafkaConsumerGroup", "CreateKafkaReassignmentTask", "CreateKafkaRebalanceLogTask", "CreateKafkaTopicQuota", "CreateKafkaUserClientQuotaTask", "CreateMessageDiagnosisTask", "CreatePostPaidKafkaInstance", "CreateReassignmentTask", "DeleteBackgroundTask", "DeleteConnector", "DeleteConnectorTask", "DeleteConsumerGroupOffsets", "DeleteInstance", "DeleteInstanceConsumerGroup", "DeleteKafkaMessage", "DeleteKafkaTopicMessages", "DeleteKafkaTopicQuota", "DeleteKafkaUserClientQuotaTask", "DeleteScheduledTask", "ListAvailableZones", "ListBackgroundTasks", "ListConfigFeatures", "ListConnectorTasks", "ListEngineProducts", "ListInstanceConsumerGroup", "ListInstanceConsumerGroupMembers", "ListInstanceConsumerGroupMessageOffset", "ListInstanceConsumerGroups", "ListInstanceConsumerGroupTopics", "ListInstances", "ListInstanceTopics", "ListMessageDiagnosisReports", "ListObsBuckets", "ListScheduledTasks", "ListTopicPartitions", "ListTopicProducers", "ModifyConnectorTask", "ModifyInstanceConfigs", "ModifyKafkaPublicIpAccessSwitch", "ModifyKafkaTopicQuota", "ModifyRecyclePolicy", "PauseConnectorTask", "ResetManagerPassword", "ResetMessageOffsetWithEngine", "ResetPassword", "ResetUserPasswrod", "ResizeEngineInstance", "RestartConnectorTask", "RestartManager", "RestoreRecycleInstance", "ResumeConnectorTask", "SendKafkaMessage", "ShowBackgroundTask", "ShowBackgroundTaskProgress", "ShowCesHierarchy", "ShowCluster", "ShowConnectorResourceInfo", "ShowConnectorTask", "ShowCoordinators", "ShowDiagnosisPreCheck", "ShowEngineInstanceExtendProductInfo", "ShowGroups", "ShowInstance", "ShowInstanceConfigs", "ShowInstanceMessages", "ShowInstanceUsers", "ShowKafkaCluster", "ShowKafkaProductCores", "ShowKafkaProjectTags", "ShowKafkaRebalanceLog", "ShowKafkaScalePreCheckInfo", "ShowKafkaTags", "ShowKafkaTopicDetail", "ShowKafkaTopicPartitionDiskusage", "ShowKafkaTopicQuota", "ShowKafkaUserClientQuota", "ShowMaintainWindows", "ShowMessageDiagnosisReport", "ShowMessages", "ShowPartitionBeginningMessage", "ShowPartitionEndMessage", "ShowPartitionMessage", "ShowRecycleInstances", "ShowSpecConvertProduct", "ShowTopicAccessPolicy", "ShowUpgradeInstanceVersion", "ShowVolumeExpandConfig", "StopKafkaRebalanceLogTask", "UpdateInstance"]

[lib]
name = "huawei_cloud_api_definitions_Kafka"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-Kafka"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
