[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchDeleteNodes = []
BindEip = []
CancelMigration = []
ChangeDatabaseVersion = []
ChangeStrategy = []
CheckDataNodeConnectionV0V3 = []
CheckMigrateLogicDb = []
CheckPreliminaryResults = []
CleanMigration = []
CompareParameterGroups = []
CopyParameterGroup = []
CreateDatabase = []
CreateDdmConfigurations = []
CreateDdmDatabase = []
CreateDdmInstance = []
CreateGroup = []
CreateInstance = []
CreateUsers = []
DeleteBackup = []
DeleteConfiguration = []
DeleteDatabase = []
DeleteDdmDatabase = []
DeleteDdmInstance = []
DeleteGroup = []
DeleteInstance = []
DeleteNodes = []
DeleteUser = []
DownloadSchemaMetadata = []
ExecuteKillLogicalProcesses = []
ExecuteKillPhysicalProcesses = []
ExpandDdmInstanceNodes = []
ExpandInstanceNodes = []
ListApiVersion = []
ListAvailableRds = []
ListAvailableRdsForMigrate = []
ListAvailableRdsList = []
ListBackups = []
ListDatabaseAvailableVersions = []
ListDatabases = []
ListDdmConfigurations = []
ListDdmEngines = []
ListDdmFlavors = []
ListEngines = []
ListFlavors = []
ListGroup = []
ListInstances = []
ListInstancesAppliedParameterGroupV0V3 = []
ListNodes = []
ListParameterGroupApplyHistoryV0V3 = []
ListReadWriteRatio = []
ListSlowLog = []
ListSlowLogs = []
ListTasks = []
ListUsers = []
MigrateLogicDb = []
MigrateResults = []
ModifyConfiguration = []
ModifyEip = []
RebuildConfig = []
ResetAdministrator = []
ResetParameterGroup = []
ResetUserPassword = []
ResizeFlavor = []
RestartDdmInstance = []
RestartInstance = []
RestartNode = []
Restore2Exist = []
RestoreMetadata = []
RetryMigration = []
RollBackDatabaseVersion = []
RollbackMigration = []
ShowAvalibleDdms = []
ShowAvalibleRds = []
ShowAvalibleTime = []
ShowBackup = []
ShowConfiguration = []
ShowDatabase = []
ShowDdmDetail = []
ShowDdmJobResult = []
ShowDdmNodeDetail = []
ShowInstance = []
ShowInstanceDatabase = []
ShowInstanceParam = []
ShowLogicalProcesses = []
ShowNode = []
ShowPhysicalProcesses = []
ShowProcessesAuditLog = []
ShowPublicIp = []
ShowRelatedDns = []
ShowRiskInfo = []
ShrinkInstanceNodes = []
SwitchRoute = []
SwitchSsl = []
SyncDnInformation = []
UnbindEip = []
UpdateDatabaseInfo = []
UpdateInstanceName = []
UpdateInstanceParam = []
UpdateInstancePort = []
UpdateInstanceSecurityGroup = []
full = ["BatchDeleteNodes", "BindEip", "CancelMigration", "ChangeDatabaseVersion", "ChangeStrategy", "CheckDataNodeConnectionV0V3", "CheckMigrateLogicDb", "CheckPreliminaryResults", "CleanMigration", "CompareParameterGroups", "CopyParameterGroup", "CreateDatabase", "CreateDdmConfigurations", "CreateDdmDatabase", "CreateDdmInstance", "CreateGroup", "CreateInstance", "CreateUsers", "DeleteBackup", "DeleteConfiguration", "DeleteDatabase", "DeleteDdmDatabase", "DeleteDdmInstance", "DeleteGroup", "DeleteInstance", "DeleteNodes", "DeleteUser", "DownloadSchemaMetadata", "ExecuteKillLogicalProcesses", "ExecuteKillPhysicalProcesses", "ExpandDdmInstanceNodes", "ExpandInstanceNodes", "ListApiVersion", "ListAvailableRds", "ListAvailableRdsForMigrate", "ListAvailableRdsList", "ListBackups", "ListDatabaseAvailableVersions", "ListDatabases", "ListDdmConfigurations", "ListDdmEngines", "ListDdmFlavors", "ListEngines", "ListFlavors", "ListGroup", "ListInstances", "ListInstancesAppliedParameterGroupV0V3", "ListNodes", "ListParameterGroupApplyHistoryV0V3", "ListReadWriteRatio", "ListSlowLog", "ListSlowLogs", "ListTasks", "ListUsers", "MigrateLogicDb", "MigrateResults", "ModifyConfiguration", "ModifyEip", "RebuildConfig", "ResetAdministrator", "ResetParameterGroup", "ResetUserPassword", "ResizeFlavor", "RestartDdmInstance", "RestartInstance", "RestartNode", "Restore2Exist", "RestoreMetadata", "RetryMigration", "RollBackDatabaseVersion", "RollbackMigration", "ShowAvalibleDdms", "ShowAvalibleRds", "ShowAvalibleTime", "ShowBackup", "ShowConfiguration", "ShowDatabase", "ShowDdmDetail", "ShowDdmJobResult", "ShowDdmNodeDetail", "ShowInstance", "ShowInstanceDatabase", "ShowInstanceParam", "ShowLogicalProcesses", "ShowNode", "ShowPhysicalProcesses", "ShowProcessesAuditLog", "ShowPublicIp", "ShowRelatedDns", "ShowRiskInfo", "ShrinkInstanceNodes", "SwitchRoute", "SwitchSsl", "SyncDnInformation", "UnbindEip", "UpdateDatabaseInfo", "UpdateInstanceName", "UpdateInstanceParam", "UpdateInstancePort", "UpdateInstanceSecurityGroup"]

[lib]
name = "huawei_cloud_api_definitions_DDM"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DDM"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
