[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
CancelMigration = []
ChangeDatabaseVersion = []
ChangeStrategy = []
CheckMigrateLogicDb = []
CheckPreliminaryResults = []
CleanMigration = []
CreateDatabase = []
CreateDdmConfigurations = []
CreateDdmDatabase = []
CreateGroup = []
CreateInstance = []
CreateUsers = []
DeleteBackup = []
DeleteConfiguration = []
DeleteDatabase = []
DeleteDdmDatabase = []
DeleteDdmInstance = []
DeleteInstance = []
DeleteUser = []
DownloadSchemaMetadata = []
ExecuteKillLogicalProcesses = []
ExecuteKillPhysicalProcesses = []
ExpandDdmInstanceNodes = []
ExpandInstanceNodes = []
ListApiVersion = []
ListAvailableRds = []
ListAvailableRdsForMigrate = []
ListAvailableRdsList = []
ListBackups = []
ListDatabaseAvailableVersions = []
ListDatabases = []
ListDdmConfigurations = []
ListDdmEngines = []
ListDdmFlavors = []
ListEngines = []
ListFlavors = []
ListGroup = []
ListInstances = []
ListNodes = []
ListReadWriteRatio = []
ListSlowLog = []
ListSlowLogs = []
ListUsers = []
MigrateLogicDb = []
MigrateResults = []
ModifyConfiguration = []
RebuildConfig = []
ResetAdministrator = []
ResetUserPassword = []
ResizeFlavor = []
RestartInstance = []
Restore2Exist = []
RestoreMetadata = []
RetryMigration = []
RollBackDatabaseVersion = []
RollbackMigration = []
ShowAvalibleDdms = []
ShowAvalibleRds = []
ShowAvalibleTime = []
ShowBackup = []
ShowConfiguration = []
ShowDatabase = []
ShowDdmJobResult = []
ShowInstance = []
ShowInstanceDatabase = []
ShowInstanceParam = []
ShowLogicalProcesses = []
ShowNode = []
ShowPhysicalProcesses = []
ShowProcessesAuditLog = []
ShowRelatedDns = []
ShowRiskInfo = []
ShrinkInstanceNodes = []
SwitchRoute = []
SwitchSsl = []
UpdateDatabaseInfo = []
UpdateInstanceName = []
UpdateInstanceParam = []
UpdateInstancePort = []
UpdateInstanceSecurityGroup = []
UpdateReadAndWriteStrategy = []
UpdateUser = []
UploadSchemaMetadata = []
ValidateWeakPassword = []
full = ["CancelMigration", "ChangeDatabaseVersion", "ChangeStrategy", "CheckMigrateLogicDb", "CheckPreliminaryResults", "CleanMigration", "CreateDatabase", "CreateDdmConfigurations", "CreateDdmDatabase", "CreateGroup", "CreateInstance", "CreateUsers", "DeleteBackup", "DeleteConfiguration", "DeleteDatabase", "DeleteDdmDatabase", "DeleteDdmInstance", "DeleteInstance", "DeleteUser", "DownloadSchemaMetadata", "ExecuteKillLogicalProcesses", "ExecuteKillPhysicalProcesses", "ExpandDdmInstanceNodes", "ExpandInstanceNodes", "ListApiVersion", "ListAvailableRds", "ListAvailableRdsForMigrate", "ListAvailableRdsList", "ListBackups", "ListDatabaseAvailableVersions", "ListDatabases", "ListDdmConfigurations", "ListDdmEngines", "ListDdmFlavors", "ListEngines", "ListFlavors", "ListGroup", "ListInstances", "ListNodes", "ListReadWriteRatio", "ListSlowLog", "ListSlowLogs", "ListUsers", "MigrateLogicDb", "MigrateResults", "ModifyConfiguration", "RebuildConfig", "ResetAdministrator", "ResetUserPassword", "ResizeFlavor", "RestartInstance", "Restore2Exist", "RestoreMetadata", "RetryMigration", "RollBackDatabaseVersion", "RollbackMigration", "ShowAvalibleDdms", "ShowAvalibleRds", "ShowAvalibleTime", "ShowBackup", "ShowConfiguration", "ShowDatabase", "ShowDdmJobResult", "ShowInstance", "ShowInstanceDatabase", "ShowInstanceParam", "ShowLogicalProcesses", "ShowNode", "ShowPhysicalProcesses", "ShowProcessesAuditLog", "ShowRelatedDns", "ShowRiskInfo", "ShrinkInstanceNodes", "SwitchRoute", "SwitchSsl", "UpdateDatabaseInfo", "UpdateInstanceName", "UpdateInstanceParam", "UpdateInstancePort", "UpdateInstanceSecurityGroup", "UpdateReadAndWriteStrategy", "UpdateUser", "UploadSchemaMetadata", "ValidateWeakPassword"]

[lib]
name = "huawei_cloud_api_definitions_DDM"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DDM"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
