[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchDeleteNodes = []
BatchModifyReadWriteStrategy = []
BindEip = []
CancelMigration = []
ChangeDatabaseVersion = []
ChangeStrategy = []
CheckDataNodeConnection = []
CheckMigrateLogicDb = []
CheckPreliminaryResults = []
CleanMigration = []
CompareParameterGroups = []
CopyConfiguration = []
CreateDatabase = []
CreateDdmConfigurations = []
CreateDdmDatabase = []
CreateDdmInstance = []
CreateGroup = []
CreateInstance = []
CreateUsers = []
DeleteBackup = []
DeleteConfiguration = []
DeleteDatabase = []
DeleteDdmDatabase = []
DeleteDdmInstance = []
DeleteGroup = []
DeleteInstance = []
DeleteNodes = []
DeleteUser = []
DownloadSchemaMetadata = []
ExecuteKillLogicalProcesses = []
ExecuteKillPhysicalProcesses = []
ExpandDdmInstanceNodes = []
ExpandInstanceNodes = []
ListApiVersion = []
ListAvailableRds = []
ListAvailableRdsForMigrate = []
ListAvailableRdsList = []
ListBackups = []
ListConfigurationApplyHistories = []
ListDatabaseAvailableVersions = []
ListDatabases = []
ListDdmConfigurations = []
ListDdmEngines = []
ListDdmFlavors = []
ListDdms = []
ListEngines = []
ListFlavors = []
ListGroup = []
ListInstances = []
ListInstancesConfigurations = []
ListNodes = []
ListReadWriteRatio = []
ListSlowLog = []
ListSlowLogAnalysis = []
ListSlowLogs = []
ListSqlBlack = []
ListTasks = []
ListUsers = []
MigrateLogicDb = []
MigrateResults = []
ModifyConfiguration = []
ModifyEip = []
ModifySqlBlackList = []
RebuildConfig = []
ResetAdministrator = []
ResetParameterGroup = []
ResetUserPassword = []
ResizeFlavor = []
RestartDdmInstance = []
RestartInstance = []
RestartNode = []
Restore2Exist = []
RestoreMetadata = []
RetryMigration = []
RollBackDatabaseVersion = []
RollbackMigration = []
ShowAvalibleDdms = []
ShowAvalibleRds = []
ShowAvalibleTime = []
ShowBackup = []
ShowConfiguration = []
ShowDatabase = []
ShowDdmDetail = []
ShowDdmJobResult = []
ShowDdmNodeDetail = []
ShowInstance = []
ShowInstanceDatabase = []
ShowInstanceParam = []
ShowIpGroup = []
ShowLogicalProcesses = []
ShowMigrationLog = []
ShowNode = []
ShowPhysicalProcesses = []
ShowProcessesAuditLog = []
ShowPublicIp = []
ShowRelatedDns = []
ShowRiskInfo = []
ShrinkInstanceNodes = []
SwitchIpGroup = []
SwitchRoute = []
full = ["BatchDeleteNodes", "BatchModifyReadWriteStrategy", "BindEip", "CancelMigration", "ChangeDatabaseVersion", "ChangeStrategy", "CheckDataNodeConnection", "CheckMigrateLogicDb", "CheckPreliminaryResults", "CleanMigration", "CompareParameterGroups", "CopyConfiguration", "CreateDatabase", "CreateDdmConfigurations", "CreateDdmDatabase", "CreateDdmInstance", "CreateGroup", "CreateInstance", "CreateUsers", "DeleteBackup", "DeleteConfiguration", "DeleteDatabase", "DeleteDdmDatabase", "DeleteDdmInstance", "DeleteGroup", "DeleteInstance", "DeleteNodes", "DeleteUser", "DownloadSchemaMetadata", "ExecuteKillLogicalProcesses", "ExecuteKillPhysicalProcesses", "ExpandDdmInstanceNodes", "ExpandInstanceNodes", "ListApiVersion", "ListAvailableRds", "ListAvailableRdsForMigrate", "ListAvailableRdsList", "ListBackups", "ListConfigurationApplyHistories", "ListDatabaseAvailableVersions", "ListDatabases", "ListDdmConfigurations", "ListDdmEngines", "ListDdmFlavors", "ListDdms", "ListEngines", "ListFlavors", "ListGroup", "ListInstances", "ListInstancesConfigurations", "ListNodes", "ListReadWriteRatio", "ListSlowLog", "ListSlowLogAnalysis", "ListSlowLogs", "ListSqlBlack", "ListTasks", "ListUsers", "MigrateLogicDb", "MigrateResults", "ModifyConfiguration", "ModifyEip", "ModifySqlBlackList", "RebuildConfig", "ResetAdministrator", "ResetParameterGroup", "ResetUserPassword", "ResizeFlavor", "RestartDdmInstance", "RestartInstance", "RestartNode", "Restore2Exist", "RestoreMetadata", "RetryMigration", "RollBackDatabaseVersion", "RollbackMigration", "ShowAvalibleDdms", "ShowAvalibleRds", "ShowAvalibleTime", "ShowBackup", "ShowConfiguration", "ShowDatabase", "ShowDdmDetail", "ShowDdmJobResult", "ShowDdmNodeDetail", "ShowInstance", "ShowInstanceDatabase", "ShowInstanceParam", "ShowIpGroup", "ShowLogicalProcesses", "ShowMigrationLog", "ShowNode", "ShowPhysicalProcesses", "ShowProcessesAuditLog", "ShowPublicIp", "ShowRelatedDns", "ShowRiskInfo", "ShrinkInstanceNodes", "SwitchIpGroup", "SwitchRoute"]

[lib]
name = "huawei_cloud_api_definitions_DDM"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-DDM"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
