[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
AddActionRule = []
AddAlarmRule = []
AddEvent2alarmRule = []
AddMetricData = []
AddMuteRules = []
AddOrUpdateMetricOrEventAlarmRule = []
AddOrUpdateServiceDiscoveryRules = []
BatchImportAgent = []
BatchUpdateAgent = []
BatchUpdateAlarmRule = []
CountEvents = []
CreateApp = []
CreateComponent = []
CreateEnv = []
CreateNotificationTemplate = []
CreatePromInstance = []
CreateRecordingRule = []
CreateSubApp = []
CreateWorkflow = []
DeleteActionRule = []
DeleteAlarmRule = []
DeleteAlarmRuleTemplate = []
DeleteAlarmRules = []
DeleteApp = []
DeleteComponent = []
DeleteDashboard = []
DeleteDashboardsFolder = []
DeleteEnv = []
DeleteEvent2alarmRule = []
DeleteMetricOrEventAlarmRule = []
DeleteMuteRules = []
DeleteNotificationTemplate = []
DeletePromInstance = []
DeleteSubApp = []
DeleteserviceDiscoveryRules = []
ExecuteWorkflow = []
ListAccessCode = []
ListActionRule = []
ListAgents = []
ListAlarmRule = []
ListAlarmRuleTemplate = []
ListAllJobByName = []
ListAllScriptByName = []
ListAllVersionByVersionId = []
ListDashBoards = []
ListDashboardsFolder = []
ListEvent2alarmRule = []
ListEvents = []
ListInstantQueryAomPromGet = []
ListInstantQueryAomPromPost = []
ListLabelValuesAomPromGet = []
ListLabelsAomPromGet = []
ListLabelsAomPromPost = []
ListLogItems = []
ListMetadataAomPromGet = []
ListMetricItems = []
ListMetricOrEventAlarmRule = []
ListMuteRule = []
ListNotificationTemplateByName = []
ListNotificationTemplates = []
ListNotifiedHistories = []
ListPermissions = []
ListPromInstance = []
ListRangeQueryAomPromGet = []
ListRangeQueryAomPromPost = []
ListResourceUnderNode = []
ListSample = []
ListSeries = []
ListServiceDiscoveryRules = []
ListTemplateByJobId = []
ListWorkflow = []
ListWorkflowExecutions = []
PushEvents = []
SearchTemplateById = []
SearchWorkflowExecutionDetail = []
ShowActionRule = []
ShowAgentInfos = []
ShowAlarmRule = []
ShowApp = []
ShowAppByName = []
ShowComponent = []
ShowComponentByName = []
ShowDashBoard = []
ShowEnv = []
ShowEnvByName = []
ShowMetricsData = []
StartPausingWorkflowExecutions = []
StopExecution = []
UpdateActionRule = []
UpdateAlarmRule = []
UpdateApp = []
UpdateComponent = []
UpdateEnv = []
UpdateEventRule = []
UpdateMuteRule = []
UpdateNotificationTemplate = []
UpdatePromInstance = []
UpdateSubApp = []
UpdateWorkflowTriggerStatus = []
full = ["AddActionRule", "AddAlarmRule", "AddEvent2alarmRule", "AddMetricData", "AddMuteRules", "AddOrUpdateMetricOrEventAlarmRule", "AddOrUpdateServiceDiscoveryRules", "BatchImportAgent", "BatchUpdateAgent", "BatchUpdateAlarmRule", "CountEvents", "CreateApp", "CreateComponent", "CreateEnv", "CreateNotificationTemplate", "CreatePromInstance", "CreateRecordingRule", "CreateSubApp", "CreateWorkflow", "DeleteActionRule", "DeleteAlarmRule", "DeleteAlarmRules", "DeleteAlarmRuleTemplate", "DeleteApp", "DeleteComponent", "DeleteDashboard", "DeleteDashboardsFolder", "DeleteEnv", "DeleteEvent2alarmRule", "DeleteMetricOrEventAlarmRule", "DeleteMuteRules", "DeleteNotificationTemplate", "DeletePromInstance", "DeleteserviceDiscoveryRules", "DeleteSubApp", "ExecuteWorkflow", "ListAccessCode", "ListActionRule", "ListAgents", "ListAlarmRule", "ListAlarmRuleTemplate", "ListAllJobByName", "ListAllScriptByName", "ListAllVersionByVersionId", "ListDashBoards", "ListDashboardsFolder", "ListEvent2alarmRule", "ListEvents", "ListInstantQueryAomPromGet", "ListInstantQueryAomPromPost", "ListLabelsAomPromGet", "ListLabelsAomPromPost", "ListLabelValuesAomPromGet", "ListLogItems", "ListMetadataAomPromGet", "ListMetricItems", "ListMetricOrEventAlarmRule", "ListMuteRule", "ListNotificationTemplateByName", "ListNotificationTemplates", "ListNotifiedHistories", "ListPermissions", "ListPromInstance", "ListRangeQueryAomPromGet", "ListRangeQueryAomPromPost", "ListResourceUnderNode", "ListSample", "ListSeries", "ListServiceDiscoveryRules", "ListTemplateByJobId", "ListWorkflow", "ListWorkflowExecutions", "PushEvents", "SearchTemplateById", "SearchWorkflowExecutionDetail", "ShowActionRule", "ShowAgentInfos", "ShowAlarmRule", "ShowApp", "ShowAppByName", "ShowComponent", "ShowComponentByName", "ShowDashBoard", "ShowEnv", "ShowEnvByName", "ShowMetricsData", "StartPausingWorkflowExecutions", "StopExecution", "UpdateActionRule", "UpdateAlarmRule", "UpdateApp", "UpdateComponent", "UpdateEnv", "UpdateEventRule", "UpdateMuteRule", "UpdateNotificationTemplate", "UpdatePromInstance", "UpdateSubApp", "UpdateWorkflowTriggerStatus"]

[lib]
name = "huawei_cloud_api_definitions_AOM"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-AOM"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
