[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchCreateDeleteNatGatewayTag = []
BatchCreateDeletePrivateNatTags = []
BatchCreateDeleteTransitIpTags = []
BatchCreateDeleteTransitSubnetTags = []
BatchCreateNatGatewayDnatRules = []
CreateNatGateway = []
CreateNatGatewayDnatRule = []
CreateNatGatewaySnatRule = []
CreateNatGatewayTag = []
CreatePrivateDnat = []
CreatePrivateNat = []
CreatePrivateNatTag = []
CreatePrivateSnat = []
CreateTransitIp = []
CreateTransitIpTag = []
CreateTransitSubnet = []
CreateTransitSubnetTag = []
DeleteNatGateway = []
DeleteNatGatewayDnatRule = []
DeleteNatGatewaySnatRule = []
DeleteNatGatewayTag = []
DeletePrivateDnat = []
DeletePrivateNat = []
DeletePrivateNatTag = []
DeletePrivateSnat = []
DeleteTransitIp = []
DeleteTransitIpTag = []
DeleteTransitSubnet = []
DeleteTransitSubnetTag = []
ListNatGatewayByTag = []
ListNatGatewayDnatRules = []
ListNatGatewaySnatRules = []
ListNatGatewaySpecs = []
ListNatGatewayTag = []
ListNatGateways = []
ListPrivateDnats = []
ListPrivateNatTags = []
ListPrivateNats = []
ListPrivateNatsByTags = []
ListPrivateSnats = []
ListSpecs = []
ListTransitIpTags = []
ListTransitIps = []
ListTransitIpsByTags = []
ListTransitSubnet = []
ListTransitSubnetTags = []
ListTransitSubnetsByTags = []
ShowNatGateway = []
ShowNatGatewayDnatRule = []
ShowNatGatewaySnatRule = []
ShowNatGatewayTag = []
ShowPrivateDnat = []
ShowPrivateNat = []
ShowPrivateNatTags = []
ShowPrivateSnat = []
ShowTransitIp = []
ShowTransitIpTags = []
ShowTransitSubnet = []
ShowTransitSubnetTags = []
UpdateNatGateway = []
UpdateNatGatewayDnatRule = []
UpdateNatGatewaySnatRule = []
UpdateNatGatewayToPeriod = []
UpdatePrivateDnat = []
UpdatePrivateNat = []
UpdatePrivateSnat = []
UpdateTransitSubnet = []
full = ["BatchCreateDeleteNatGatewayTag", "BatchCreateDeletePrivateNatTags", "BatchCreateDeleteTransitIpTags", "BatchCreateDeleteTransitSubnetTags", "BatchCreateNatGatewayDnatRules", "CreateNatGateway", "CreateNatGatewayDnatRule", "CreateNatGatewaySnatRule", "CreateNatGatewayTag", "CreatePrivateDnat", "CreatePrivateNat", "CreatePrivateNatTag", "CreatePrivateSnat", "CreateTransitIp", "CreateTransitIpTag", "CreateTransitSubnet", "CreateTransitSubnetTag", "DeleteNatGateway", "DeleteNatGatewayDnatRule", "DeleteNatGatewaySnatRule", "DeleteNatGatewayTag", "DeletePrivateDnat", "DeletePrivateNat", "DeletePrivateNatTag", "DeletePrivateSnat", "DeleteTransitIp", "DeleteTransitIpTag", "DeleteTransitSubnet", "DeleteTransitSubnetTag", "ListNatGatewayByTag", "ListNatGatewayDnatRules", "ListNatGateways", "ListNatGatewaySnatRules", "ListNatGatewaySpecs", "ListNatGatewayTag", "ListPrivateDnats", "ListPrivateNats", "ListPrivateNatsByTags", "ListPrivateNatTags", "ListPrivateSnats", "ListSpecs", "ListTransitIps", "ListTransitIpsByTags", "ListTransitIpTags", "ListTransitSubnet", "ListTransitSubnetsByTags", "ListTransitSubnetTags", "ShowNatGateway", "ShowNatGatewayDnatRule", "ShowNatGatewaySnatRule", "ShowNatGatewayTag", "ShowPrivateDnat", "ShowPrivateNat", "ShowPrivateNatTags", "ShowPrivateSnat", "ShowTransitIp", "ShowTransitIpTags", "ShowTransitSubnet", "ShowTransitSubnetTags", "UpdateNatGateway", "UpdateNatGatewayDnatRule", "UpdateNatGatewaySnatRule", "UpdateNatGatewayToPeriod", "UpdatePrivateDnat", "UpdatePrivateNat", "UpdatePrivateSnat", "UpdateTransitSubnet"]

[lib]
name = "huawei_cloud_api_definitions_NAT"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-NAT"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
