[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchDeleteTrashes = []
BatchRestoreRepo = []
CreateArtifactory = []
CreateAttention = []
CreateDockerRepositories = []
CreateMavenRepo = []
CreateProjectRelatedRepository = []
DeleteArtifactFile = []
DeleteCompletelyUpdateFileState = []
DeleteRepository = []
ListAllRepositories = []
ListArtifactoryComponent = []
ListArtifactoryStorageStatistic = []
ListAttentions = []
ListCapacityMessageSetting = []
ListChildProxyRepositoriesList = []
ListDomainIpConfig = []
ListFileBuildArchives = []
ListFiles = []
ListLatestVersionFiles = []
ListMavenList = []
ListMavenUser = []
ListNetProxy = []
ListProjectRolePermissions = []
ListProjectUsers = []
ListSecGuardList = []
ModifyRepository = []
ResetUserPassword = []
SearchArtifacts = []
SearchByChecksum = []
ShowAudit = []
ShowAutoDeleteJobSettings = []
ShowDomainReleaseRepoStorage = []
ShowFileDetail = []
ShowFileDetailByFullName = []
ShowFileTree = []
ShowLatestVersionFilesCount = []
ShowMavenInfo = []
ShowMultiRolesUserPermissions = []
ShowOpenSourceEnabled = []
ShowPackageDataDetail = []
ShowPackageInfo = []
ShowProjectList = []
ShowProjectReleaseFiles = []
ShowProjectStorageInfo = []
ShowReleaseProjectFiles = []
ShowRepoUserInfo = []
ShowRepository = []
ShowRepositoryInfo = []
ShowRepositoryRolesPrivilege = []
ShowStorage = []
ShowUserPrivileges = []
ShowUserTicket = []
UpdateArtifactory = []
UpdateRepoRolesPrivilege = []
full = ["BatchDeleteTrashes", "BatchRestoreRepo", "CreateArtifactory", "CreateAttention", "CreateDockerRepositories", "CreateMavenRepo", "CreateProjectRelatedRepository", "DeleteArtifactFile", "DeleteCompletelyUpdateFileState", "DeleteRepository", "ListAllRepositories", "ListArtifactoryComponent", "ListArtifactoryStorageStatistic", "ListAttentions", "ListCapacityMessageSetting", "ListChildProxyRepositoriesList", "ListDomainIpConfig", "ListFileBuildArchives", "ListFiles", "ListLatestVersionFiles", "ListMavenList", "ListMavenUser", "ListNetProxy", "ListProjectRolePermissions", "ListProjectUsers", "ListSecGuardList", "ModifyRepository", "ResetUserPassword", "SearchArtifacts", "SearchByChecksum", "ShowAudit", "ShowAutoDeleteJobSettings", "ShowDomainReleaseRepoStorage", "ShowFileDetail", "ShowFileDetailByFullName", "ShowFileTree", "ShowLatestVersionFilesCount", "ShowMavenInfo", "ShowMultiRolesUserPermissions", "ShowOpenSourceEnabled", "ShowPackageDataDetail", "ShowPackageInfo", "ShowProjectList", "ShowProjectReleaseFiles", "ShowProjectStorageInfo", "ShowReleaseProjectFiles", "ShowRepository", "ShowRepositoryInfo", "ShowRepositoryRolesPrivilege", "ShowRepoUserInfo", "ShowStorage", "ShowUserPrivileges", "ShowUserTicket", "UpdateArtifactory", "UpdateRepoRolesPrivilege"]

[lib]
name = "huawei_cloud_api_definitions_CodeArtsArtifact"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-CodeArtsArtifact"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
