[dependencies.chrono]
features = ["serde"]
version = "0"

[dependencies.regress]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.typify]
version = "0"

[features]
BatchDeletePacifyWords = []
BatchExecuteAssetAction = []
Cancel2DDigitalHumanVideo = []
CancelPhotoDigitalHumanVideo = []
CheckRecallKnowledgeLibrary = []
CheckVoiceAsset = []
CommitShortJob = []
CommitVoiceTrainingJob = []
ConfirmFileUpload = []
ConfirmSmarLiveRoom = []
ConfirmTrainingSegment = []
CopyVideoScripts = []
CountTenantResources = []
Create2DDigitalHumanVideo = []
Create2dModelTrainingJob = []
CreateActiveCode = []
CreateAgencyWithRoleType = []
CreateAssetByReplicationInfo = []
CreateAsyncTtsJob = []
CreateAudioRecordConfig = []
CreateBatchKnowledgeQuestion = []
CreateDialogReportConfig = []
CreateDialogUrl = []
CreateDigitalAsset = []
CreateDigitalHumanBusinessCard = []
CreateDocument = []
CreateFile = []
CreateHotQuestion = []
CreateHotWords = []
CreateInstruction = []
CreateInstructionLibrary = []
CreateIntentAndQuestion = []
CreateInteractionRule = []
CreateInteractionRuleGroup = []
CreateInteractiveChat = []
CreateKnowledgeIntent = []
CreateKnowledgeLibrary = []
CreateKnowledgeQuestion = []
CreateKnowledgeSkill = []
CreateLargeFile = []
CreateLivePlatform = []
CreateLlmConfig = []
CreateMcpServer = []
CreateMetaStudioOrders = []
CreateOnceCode = []
CreatePacifyWords = []
CreatePhotoDetection = []
CreatePhotoDigitalHumanVideo = []
CreatePluginConfig = []
CreateProduct = []
CreateQuestionAnswer = []
CreateRobot = []
CreateRole = []
CreateShortJob = []
CreateSmartChatRoom = []
CreateSmartLiveRoom = []
CreateSubtitleFile = []
CreateTrainingAdvanceJob = []
CreateTrainingBasicJob = []
CreateTrainingMiddleJob = []
CreateTrainingThirdPartyJob = []
CreateTtsAudition = []
CreateTtscVocabularyConfigs = []
CreateTtscVocabularyGroups = []
CreateVideoScripts = []
CreateWelcomeSpeech = []
Delete2dModelTrainingJob = []
DeleteActiveCode = []
DeleteAgencyWithRoleType = []
DeleteAsset = []
DeleteAudioRecordConfig = []
DeleteDialogReportConfig = []
DeleteDigitalHumanBusinessCard = []
DeleteDocument = []
DeleteFile = []
DeleteHotQuestion = []
DeleteHotWords = []
DeleteInstruction = []
DeleteInstructionLibrary = []
DeleteInteractionRule = []
DeleteInteractionRuleGroup = []
DeleteKnowledgeIntent = []
DeleteKnowledgeLibrary = []
DeleteKnowledgeQuestion = []
DeleteKnowledgeSkill = []
DeleteLivePlatform = []
DeleteLlmConfig = []
DeleteMcpServer = []
DeletePacifyWords = []
DeletePluginConfig = []
DeleteProduct = []
DeleteQuestionAnswer = []
DeleteRobot = []
DeleteRole = []
DeleteSmartChatRoom = []
DeleteSmartLiveRoom = []
DeleteTask = []
DeleteTtscVocabularyConfigs = []
DeleteTtscVocabularyGroups = []
DeleteVideoScript = []
full = ["BatchDeletePacifyWords", "BatchExecuteAssetAction", "Cancel2DDigitalHumanVideo", "CancelPhotoDigitalHumanVideo", "CheckRecallKnowledgeLibrary", "CheckVoiceAsset", "CommitShortJob", "CommitVoiceTrainingJob", "ConfirmFileUpload", "ConfirmSmarLiveRoom", "ConfirmTrainingSegment", "CopyVideoScripts", "CountTenantResources", "Create2DDigitalHumanVideo", "Create2dModelTrainingJob", "CreateActiveCode", "CreateAgencyWithRoleType", "CreateAssetByReplicationInfo", "CreateAsyncTtsJob", "CreateAudioRecordConfig", "CreateBatchKnowledgeQuestion", "CreateDialogReportConfig", "CreateDialogUrl", "CreateDigitalAsset", "CreateDigitalHumanBusinessCard", "CreateDocument", "CreateFile", "CreateHotQuestion", "CreateHotWords", "CreateInstruction", "CreateInstructionLibrary", "CreateIntentAndQuestion", "CreateInteractionRule", "CreateInteractionRuleGroup", "CreateInteractiveChat", "CreateKnowledgeIntent", "CreateKnowledgeLibrary", "CreateKnowledgeQuestion", "CreateKnowledgeSkill", "CreateLargeFile", "CreateLivePlatform", "CreateLlmConfig", "CreateMcpServer", "CreateMetaStudioOrders", "CreateOnceCode", "CreatePacifyWords", "CreatePhotoDetection", "CreatePhotoDigitalHumanVideo", "CreatePluginConfig", "CreateProduct", "CreateQuestionAnswer", "CreateRobot", "CreateRole", "CreateShortJob", "CreateSmartChatRoom", "CreateSmartLiveRoom", "CreateSubtitleFile", "CreateTrainingAdvanceJob", "CreateTrainingBasicJob", "CreateTrainingMiddleJob", "CreateTrainingThirdPartyJob", "CreateTtsAudition", "CreateTtscVocabularyConfigs", "CreateTtscVocabularyGroups", "CreateVideoScripts", "CreateWelcomeSpeech", "Delete2dModelTrainingJob", "DeleteActiveCode", "DeleteAgencyWithRoleType", "DeleteAsset", "DeleteAudioRecordConfig", "DeleteDialogReportConfig", "DeleteDigitalHumanBusinessCard", "DeleteDocument", "DeleteFile", "DeleteHotQuestion", "DeleteHotWords", "DeleteInstruction", "DeleteInstructionLibrary", "DeleteInteractionRule", "DeleteInteractionRuleGroup", "DeleteKnowledgeIntent", "DeleteKnowledgeLibrary", "DeleteKnowledgeQuestion", "DeleteKnowledgeSkill", "DeleteLivePlatform", "DeleteLlmConfig", "DeleteMcpServer", "DeletePacifyWords", "DeletePluginConfig", "DeleteProduct", "DeleteQuestionAnswer", "DeleteRobot", "DeleteRole", "DeleteSmartChatRoom", "DeleteSmartLiveRoom", "DeleteTask", "DeleteTtscVocabularyConfigs", "DeleteTtscVocabularyGroups", "DeleteVideoScript"]

[lib]
name = "huawei_cloud_api_definitions_MetaStudio"
path = "src/lib.rs"

[package]
authors = ["mingyang91 <mingyang91@qq.com>"]
description = "Huawei Cloud API definitions, generated from OpenAPI spec"
edition = "2021"
license = "MIT"
name = "huawei-cloud-api-definitions-MetaStudio"
repository = "https://github.com/mingyang91/huawei-cloud-api-definitions"
version = "CHANGE_ME"
